/**
 * Mock assessment submissions (local) — links to coach roster athlete ids.
 */

import type { HyroxAssessmentInput } from "@/app/lib/hyroxAthleteProfileTypes";

export const HYROX_MOCK_ASSESSMENT_SUBMISSIONS: Record<string, HyroxAssessmentInput> = {
  /** A) Intermediate, 5 days/week, wall balls weak */
  "priya-n": {
    athleteId: "priya-n",
    submittedAt: "2026-05-10T12:00:00Z",
    name: "Priya Nair",
    email: "priya.n@example.com",
    raceName: "Hyrox London",
    raceDate: "2026-10-03",
    raceCategory: "Hyrox Women Open",
    targetTimeBand: "Sub 1:20",
    trainingDaysPreference: ["Mon", "Tue", "Wed", "Thu", "Sat"],
    weeklyTrainingHoursTarget: 7,
    currentWeeklyRunVolumeKm: 28,
    recentTrainingSummary:
      "3–4 runs/week ~25–30 km · 2 gym sessions · occasional bike. No structured Hyrox block yet.",
    recentThresholdSession: "3×8 min tempo fortnight ago — felt controlled.",
    fiveKmTime: "21:30",
    tenKmTime: "45:00",
    usesHeartRateMonitor: true,
    maxHeartRate: 182,
    thresholdHeartRate: 162,
    experienceHyrox: "some",
    strengthSelfRating: "moderate",
    stationWeaknesses: ["wall_balls", "sled_push_pull", "lunges"],
    equipmentAvailable: {
      track: true,
      sled: true,
      skiErg: true,
      rowErg: true,
      bike: true,
      wallBalls: true,
      farmersHandles: true,
      sandbag: true,
      fullGym: true,
    },
    equipmentLimitations: "No ski at home gym — gym sessions only",
    injuryFlags: ["Low back occasional tightness"],
    sleepQuality: "average",
    stressLevel: "moderate",
    recoveryNotes: "Desk job fatigue afternoons",
    bodyweightKg: 64,
    bodyCompositionGoal: "Lose ~2 kg slowly while keeping strength",
    contentConsent: true,
    documentationConsent: false,
  },

  /** B) Strong runner, sled/wall balls weak */
  "sarah-m": {
    athleteId: "sarah-m",
    submittedAt: "2026-05-12T09:30:00Z",
    name: "Sarah Mitchell",
    email: "sarah.m@example.com",
    raceName: "Hyrox Birmingham",
    raceDate: "2026-09-12",
    raceCategory: "Hyrox Women Open",
    targetTimeBand: "Sub 1:35",
    trainingDaysPreference: ["Tue", "Thu", "Sat", "Sun"],
    weeklyTrainingHoursTarget: 5.5,
    currentWeeklyRunVolumeKm: 22,
    recentTrainingSummary:
      "Running 3–4×/week, building from couch-to-5k background. Minimal strength history.",
    fiveKmTime: "27:00",
    tenKmTime: "",
    usesHeartRateMonitor: false,
    maxHeartRate: 178,
    thresholdHeartRate: null,
    experienceHyrox: "none",
    strengthSelfRating: "moderate",
    stationWeaknesses: ["wall_balls", "burpees", "running_under_fatigue"],
    equipmentAvailable: {
      treadmill: true,
      skiErg: true,
      rowErg: true,
      bike: true,
      wallBalls: true,
      fullGym: true,
    },
    injuryFlags: ["Mild calf tightness historically"],
    sleepQuality: "good",
    stressLevel: "low",
    bodyCompositionGoal: "Maintain weight, slow body comp improvement",
    contentConsent: true,
    documentationConsent: true,
  },

  /** C) Advanced competitive, double-session ready */
  "james-k": {
    athleteId: "james-k",
    submittedAt: "2026-05-08T14:00:00Z",
    name: "James Kerr",
    email: "james.k@example.com",
    raceName: "Hyrox Pro Series",
    raceDate: "2026-08-22",
    raceCategory: "Hyrox Men Pro",
    targetTimeBand: "Top 20%",
    trainingDaysPreference: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    weeklyTrainingHoursTarget: 11,
    currentWeeklyRunVolumeKm: 45,
    recentTrainingSummary:
      "Structured Hyrox block 8 months · 6 days/week · regular threshold and gym. Recent mini-test logged.",
    recentThresholdSession: "6×6 min threshold — controlled last rep.",
    fiveKmTime: "16:45",
    tenKmTime: "35:30",
    usesHeartRateMonitor: true,
    maxHeartRate: 190,
    thresholdHeartRate: 172,
    experienceHyrox: "competitive",
    strengthSelfRating: "high",
    stationWeaknesses: ["wall_balls", "running_under_fatigue"],
    equipmentAvailable: {
      track: true,
      sled: true,
      skiErg: true,
      rowErg: true,
      bike: true,
      wallBalls: true,
      farmersHandles: true,
      sandbag: true,
      fullGym: true,
    },
    injuryFlags: [],
    sleepQuality: "good",
    stressLevel: "moderate",
    bodyCompositionGoal: "Race weight maintenance",
    contentConsent: true,
    documentationConsent: true,
  },

  /** D) Poor recovery / high stress */
  "tom-h": {
    athleteId: "tom-h",
    submittedAt: "2026-05-09T11:15:00Z",
    name: "Tom Hughes",
    email: "tom.h@example.com",
    raceName: "Hyrox Manchester",
    raceDate: "2026-08-01",
    raceCategory: "Hyrox Men Open",
    targetTimeBand: "Sub 1:20",
    trainingDaysPreference: ["Mon", "Tue", "Thu", "Fri", "Sat"],
    weeklyTrainingHoursTarget: 7.5,
    currentWeeklyRunVolumeKm: 30,
    recentTrainingSummary:
      "Usually 5 days/week but sleep poor last 2 weeks — RPE drifting high on easy runs.",
    fiveKmTime: "20:00",
    tenKmTime: "42:00",
    usesHeartRateMonitor: true,
    maxHeartRate: 186,
    thresholdHeartRate: 165,
    experienceHyrox: "some",
    strengthSelfRating: "moderate",
    stationWeaknesses: ["ski", "row", "running_under_fatigue"],
    equipmentAvailable: {
      skiErg: true,
      rowErg: true,
      bike: true,
      fullGym: true,
    },
    equipmentLimitations: "No track access Mon–Fri",
    injuryFlags: ["Fatigue flags — no acute injury"],
    sleepQuality: "poor",
    stressLevel: "high",
    recoveryNotes: "Poor sleep × 2 weeks · high work stress",
    contentConsent: true,
    documentationConsent: true,
  },
};

export function getMockAssessmentForAthlete(
  athleteId: string
): HyroxAssessmentInput | undefined {
  return HYROX_MOCK_ASSESSMENT_SUBMISSIONS[athleteId];
}
