/**
 * Hybrid365 Coach Staples — Kieran's personal Hyrox sessions.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";

const KIERAN_SOURCE = "Kieran personal session" as const;
const KIERAN_TAGS = ["kieran-session", "hybrid365-staple", "coach-staple"] as const;

const SAFETY_DENSITY =
  "Do not place next to heavy legs, threshold run, or another high-stress Hyrox session unless deliberately planned. If recovery is poor, reduce rounds/reps or convert to aerobic support. Movement quality over completion.";

export const KIERAN_COACH_SESSIONS: CoachLibraryEntry[] = [
  buildCoachEntry({
    id: "kieran-bike-wb",
    sessionLibraryId: "coach_kieran-bike-wb",
    name: "Assault Bike Into Wall Balls",
    category: "station_emom",
    subcategory: "Bike + Wall Balls · Station density",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "High HR before wall balls — station density",
    intensityType: "hyrox_density",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    bikeMinutes: 15,
    stationVolume: 60,
    equipmentRequired: ["Assault Bike", "Wall ball"],
    bestFor: [
      "wall_ball_weakness",
      "high_hr_before_wall_balls",
      "station_density",
      "lower_impact_conditioning",
    ],
    avoidIf: [
      "poor_recovery",
      "shoulder_pain",
      "race_week_unless_reduced",
      "beginner_unless_scaled",
    ],
    tags: [...KIERAN_TAGS, "wall_ball", "bike", "density"],
    source: KIERAN_SOURCE,
    similarSessions: ["wb-emom", "wb-under-fatigue", "kieran-four-part-emom"],
    progressionOptions: [
      "Beginner: 3×2 min bike + 8–12 WB · 2 min rest",
      "Intermediate: 4×3 min bike + 15 WB · 90s rest",
      "Advanced: 5–6×3–4 min bike + 18–20 WB",
      "Pro: 6×4 min bike @ 300–400w + 20 WB race load · 60–90s rest",
    ],
    regressionOptions: ["Reduce rounds or bike duration; lower wall ball height/load"],
    editableVariables: [
      "rounds",
      "bikeWatts",
      "bikeDurationMinutes",
      "wallBallReps",
      "rest",
      "rpeTarget",
    ],
    prescription: {
      objective:
        "Execute wall balls under high breathing demand without losing rhythm or depth.",
      warmup: ["5–8 min easy bike or row", "Wall ball prep: 10–15 reps @ light load", "Shoulder mobility"],
      mainSet: [
        "Default 3–6 rounds:",
        "3–4 min Assault Bike @ 300–400w",
        "15–20 wall balls @ race height",
        "Rest 90 sec between rounds",
        "Beginner: 3×2 min bike + 8–12 WB · 2 min rest",
        "Pro: 6×4 min bike + 20 WB race load · 60–90s rest",
      ],
      cooldown: ["Easy spin 5 min", "Shoulder + hip flexor stretch"],
      targetLoad: "Race wall ball load where possible",
      targetRPE: "8–9",
      whatToRecord: [
        "Bike watts each round",
        "Wall ball reps",
        "Breaks / missed reps",
        "RPE",
        "HR response",
        "Technical breakdown on wall balls",
      ],
      coachNote:
        "The goal is to execute wall balls under high breathing demand without losing rhythm or depth.",
      safetyNote: SAFETY_DENSITY,
      progression: "Add rounds before increasing bike wattage.",
      regression: "Reduce bike time or wall ball reps; extend rest to 2 min.",
    },
  }),

  buildCoachEntry({
    id: "kieran-row-burpee-18",
    sessionLibraryId: "coach_kieran-row-burpee-18",
    name: "18-Min Row + Burpee To Plate Continuous EMOM",
    category: "station_emom",
    subcategory: "Row race pace + burpee volume",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Row fatigue into burpee rhythm",
    intensityType: "hyrox_density",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    ergMinutes: 9,
    stationVolume: 60,
    equipmentRequired: ["RowErg", "Plate / box for burpee"],
    bestFor: [
      "burpee_weakness",
      "row_fatigue_into_bodyweight",
      "hyrox_station_tolerance",
      "rhythm_under_fatigue",
    ],
    avoidIf: ["low_back_irritation", "poor_burpee_mechanics", "poor_recovery", "beginner_unless_scaled"],
    tags: [...KIERAN_TAGS, "row", "burpee", "density"],
    source: KIERAN_SOURCE,
    similarSessions: ["burpee-emom", "kieran-four-part-emom"],
    progressionOptions: [
      "Beginner: 3×300m row + 8–10 burpee to plate · 60–90s rest",
      "Intermediate: 3×400–500m row + 12–15 burpee",
      "Advanced: 18 min continuous 500m row @ race pace + 20 burpee to plate (repeat)",
    ],
    editableVariables: [
      "rounds",
      "ergReps",
      "intervalDurationMinutes",
      "burpeeReps",
      "targetSplit",
      "rest",
      "emomMinutes",
    ],
    prescription: {
      objective: "Hold the row controlled enough that burpee rhythm doesn't collapse.",
      warmup: ["5 min easy row", "Burpee to plate skill: 2×5", "Hip hinge prep"],
      mainSet: [
        "18 min continuous — repeat:",
        "500m Row @ race pace",
        "20 burpee to plate",
        "Rest 2–3 min after block if part of larger session",
        "Or 3 rounds continuous with same structure",
        "Beginner: 3×300m + 8–10 burpee · 60–90s between rounds",
      ],
      cooldown: ["Easy row 5 min", "Hip flexor + low back mobility"],
      targetPace: "Race row split",
      targetRPE: "8–9",
      whatToRecord: [
        "Row split per 500m",
        "Burpee reps completed",
        "Total rounds / time",
        "RPE",
        "HR",
        "Pacing breakdown",
      ],
      coachNote: "Hold the row controlled enough that burpee rhythm doesn't collapse.",
      safetyNote: SAFETY_DENSITY,
    },
  }),

  buildCoachEntry({
    id: "kieran-four-part-emom",
    sessionLibraryId: "coach_kieran-four-part-emom",
    name: "Four-Part HYROX EMOM Density Session",
    category: "station_emom",
    subcategory: "Ski + Burpees + Wall Balls + Assault Bike",
    level: "advanced",
    durationMinutes: 60,
    hardDay: true,
    hardDayReason: "Very high station density — multi-EMOM",
    intensityType: "station_density",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "very_high",
    ergMinutes: 10,
    bikeMinutes: 12,
    stationVolume: 120,
    equipmentRequired: [
      "SkiErg",
      "Assault Bike",
      "Wall ball",
      "Box",
      "DBs",
      "Pull-up bar optional",
    ],
    bestFor: [
      "advanced_athletes",
      "station_density",
      "wall_balls_under_fatigue",
      "burpee_conditioning",
      "race_fatigue_tolerance",
      "content_documentation",
    ],
    avoidIf: [
      "beginner",
      "poor_recovery",
      "race_week",
      "shoulder_issues",
      "recent_heavy_legs",
      "cannot_maintain_movement_quality",
    ],
    tags: [...KIERAN_TAGS, "emom", "ski", "burpee", "wall_ball", "bike", "very_high_stress"],
    source: KIERAN_SOURCE,
    similarSessions: ["kieran-bike-wb", "wb-emom", "overload"],
    progressionOptions: [
      "Beginner: one 8–12 min EMOM only, reduced reps",
      "Intermediate: Part 1 only or Part 1 + reduced Part 2",
      "Advanced: full session as written",
      "Pro: race loads, tighter transitions, reduced rest if tolerated",
    ],
    editableVariables: [
      "emomMinutes",
      "skiDistanceM",
      "burpeeReps",
      "wallBallReps",
      "bikeCalories",
      "rest",
      "rounds",
    ],
    prescription: {
      objective:
        "High-stress density session — repeatability and movement quality, not chaos.",
      warmup: ["10 min easy mixed erg", "Movement prep each station", "2×5 wall balls light"],
      mainSet: [
        "Part 1 — 20 min EMOM (rotate ×5):",
        "Min 1: 200m Ski @ race pace",
        "Min 2: 10 burpee over box",
        "Min 3: 15–18 wall balls",
        "Min 4: 12 cal Assault Bike",
        "Rest 3–4 min",
        "Part 2 — 12 min EMOM (×6): Min 1: 10 burpee box jumps · Min 2: 20 wall balls",
        "Rest 4 min",
        "Part 3 — 10 min EMOM (×5): Min 1: 12 DB snatch · Min 2: 12 burpee over DB",
      ],
      cooldown: ["Easy bike 8–10 min", "Full body mobility"],
      targetRPE: "8–9+",
      whatToRecord: [
        "Completion of each EMOM",
        "Reps completed per minute",
        "Missed minutes",
        "HR / RPE",
        "Wall ball breakdown",
        "Burpee rhythm",
        "Movement quality notes",
      ],
      coachNote:
        "This is a high-stress density session. The goal is repeatability and movement quality, not chaos.",
      safetyNote: SAFETY_DENSITY,
      progression: "Complete Part 1 before adding Part 2 and 3.",
      regression: "Single 8–12 min EMOM with reduced reps only.",
    },
  }),

  buildCoachEntry({
    id: "kieran-bike-th-overload",
    sessionLibraryId: "coach_kieran-bike-th-overload",
    name: "Assault Bike Threshold Into Station Overload",
    category: "threshold_runs",
    subcategory: "Bike threshold + lunge overload",
    level: "advanced",
    durationMinutes: 70,
    hardDay: true,
    hardDayReason: "Bike threshold + lunge station overload",
    intensityType: "bike_threshold_overload",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "very_high",
    thresholdMinutes: 25,
    bikeMinutes: 35,
    stationVolume: 12,
    equipmentRequired: ["Assault Bike", "Lunge load / sandbag"],
    bestFor: [
      "advanced_athletes",
      "threshold_without_run_impact",
      "lunges_under_fatigue",
      "high_aerobic_quad_demand",
      "protect_run_volume",
    ],
    avoidIf: [
      "poor_recovery",
      "knee_quad_issues",
      "beginner",
      "heavy_leg_soreness",
      "race_week_unless_reduced",
    ],
    tags: [...KIERAN_TAGS, "threshold", "bike", "lunge", "overload"],
    source: KIERAN_SOURCE,
    similarSessions: ["overload", "kieran-bike-wb", "bike-th-5x5"],
    progressionOptions: [
      "Beginner: 3×3 min bike + 2 rounds short overload",
      "Intermediate: 4×4 min bike + 3 overload rounds",
      "Advanced: 5×5 min @ 300–425w + 4 overload rounds as written",
      "Pro: 5–6×5 min bike + 4–5 overload rounds",
    ],
    editableVariables: [
      "reps",
      "repDurationMinutes",
      "bikeWatts",
      "recovery",
      "rounds",
      "lungeDurationMinutes",
      "stationDetail",
      "rest",
    ],
    prescription: {
      objective:
        "Build threshold and station tolerance without running impact. Keep bike output repeatable.",
      warmup: ["8 min easy bike", "Lunge prep", "Quad activation"],
      mainSet: [
        "Part 1: 5×5 min Assault Bike @ 300–425w · 90s rest",
        "After final bike rep, straight into Part 2:",
        "4 rounds: 2 min bike · 3 min lunges · 1 min bike · Rest 90s",
        "Beginner: 3×3 min bike controlled, then 2 short overload rounds",
      ],
      cooldown: ["Easy spin 10 min", "Quad + hip flexor stretch"],
      targetLoad: "Lunge load from athlete programme",
      targetRPE: "8–9",
      whatToRecord: [
        "Watts per bike interval",
        "HR",
        "Lunge load / distance",
        "RPE",
        "Quad fatigue",
        "Ability to maintain bike output in overload",
      ],
      coachNote:
        "Use this to build threshold and station tolerance without adding running impact. Keep bike output repeatable.",
      safetyNote: SAFETY_DENSITY,
    },
  }),

  buildCoachEntry({
    id: "kieran-race-pace-tempo",
    sessionLibraryId: "coach_kieran-race-pace-tempo",
    name: "HYROX Tempo Race Pace Practice",
    category: "run_development",
    subcategory: "Race pace / tempo",
    level: "intermediate",
    durationMinutes: 55,
    hardDay: true,
    hardDayReason: "5 km race-pace quality running",
    intensityType: "race_pace_tempo",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    sessionStress: "moderate",
    runDistanceKm: 7,
    qualityRunMinutes: 25,
    equipmentRequired: ["Track / treadmill"],
    bestFor: [
      "hyrox_race_pace_practice",
      "rhythm_without_stations",
      "controlled_aerobic_quality",
      "race_build_phase",
    ],
    avoidIf: [
      "beginner_low_run_volume",
      "poor_recovery",
      "cannot_control_pace",
      "too_close_to_hard_run",
    ],
    tags: [...KIERAN_TAGS, "race_pace", "tempo", "run"],
    source: KIERAN_SOURCE,
    preferredDay: "Wed",
    similarSessions: ["tempo", "th-3x10", "5k-8x3"],
    progressionOptions: [
      "Beginner: 1 km WU · 3×1 km @ controlled race effort · 500m float · 1 km WD",
      "Advanced: default with stricter pace control",
      "Pro: longer race-pace sections or shorter floats",
    ],
    editableVariables: [
      "runDistanceM",
      "targetPace",
      "recovery",
      "reps",
      "rpeTarget",
      "hrGuide",
    ],
    prescription: {
      objective:
        "Teaches target HYROX run rhythm — controlled, not a 5 km time trial.",
      warmup: ["2 km easy warm-up", "4×20s strides", "2 min easy"],
      mainSet: [
        "1 km @ target HYROX race pace",
        "500 m float",
        "2 km @ target HYROX race pace",
        "500 m float",
        "2 km @ target HYROX race pace",
        "Total race-pace volume: 5 km within 7 km session",
      ],
      cooldown: ["1 km easy warm-down"],
      targetPace: "Athlete HYROX race pace from testing",
      targetRPE: "6–7 on race-pace sections",
      whatToRecord: [
        "Pace each race-pace section",
        "Float pace",
        "HR",
        "RPE",
        "Whether race pace felt controlled",
        "HR drift across reps",
      ],
      coachNote:
        "This teaches target HYROX run rhythm. It should feel controlled, not like a 5 km time trial.",
      safetyNote: "Avoid day before threshold run or heavy legs unless deliberately planned.",
    },
  }),
];

/** Tag existing overload staple as a Kieran/Hybrid365 coach staple for the dedicated folder. */
export function enrichCoachStapleEntry(entry: CoachLibraryEntry): CoachLibraryEntry {
  if (entry.id !== "overload") return entry;
  return {
    ...entry,
    source: KIERAN_SOURCE,
    tags: [...new Set([...entry.tags, ...KIERAN_TAGS])],
    similarSessions: [
      ...(entry.similarSessions ?? []),
      "kieran-four-part-emom",
      "kieran-bike-th-overload",
    ],
    prescription: {
      ...entry.prescription,
      safetyNote: entry.prescription.safetyNote ?? SAFETY_DENSITY,
    },
  };
}
