/**
 * HYROX-specific 1-1 coach library — technique, efficiency, strength endurance,
 * compromised running, station clusters, race execution and density.
 *
 * Additive only. Existing library IDs are unchanged. Assigned sessions remain snapshots.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";
import type { ProgrammingSessionStandards } from "@/app/lib/hyrox-team/modules/programmingSystem/types";

const SRC = "Hybrid365 library" as const;

function standards(partial: ProgrammingSessionStandards): ProgrammingSessionStandards {
  return partial;
}

function spec(
  input: Omit<Parameters<typeof buildCoachEntry>[0], "source">
): CoachLibraryEntry {
  return buildCoachEntry({
    ...input,
    source: SRC,
    tags: Array.from(
      new Set([...(input.tags ?? []), "hyrox", "hyrox-specific", "not_generic_threshold"])
    ),
  });
}

const GENERIC_PACE =
  "Use athlete-specific HYROX target pace / threshold pace / prescribed split — do not chase a universal number.";
const GENERIC_LOAD =
  "Load: race load or coach-prescribed overload. Keep technique unbroken; drop load before form collapses.";

export const HYROX_SPECIFIC_COACH_SESSIONS: CoachLibraryEntry[] = [
  spec({
    id: "hxspec-sled-easy-technique",
    sessionLibraryId: "coach_hxspec_sled_easy_technique",
    name: "Sled — Easy Technique",
    category: "hyrox_volume_builders",
    subcategory: "sled · technique",
    level: "all",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "strength",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 150,
    equipmentRequired: ["Sled", "Open floor ≥25m"],
    bestFor: ["technique_block", "alongside_threshold", "sled_skill"],
    avoidIf: [],
    tags: [
      "technique",
      "easy-technique",
      "sled",
      "sled_push",
      "sled_pull",
      "efficiency",
      "stimulus-technique",
    ],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-sled-technique-volume",
    editableVariables: ["sledLoad", "distanceM", "bouts"],
    programmingStandards: standards({
      purpose: "Teach sled push/pull positions at easy intensity without creating a hard day.",
      primaryAdaptation: "sled_technique",
      secondaryAdaptation: "movement_confidence",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Sled", "Open floor ≥25m"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "deload",
      recommendedProgression: "Sled — Technique + Volume",
      recommendedRegression: "3×12.5m each · longer rest",
      suggestedSessionPlacement: ["easy_day", "after_threshold_plus_6h", "deload"],
      adjacencyWarnings: ["race_simulation"],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Load", "Body-angle notes", "Session RPE"],
    }),
    prescription: {
      objective:
        "Sled technique / RPE 4–5. Groove body angle, foot turnover, push position, rope collection and pull rhythm with full recovery.",
      warmup: ["5 min easy bike or row", "2×10 bodyweight squats + hip hinges", "2×12.5m empty-sled feel"],
      mainSet: [
        "Part 1 — Sled push technique",
        "5×20m sled push @ submaximal / coach-prescribed light-moderate load",
        "Walk back · full recovery between reps (≈60–90s)",
        "Cues: forward lean from ankles, short steps, arms locked, no grinding finish",
        "Part 2 — Sled pull technique",
        "5×20m sled pull @ same submaximal load",
        "Full recovery. Cues: hips low, long pulls, constant strap tension, tidy rope collection and turn",
        GENERIC_LOAD,
      ],
      cooldown: ["4 min easy walk", "Hip flexor + calf stretch"],
      targetLoad: "Submaximal technique load",
      targetRPE: "4–5",
      whatToRecord: ["Load used", "Which cue improved position", "Session RPE"],
      coachNote: "This is exposure, not a hard station day. It can sit beside threshold running.",
      progression: "Sled — Technique + Volume",
      regression: "3×12.5–20m each · extra rest.",
    },
  }),
  spec({
    id: "hxspec-sled-technique-volume",
    sessionLibraryId: "coach_hxspec_sled_technique_volume",
    name: "Sled — Technique + Volume",
    category: "hyrox_volume_builders",
    subcategory: "sled · technique_volume",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 250,
    equipmentRequired: ["Sled", "Open floor ≥25m"],
    bestFor: ["sled_skill", "build_block"],
    avoidIf: ["high_doms_state"],
    tags: ["technique", "sled", "sled_push", "sled_pull", "volume", "stimulus-volume"],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-sled-strength-endurance",
    recommendedRegression: "hxspec-sled-easy-technique",
    editableVariables: ["bouts", "distanceM", "sledLoad"],
    programmingStandards: standards({
      purpose: "Increase easy sled exposure while keeping technique the limiter, not fatigue.",
      primaryAdaptation: "sled_technical_volume",
      secondaryAdaptation: "local_endurance_intro",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Sled"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Sled — Strength Endurance",
      recommendedRegression: "Sled — Easy Technique",
      suggestedSessionPlacement: ["secondary_station_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "5",
      recommendedLoggingFields: ["Bouts", "Load", "RPE"],
    }),
    prescription: {
      objective: "Sled technique + volume / RPE 5. More metres, still submaximal, still full recoveries.",
      warmup: ["5 min easy erg", "2×15m light push + 2×15m light pull"],
      mainSet: [
        "6×25m sled push @ submaximal race-feel load · walk-back full recovery",
        "6×25m sled pull @ same load · full recovery",
        "Optional: 2 controlled 180° turns each side focusing on rope/handle reset",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk 4 min"],
      targetRPE: "5",
      whatToRecord: ["Load", "Bouts completed unbroken", "RPE"],
      coachNote: "If any bout grinds, drop load immediately. Quality over extra plates.",
    },
  }),
  spec({
    id: "hxspec-wb-efficiency",
    sessionLibraryId: "coach_hxspec_wb_efficiency",
    name: "Wall Balls — Efficiency",
    category: "station_emom",
    subcategory: "wall_ball · efficiency",
    level: "all",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 120,
    equipmentRequired: ["Wall ball", "Target"],
    bestFor: ["wall_ball_skill", "alongside_running"],
    avoidIf: [],
    tags: ["technique", "efficiency", "wall_ball", "stimulus-efficiency"],
    progressionFamily: "wall_ball_density_builder",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-wb-efficiency-emom",
    editableVariables: ["reps", "sets", "ballWeight"],
    programmingStandards: standards({
      purpose: "Build repeatable wall-ball rhythm, catch position and breathing without muscular junk fatigue.",
      primaryAdaptation: "wall_ball_efficiency",
      secondaryAdaptation: "breathing_rhythm",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Wall ball"],
      progressionFamily: "wall_ball_density_builder",
      progressionLevel: "deload",
      recommendedProgression: "Wall Balls — Efficiency EMOM",
      recommendedRegression: "8×12 reps",
      suggestedSessionPlacement: ["easy_day", "skill_session"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Unbroken sets", "Missed targets", "RPE"],
    }),
    prescription: {
      objective:
        "Wall ball efficiency / RPE 4–5. Breathing, catch, squat rhythm and accuracy — avoid unnecessary muscular fatigue.",
      warmup: ["3 min easy ski or bike", "10 empty-wall-ball squat + throw pattern"],
      mainSet: [
        "8×15–20 wall balls @ race-height target · race-weight or slightly lighter if accuracy fails",
        "Full recovery between sets (walk / 4–6 easy breaths)",
        "Cues: catch high, ride the bounce, exhale on throw, same squat depth every rep",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 4 min", "Shoulder + hip openers"],
      targetRPE: "4–5",
      whatToRecord: ["Set sizes", "Target misses", "RPE"],
      coachNote: "Stop a set 2–3 reps before form noise. This is not a density test.",
    },
  }),
  spec({
    id: "hxspec-wb-efficiency-emom",
    sessionLibraryId: "coach_hxspec_wb_efficiency_emom",
    name: "Wall Balls — Efficiency EMOM",
    category: "station_emom",
    subcategory: "wall_ball · emom_efficiency",
    level: "intermediate",
    durationMinutes: 30,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 100,
    equipmentRequired: ["Wall ball"],
    bestFor: ["wall_ball_skill"],
    avoidIf: [],
    tags: ["technique", "efficiency", "wall_ball", "emom", "stimulus-efficiency"],
    progressionFamily: "wall_ball_density_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-wb-density",
    recommendedRegression: "hxspec-wb-efficiency",
    editableVariables: ["emomMinutes", "repsPerMinute"],
    programmingStandards: standards({
      purpose: "Low-fatigue clocked wall-ball exposure for rhythm under a light density constraint.",
      primaryAdaptation: "wall_ball_repeatability",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 30,
      estimatedFatigueCost: "low",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball"],
      progressionFamily: "wall_ball_density_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Wall Balls — Density",
      recommendedRegression: "Wall Balls — Efficiency",
      suggestedSessionPlacement: ["skill_day"],
      adjacencyWarnings: [],
      expectedRpe: "5",
      recommendedLoggingFields: ["Reps/min", "Rest remaining", "RPE"],
    }),
    prescription: {
      objective: "Wall ball efficiency EMOM / RPE 5. Stay well inside redline; own the leftover seconds.",
      warmup: ["3 min easy erg", "2×10 easy wall balls"],
      mainSet: [
        "12 min EMOM: 8–12 wall balls (choose a number that leaves ≥20s rest)",
        "If rest drops below 15s, cut 2 reps next minute",
        "Breathing must stay repeatable — this is not a race break test",
      ],
      cooldown: ["Easy walk 3 min"],
      targetRPE: "5",
      whatToRecord: ["Reps chosen", "Minutes completed", "RPE"],
      coachNote: "Clock is a rhythm tool, not a hammer.",
    },
  }),
  spec({
    id: "hxspec-bbj-easy-technique",
    sessionLibraryId: "coach_hxspec_bbj_easy_technique",
    name: "BBJ — Easy Technique",
    category: "hyrox_volume_builders",
    subcategory: "bbj · technique",
    level: "all",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 120,
    equipmentRequired: ["Open floor ≥20m"],
    bestFor: ["bbj_skill"],
    avoidIf: ["acute_calf_issue"],
    tags: ["technique", "bbj", "burpee", "stimulus-technique"],
    progressionFamily: "burpee_economy_builder",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-bbj-repeatability",
    editableVariables: ["distanceM", "bouts"],
    programmingStandards: standards({
      purpose: "Teach repeatable burpee broad-jump length, get-up and breathing with walk-back recovery.",
      primaryAdaptation: "bbj_technique",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Open floor"],
      progressionFamily: "burpee_economy_builder",
      progressionLevel: "deload",
      recommendedProgression: "BBJ — Repeatability",
      recommendedRegression: "6×15m",
      suggestedSessionPlacement: ["easy_day"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Jump length feel", "RPE"],
    }),
    prescription: {
      objective:
        "BBJ technique / RPE 4–5. Repeatable jump length, low wasted vertical, efficient get-up, breathing.",
      warmup: ["3 min easy jog", "6 squat-to-stand + 4 easy burpees"],
      mainSet: [
        "8×20m burpee broad jump",
        "Walk back / full recovery between reps",
        "Cues: long jump not high jump, soft land, stand tall before next drop, exhale on the jump",
      ],
      cooldown: ["Easy walk 4 min"],
      targetRPE: "4–5",
      whatToRecord: ["How jump length held", "RPE"],
      coachNote: "No sprinting the station. Film 1–2 reps if useful.",
    },
  }),
  spec({
    id: "hxspec-lunge-easy-technique",
    sessionLibraryId: "coach_hxspec_lunge_easy_technique",
    name: "Lunges — Easy Technique",
    category: "hyrox_volume_builders",
    subcategory: "lunge · technique",
    level: "all",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "strength",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 140,
    equipmentRequired: ["Sandbag or similar", "Open floor ≥20m"],
    bestFor: ["lunge_skill"],
    avoidIf: ["acute_knee_pain"],
    tags: ["technique", "lunges", "stimulus-technique"],
    progressionFamily: "lunge_durability_builder",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-lunge-strength-endurance",
    editableVariables: ["distanceM", "load", "bouts"],
    programmingStandards: standards({
      purpose: "Groove lunge posture, stride length, knee track, breathing and turns at submaximal load.",
      primaryAdaptation: "lunge_technique",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Sandbag"],
      progressionFamily: "lunge_durability_builder",
      progressionLevel: "deload",
      recommendedProgression: "Lunges — Strength Endurance",
      recommendedRegression: "Bodyweight 6×20m",
      suggestedSessionPlacement: ["easy_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Load", "Posture notes", "RPE"],
    }),
    prescription: {
      objective: "Lunge technique / RPE 4–5. Posture, stride, stable knee, breathing, efficient turns.",
      warmup: ["3 min easy bike", "10 reverse lunges each side unweighted"],
      mainSet: [
        "7×20m walking lunges @ moderate/submaximal sandbag (or race bag if position stays tidy)",
        "Walk back / full recovery",
        "Cues: tall chest, even stride, knee tracks, bag quiet, controlled 180° turn",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk + hip flexor stretch"],
      targetRPE: "4–5",
      whatToRecord: ["Load", "Turn quality", "RPE"],
      coachNote: "If torso folds, drop load. Technique day.",
    },
  }),
  spec({
    id: "hxspec-ski-easy-technique",
    sessionLibraryId: "coach_hxspec_ski_easy_technique",
    name: "Ski — Easy Technique",
    category: "easy_erg",
    subcategory: "ski · technique",
    level: "all",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    sessionStress: "moderate",
    ergMinutes: 30,
    equipmentRequired: ["SkiErg"],
    bestFor: ["ski_skill", "easy_aerobic"],
    avoidIf: [],
    tags: ["technique", "ski", "stimulus-technique"],
    progressionFamily: "ski_engine",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-ski-wb-fatigue",
    editableVariables: ["reps", "distanceM"],
    programmingStandards: standards({
      purpose: "Ski stroke rhythm, hip involvement and sustainable rate at easy aerobic cost.",
      primaryAdaptation: "ski_technique",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["SkiErg"],
      progressionFamily: "ski_engine",
      progressionLevel: "deload",
      recommendedProgression: "Ski + Wall Balls — Fatigue Resistance",
      recommendedRegression: "8 min easy continuous",
      suggestedSessionPlacement: ["easy_day"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Split", "Stroke rate", "RPE"],
    }),
    prescription: {
      objective: "Ski technique / RPE 4–5. Stroke rhythm, hips, efficient return, sustainable rate.",
      warmup: ["4 min easy ski pick-up"],
      mainSet: [
        "10×250m ski @ controlled / target Ski pace (easy)",
        "45–60s easy paddle recovery",
        "Or: 3×6 min easy continuous technique blocks · 90s rest",
        "Cues: long catch, close the hips, relaxed return, rate you could hold twice as long",
        GENERIC_PACE,
      ],
      cooldown: ["3 min very easy ski"],
      targetRPE: "4–5",
      whatToRecord: ["Avg split", "Stroke rate", "RPE"],
      coachNote: "Aerobic technique, not erg intervals.",
    },
  }),
  spec({
    id: "hxspec-row-easy-technique",
    sessionLibraryId: "coach_hxspec_row_easy_technique",
    name: "Row — Easy Technique",
    category: "easy_erg",
    subcategory: "row · technique",
    level: "all",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    sessionStress: "moderate",
    ergMinutes: 30,
    equipmentRequired: ["RowErg"],
    bestFor: ["row_skill", "easy_aerobic"],
    avoidIf: [],
    tags: ["technique", "row", "stimulus-technique"],
    progressionFamily: "row_engine",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-row-lunge-fatigue",
    editableVariables: ["reps", "distanceM"],
    programmingStandards: standards({
      purpose: "Row sequence, connection and sustainable output at easy intensity.",
      primaryAdaptation: "row_technique",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["RowErg"],
      progressionFamily: "row_engine",
      progressionLevel: "deload",
      recommendedProgression: "Row + Lunges — Fatigue Resistance",
      recommendedRegression: "6×400m",
      suggestedSessionPlacement: ["easy_day"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Split", "Stroke rate", "RPE"],
    }),
    prescription: {
      objective: "Row technique / RPE 4–5. Legs-body-arms sequence, connection, sustainable rate.",
      warmup: ["4 min easy row"],
      mainSet: [
        "8×500m row @ controlled / target Row pace (easy)",
        "60–75s easy paddle",
        "Cues: early leg drive, late arm draw, unhurried recovery, hold a split you could repeat",
        GENERIC_PACE,
      ],
      cooldown: ["3 min very easy row"],
      targetRPE: "4–5",
      whatToRecord: ["Avg split", "Stroke rate", "RPE"],
      coachNote: "Sequence first, watts second.",
    },
  }),
  spec({
    id: "hxspec-hyrox-technique-flow-easy",
    sessionLibraryId: "coach_hxspec_hyrox_technique_flow_easy",
    name: "HYROX Technique Flow — Easy",
    category: "hyrox_volume_builders",
    subcategory: "mixed · technique_flow",
    level: "all",
    durationMinutes: 50,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 180,
    equipmentRequired: ["SkiErg", "Sled", "Open floor", "Dumbbells or farmers handles", "Sandbag", "Wall ball", "RowErg"],
    bestFor: ["movement_quality", "transitions"],
    avoidIf: [],
    tags: ["technique", "mixed-hyrox", "stimulus-technique", "hyrox"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "deload",
    recommendedProgression: "hxspec-hyrox-technique-flow-front",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Easy continuous HYROX movement practice and transitions — not race simulation.",
      primaryAdaptation: "hyrox_movement_quality",
      secondaryAdaptation: "transition_practice",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["HYROX stations"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "deload",
      recommendedProgression: "HYROX Technique Flow — Front Half",
      recommendedRegression: "3 rounds, skip one station",
      suggestedSessionPlacement: ["easy_hyrox_day"],
      adjacencyWarnings: ["race_simulation"],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Rounds", "Where technique broke", "RPE"],
    }),
    prescription: {
      objective:
        "HYROX technique flow / RPE 4–5. Movement quality, transitions, aerobic station practice — NOT a race sim.",
      warmup: ["4 min easy ski", "Light joint prep"],
      mainSet: [
        "4 rounds, easy continuous:",
        "500m Ski · 20m sled push · 20m sled pull · 10 BBJ · 20m farmers · 20m lunges · 15 wall balls · 500m Row",
        "Shake out 60–90s between rounds if quality drops",
        "Loads: submaximal / race implements only if positions stay easy",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk 5 min"],
      targetRPE: "4–5",
      whatToRecord: ["Rounds", "Messiest station", "RPE"],
      coachNote: "If it starts to look like a workout, slow down.",
    },
  }),
  spec({
    id: "hxspec-hyrox-technique-flow-front",
    sessionLibraryId: "coach_hxspec_hyrox_technique_flow_front",
    name: "HYROX Technique Flow — Front Half",
    category: "hyrox_volume_builders",
    subcategory: "mixed · front_half_technique",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 140,
    equipmentRequired: ["SkiErg", "Sled", "Open floor"],
    bestFor: ["front_half_skill"],
    avoidIf: [],
    tags: ["technique", "mixed-hyrox", "ski", "sled_push", "sled_pull", "bbj"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-front-half-cluster",
    recommendedRegression: "hxspec-hyrox-technique-flow-easy",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Easy/moderate front-half station flow: ski, sleds, BBJ and short run links.",
      primaryAdaptation: "front_half_technique",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["SkiErg", "Sled"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Front Half — Technique Cluster",
      recommendedRegression: "HYROX Technique Flow — Easy",
      suggestedSessionPlacement: ["skill_day"],
      adjacencyWarnings: [],
      expectedRpe: "5",
      recommendedLoggingFields: ["Rounds", "RPE"],
    }),
    prescription: {
      objective: "Front-half technique flow / RPE 5. Ski, sleds, BBJ quality — not a race piece.",
      warmup: ["4 min easy ski"],
      mainSet: [
        "5 rounds easy:",
        "400m Ski · 20m sled push · 20m sled pull · 8–10 BBJ · 200m easy run",
        "Full technique standard; 45–60s between rounds if needed",
      ],
      cooldown: ["Easy row 4 min"],
      targetRPE: "5",
      whatToRecord: ["Rounds", "RPE"],
      coachNote: "Keep the run as a mechanic reset, not a threshold injection.",
    },
  }),
  spec({
    id: "hxspec-hyrox-technique-flow-back",
    sessionLibraryId: "coach_hxspec_hyrox_technique_flow_back",
    name: "HYROX Technique Flow — Back Half",
    category: "hyrox_volume_builders",
    subcategory: "mixed · back_half_technique",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "easy_technique",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 140,
    equipmentRequired: ["RowErg", "Farmers handles", "Sandbag", "Wall ball"],
    bestFor: ["back_half_skill"],
    avoidIf: [],
    tags: ["technique", "mixed-hyrox", "row", "farmers", "lunges", "wall_ball"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-back-half-cluster",
    recommendedRegression: "hxspec-hyrox-technique-flow-easy",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Easy/moderate back-half flow: row, farmers, lunges, wall balls.",
      primaryAdaptation: "back_half_technique",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["RowErg", "Farmers", "Sandbag", "Wall ball"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Back Half — Strength Endurance Cluster",
      recommendedRegression: "HYROX Technique Flow — Easy",
      suggestedSessionPlacement: ["skill_day"],
      adjacencyWarnings: [],
      expectedRpe: "5",
      recommendedLoggingFields: ["Rounds", "RPE"],
    }),
    prescription: {
      objective: "Back-half technique flow / RPE 5. Row, farmers, lunges, wall balls — aerobic and tidy.",
      warmup: ["4 min easy row"],
      mainSet: [
        "5 rounds easy:",
        "400m Row · 20m farmers · 20m lunges · 12–15 wall balls · 200m easy run",
        "Reset 45–60s between rounds if quality drops",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk 4 min"],
      targetRPE: "5",
      whatToRecord: ["Rounds", "Grip/lunge notes", "RPE"],
      coachNote: "Farmers and lunges stay submaximal. No death-march finishes.",
    },
  }),
  spec({
    id: "hxspec-sled-strength-endurance",
    sessionLibraryId: "coach_hxspec_sled_strength_endurance",
    name: "Sled — Strength Endurance",
    category: "hyrox_volume_builders",
    subcategory: "sled · strength_endurance",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Repeated race-load sled bouts",
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 250,
    equipmentRequired: ["Sled", "Open floor ≥25m"],
    bestFor: ["sled_weakness", "strength_endurance_block"],
    avoidIf: ["race_week", "high_doms_state"],
    tags: ["sled", "sled_push", "sled_pull", "strength-endurance", "stimulus-strength-endurance", "hard"],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-sled-to-run",
    recommendedRegression: "hxspec-sled-technique-volume",
    editableVariables: ["rounds", "sledLoad", "restSeconds"],
    programmingStandards: standards({
      purpose: "Build sled strength-endurance at race load / coach-prescribed overload with honest recovery.",
      primaryAdaptation: "sled_strength_endurance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Sled → Run — Compromised",
      recommendedRegression: "Sled — Technique + Volume",
      suggestedSessionPlacement: ["key_station_day", "not_before_threshold"],
      adjacencyWarnings: ["heavy_leg_strength", "long_compromised_running"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Load", "Rounds", "RPE"],
    }),
    prescription: {
      objective: "Sled strength endurance / RPE 7. Repeatable 25m push+pull at race load or coach-prescribed overload.",
      warmup: ["6 min easy bike", "2×15m build-up sled push/pull"],
      mainSet: [
        "5 rounds:",
        "25m sled push + 25m sled pull @ race load / coach-prescribed overload",
        "2–3 min walk recovery between rounds",
        "Stop the set if stride length collapses or hips shoot up",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 5 min"],
      targetRPE: "7",
      whatToRecord: ["Load", "Rounds unbroken", "RPE"],
      coachNote: "Hard station day. Do not pair with long compromised running.",
    },
  }),
  spec({
    id: "hxspec-wb-density",
    sessionLibraryId: "coach_hxspec_wb_density",
    name: "Wall Balls — Density",
    category: "station_emom",
    subcategory: "wall_ball · density",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Wall-ball accumulation density",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 200,
    equipmentRequired: ["Wall ball"],
    bestFor: ["wall_ball_weakness"],
    avoidIf: ["race_week"],
    tags: ["wall_ball", "density", "strength-endurance", "stimulus-strength-endurance", "hard"],
    progressionFamily: "wall_ball_density_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-wb-to-run",
    recommendedRegression: "hxspec-wb-efficiency-emom",
    editableVariables: ["workMinutes", "recoverySeconds"],
    programmingStandards: standards({
      purpose: "Accumulate quality wall-ball volume in timed sets without turning it into a max test.",
      primaryAdaptation: "wall_ball_density",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball"],
      progressionFamily: "wall_ball_density_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Wall Balls → Run — Compromised",
      recommendedRegression: "Wall Balls — Efficiency EMOM",
      suggestedSessionPlacement: ["station_day"],
      adjacencyWarnings: ["high_wall_ball_volume"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Reps per set", "Break pattern", "RPE"],
    }),
    prescription: {
      objective: "Wall ball density / RPE 7. Quality accumulation — planned breaks, not panic breaking.",
      warmup: ["4 min easy ski", "2×12 easy wall balls"],
      mainSet: [
        "Option A: 5×3 min quality wall-ball accumulation · 90s recovery",
        "Stay at sustainable race-break strategy (e.g. 15s or 10s), not to failure",
        "Option B (alternate): 12 min EMOM 10–15 wall balls leaving ≥15s rest",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 5 min"],
      targetRPE: "7",
      whatToRecord: ["Reps/set", "Break plan used", "RPE"],
      coachNote: "Pick A or B — do not combine. Density, not heroics.",
    },
  }),
  spec({
    id: "hxspec-lunge-strength-endurance",
    sessionLibraryId: "coach_hxspec_lunge_strength_endurance",
    name: "Lunges — Strength Endurance",
    category: "hyrox_volume_builders",
    subcategory: "lunge · strength_endurance",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Weighted lunge repeats",
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 200,
    equipmentRequired: ["Sandbag", "Open floor"],
    bestFor: ["lunge_weakness"],
    avoidIf: ["acute_knee_pain", "race_week"],
    tags: ["lunges", "strength-endurance", "stimulus-strength-endurance", "hard"],
    progressionFamily: "lunge_durability_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-lunge-to-run",
    recommendedRegression: "hxspec-lunge-easy-technique",
    editableVariables: ["rounds", "distanceM", "load"],
    programmingStandards: standards({
      purpose: "Build weighted-lunge strength endurance with aerobic recovery between bouts.",
      primaryAdaptation: "lunge_strength_endurance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sandbag"],
      progressionFamily: "lunge_durability_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Lunges → Run — Compromised",
      recommendedRegression: "Lunges — Easy Technique",
      suggestedSessionPlacement: ["station_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Load", "Rounds", "RPE"],
    }),
    prescription: {
      objective: "Lunge strength endurance / RPE 7. 40m repeats at race load with honest recovery.",
      warmup: ["5 min easy bike", "20m unweighted lunges"],
      mainSet: [
        "5 rounds:",
        "40m weighted lunges @ race load / coach-prescribed",
        "60–90s easy bike, ski or walk recovery",
        "Posture standard: if you fold, rest longer or drop load",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 5 min"],
      targetRPE: "7",
      whatToRecord: ["Load", "Rounds", "RPE"],
      coachNote: "Pair with easy running the next day, not another leg-station hammer.",
    },
  }),
  spec({
    id: "hxspec-bbj-repeatability",
    sessionLibraryId: "coach_hxspec_bbj_repeatability",
    name: "BBJ — Repeatability",
    category: "hyrox_volume_builders",
    subcategory: "bbj · strength_endurance",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Repeated 40m BBJ",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 240,
    equipmentRequired: ["Open floor ≥40m"],
    bestFor: ["bbj_weakness"],
    avoidIf: ["acute_calf_issue"],
    tags: ["bbj", "strength-endurance", "stimulus-strength-endurance", "hard"],
    progressionFamily: "burpee_economy_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-bbj-to-run",
    recommendedRegression: "hxspec-bbj-easy-technique",
    editableVariables: ["reps", "distanceM", "restSeconds"],
    programmingStandards: standards({
      purpose: "Improve BBJ repeatability at controlled-hard effort with enough recovery to keep jump length.",
      primaryAdaptation: "bbj_repeatability",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Open floor"],
      progressionFamily: "burpee_economy_builder",
      progressionLevel: "level_2",
      recommendedProgression: "BBJ → Run — Compromised",
      recommendedRegression: "BBJ — Easy Technique",
      suggestedSessionPlacement: ["station_day"],
      adjacencyWarnings: [],
      expectedRpe: "7",
      recommendedLoggingFields: ["Bouts", "Jump quality", "RPE"],
    }),
    prescription: {
      objective: "BBJ repeatability / RPE 7. Controlled hard 40m reps — jump length must stay honest.",
      warmup: ["5 min easy jog", "4× easy 10m BBJ"],
      mainSet: [
        "6×40m burpee broad jump",
        "60–90s walk recovery",
        "If jump length dies, extend rest rather than shortening the jump",
      ],
      cooldown: ["Easy jog 4 min"],
      targetRPE: "7",
      whatToRecord: ["Bouts", "Where length dropped", "RPE"],
      coachNote: "Controlled hard, not a sprint-burpee smash.",
    },
  }),
  spec({
    id: "hxspec-ski-wb-fatigue",
    sessionLibraryId: "coach_hxspec_ski_wb_fatigue",
    name: "Ski + Wall Balls — Fatigue Resistance",
    category: "hyrox_compromised",
    subcategory: "ski_wallball · fatigue_resistance",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Ski + wall-ball couplet repeats",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 180,
    ergMinutes: 20,
    equipmentRequired: ["SkiErg", "Wall ball"],
    bestFor: ["wall_ball_weakness", "ski_support"],
    avoidIf: ["race_week"],
    tags: ["ski", "wall_ball", "fatigue-resistance", "stimulus-fatigue-resistance", "hard"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-wb-to-run",
    recommendedRegression: "hxspec-wb-efficiency",
    editableVariables: ["rounds", "skiDistanceM", "wallBallReps"],
    programmingStandards: standards({
      purpose: "Hold wall-ball quality after ski fatigue without racing the couplet.",
      primaryAdaptation: "station_fatigue_resistance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["SkiErg", "Wall ball"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Wall Balls → Run — Compromised",
      recommendedRegression: "Wall Balls — Efficiency",
      suggestedSessionPlacement: ["hybrid_station_day"],
      adjacencyWarnings: ["high_wall_ball_volume"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Rounds", "WB break pattern", "RPE"],
    }),
    prescription: {
      objective: "Ski + wall-ball fatigue resistance / RPE 7. Keep throws accurate after the ski.",
      warmup: ["4 min easy ski", "10 easy wall balls"],
      mainSet: [
        "5 rounds:",
        "500m Ski @ target Ski pace (controlled)",
        "20–30 wall balls @ race weight / planned break strategy",
        "60–90s recovery",
        GENERIC_PACE,
      ],
      cooldown: ["Easy row 4 min"],
      targetRPE: "7",
      whatToRecord: ["Ski split", "WB breaks", "RPE"],
      coachNote: "First wall-ball reps after the ski are the session.",
    },
  }),
  spec({
    id: "hxspec-row-lunge-fatigue",
    sessionLibraryId: "coach_hxspec_row_lunge_fatigue",
    name: "Row + Lunges — Fatigue Resistance",
    category: "hyrox_compromised",
    subcategory: "row_lunge · fatigue_resistance",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Row + lunge couplet",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 160,
    ergMinutes: 20,
    equipmentRequired: ["RowErg", "Sandbag"],
    bestFor: ["lunge_weakness", "row_support"],
    avoidIf: ["acute_knee_pain"],
    tags: ["row", "lunges", "fatigue-resistance", "stimulus-fatigue-resistance", "hard"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-lunge-to-run",
    recommendedRegression: "hxspec-lunge-easy-technique",
    editableVariables: ["rounds", "rowDistanceM", "lungeDistanceM"],
    programmingStandards: standards({
      purpose: "Hold lunge posture after rowing fatigue.",
      primaryAdaptation: "lunge_fatigue_resistance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["RowErg", "Sandbag"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Lunges → Run — Compromised",
      recommendedRegression: "Lunges — Easy Technique",
      suggestedSessionPlacement: ["hybrid_station_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Rounds", "Lunge posture notes", "RPE"],
    }),
    prescription: {
      objective: "Row + lunge fatigue resistance / RPE 7. Tall lunges after the erg, not a collapse.",
      warmup: ["4 min easy row", "20m easy lunges"],
      mainSet: [
        "5 rounds:",
        "500m Row @ target Row pace (controlled)",
        "20–40m weighted lunges @ race load",
        "60–90s recovery",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk 5 min"],
      targetRPE: "7",
      whatToRecord: ["Row split", "Lunge distance/load", "RPE"],
      coachNote: "Shorten lunge distance before you shorten rest if posture fails.",
    },
  }),
  spec({
    id: "hxspec-sled-to-run",
    sessionLibraryId: "coach_hxspec_sled_to_run",
    name: "Sled → Run — Compromised",
    category: "hyrox_compromised",
    subcategory: "sled_to_run",
    level: "intermediate",
    durationMinutes: 55,
    hardDay: true,
    hardDayReason: "Sled then quality run repeats",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 5,
    qualityRunMinutes: 25,
    stationVolume: 125,
    equipmentRequired: ["Sled", "Run route / treadmill"],
    bestFor: ["compromised_running", "sled_weakness"],
    avoidIf: ["race_week", "poor_recovery_state"],
    tags: ["sled", "sled_push", "running", "compromised-running", "stimulus-compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-sled-race-execution",
    recommendedRegression: "hxspec-sled-strength-endurance",
    editableVariables: ["rounds", "runDistanceM", "sledLoad"],
    programmingStandards: standards({
      purpose: "Restore efficient running mechanics immediately after sled fatigue.",
      primaryAdaptation: "compromised_running",
      secondaryAdaptation: "sled_to_run_transition",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 55,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_2",
      recommendedProgression: "Sled — Race Execution",
      recommendedRegression: "Sled — Strength Endurance",
      suggestedSessionPlacement: ["compromised_key_day"],
      adjacencyWarnings: ["threshold_run", "race_simulation"],
      expectedRpe: "8",
      recommendedLoggingFields: ["Run splits", "First 200m notes", "RPE"],
    }),
    prescription: {
      objective:
        "Sled → run compromised running / RPE 8. Reclaim posture and cadence in the first 200m off the sled.",
      warmup: ["8 min easy run", "2×15m light sled"],
      mainSet: [
        "5 rounds:",
        "25m sled push @ race load / coach-prescribed",
        "Immediately 800m @ prescribed HYROX / controlled-hard pace",
        "2 min recovery",
        "Alternate rounds may use sled pull instead of push",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy jog 6 min"],
      targetRPE: "8",
      whatToRecord: ["800m splits", "First 200m feel", "RPE"],
      coachNote: "The run is the point. If you cannot run, you overcooked the sled.",
    },
  }),
  spec({
    id: "hxspec-wb-to-run",
    sessionLibraryId: "coach_hxspec_wb_to_run",
    name: "Wall Balls → Run — Compromised",
    category: "hyrox_compromised",
    subcategory: "wallball_to_run",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Wall balls into quality run",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4.5,
    qualityRunMinutes: 22,
    equipmentRequired: ["Wall ball", "Run route / treadmill"],
    bestFor: ["compromised_running", "wall_ball_weakness"],
    avoidIf: ["race_week"],
    tags: ["wall_ball", "running", "compromised-running", "stimulus-compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-wb-race-execution",
    recommendedRegression: "hxspec-wb-density",
    editableVariables: ["rounds", "wallBallReps", "runDistanceM"],
    programmingStandards: standards({
      purpose: "Rebuild run mechanics after wall-ball quad/shoulder fatigue.",
      primaryAdaptation: "compromised_running",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_2",
      recommendedProgression: "Wall Balls — Race Execution",
      recommendedRegression: "Wall Balls — Density",
      suggestedSessionPlacement: ["compromised_key_day"],
      adjacencyWarnings: ["threshold_run"],
      expectedRpe: "8",
      recommendedLoggingFields: ["Run splits", "WB breaks", "RPE"],
    }),
    prescription: {
      objective: "Wall balls → run / RPE 8. Find the run after the squat-throw fatigue.",
      warmup: ["8 min easy run", "2×10 wall balls"],
      mainSet: [
        "4–5 rounds:",
        "25–40 wall balls @ race weight / planned breaks",
        "800m–1km @ prescribed HYROX / controlled-hard pace",
        "90s–2 min recovery",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 5 min"],
      targetRPE: "8",
      whatToRecord: ["Run splits", "WB pattern", "RPE"],
      coachNote: "Do not empty the tank on wall balls if the run then dies.",
    },
  }),
  spec({
    id: "hxspec-lunge-to-run",
    sessionLibraryId: "coach_hxspec_lunge_to_run",
    name: "Lunges → Run — Compromised",
    category: "hyrox_compromised",
    subcategory: "lunge_to_run",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Lunges into quality run",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Sandbag", "Run route / treadmill"],
    bestFor: ["compromised_running", "lunge_weakness"],
    avoidIf: ["acute_knee_pain"],
    tags: ["lunges", "running", "compromised-running", "stimulus-compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-lunge-race-execution",
    recommendedRegression: "hxspec-lunge-strength-endurance",
    editableVariables: ["rounds", "lungeDistanceM", "runDistanceM"],
    programmingStandards: standards({
      purpose: "Restore stride after weighted-lunge stiffness.",
      primaryAdaptation: "compromised_running",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sandbag", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_2",
      recommendedProgression: "Lunges — Race Execution",
      recommendedRegression: "Lunges — Strength Endurance",
      suggestedSessionPlacement: ["compromised_key_day"],
      adjacencyWarnings: ["threshold_run"],
      expectedRpe: "8",
      recommendedLoggingFields: ["First 200m", "Run splits", "RPE"],
    }),
    prescription: {
      objective: "Lunges → run / RPE 8. Open the stride in the first 200m after the bag.",
      warmup: ["8 min easy run", "20m easy lunges"],
      mainSet: [
        "4–5 rounds:",
        "40m weighted lunges @ race load",
        "800m @ prescribed HYROX / controlled-hard pace",
        "90s–2 min recovery",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy jog 5 min"],
      targetRPE: "8",
      whatToRecord: ["First 200m notes", "800m splits", "RPE"],
      coachNote: "Cue cadence and hip extension off the last lunge.",
    },
  }),
  spec({
    id: "hxspec-bbj-to-run",
    sessionLibraryId: "coach_hxspec_bbj_to_run",
    name: "BBJ → Run — Compromised",
    category: "hyrox_compromised",
    subcategory: "bbj_to_run",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "BBJ into quality run",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Open floor", "Run route / treadmill"],
    bestFor: ["compromised_running", "bbj_weakness"],
    avoidIf: ["acute_calf_issue"],
    tags: ["bbj", "running", "compromised-running", "stimulus-compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-bbj-race-execution",
    recommendedRegression: "hxspec-bbj-repeatability",
    editableVariables: ["rounds", "bbjDistanceM", "runDistanceM"],
    programmingStandards: standards({
      purpose: "Reclaim running rhythm after BBJ posterior-chain fatigue.",
      primaryAdaptation: "compromised_running",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Open floor", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_2",
      recommendedProgression: "BBJ — Race Execution",
      recommendedRegression: "BBJ — Repeatability",
      suggestedSessionPlacement: ["compromised_key_day"],
      adjacencyWarnings: ["threshold_run"],
      expectedRpe: "8",
      recommendedLoggingFields: ["Run splits", "RPE"],
    }),
    prescription: {
      objective: "BBJ → run / RPE 8. Smooth the first running metres after jump fatigue.",
      warmup: ["8 min easy run", "10m easy BBJ"],
      mainSet: [
        "4–5 rounds:",
        "40m BBJ",
        "800m @ prescribed HYROX / controlled-hard pace",
        "90s–2 min recovery",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 5 min"],
      targetRPE: "8",
      whatToRecord: ["800m splits", "Stiffness notes", "RPE"],
      coachNote: "Do not hop into a sprint. Settle posture, then hit the prescribed pace.",
    },
  }),
  spec({
    id: "hxspec-run-to-sled",
    sessionLibraryId: "coach_hxspec_run_to_sled",
    name: "Run → Sled — Compromised",
    category: "hyrox_compromised",
    subcategory: "run_to_sled",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Quality run into sled",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Sled", "Run route / treadmill"],
    bestFor: ["compromised_running", "sled_weakness"],
    avoidIf: ["race_week"],
    tags: ["running", "sled", "sled_push", "sled_pull", "compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-sled-to-run",
    recommendedRegression: "hxspec-sled-easy-technique",
    editableVariables: ["rounds", "runDistanceM", "sledLoad"],
    programmingStandards: standards({
      purpose: "Practise sled execution after a quality run without full race simulation.",
      primaryAdaptation: "run_to_station_compromised",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_1",
      recommendedProgression: "Sled → Run — Compromised",
      recommendedRegression: "Sled — Easy Technique",
      suggestedSessionPlacement: ["compromised_day"],
      adjacencyWarnings: ["threshold_run"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Run splits", "Sled feel", "RPE"],
    }),
    prescription: {
      objective: "Run → sled / RPE 7–8. Keep run quality high with shorter intervals, then hit the sled with intent.",
      warmup: ["8 min easy run", "light sled feel"],
      mainSet: [
        "5 rounds:",
        "500–800m @ prescribed HYROX / controlled-hard pace",
        "Immediately 25m sled push or pull @ race load",
        "90s–2 min recovery",
        "Shorter run option (500m) if you need higher run quality",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy jog 5 min"],
      targetRPE: "7–8",
      whatToRecord: ["Run splits", "Sled load/feel", "RPE"],
      coachNote: "Not a full race sim. Protect run mechanics.",
    },
  }),
  spec({
    id: "hxspec-run-to-wb",
    sessionLibraryId: "coach_hxspec_run_to_wb",
    name: "Run → Wall Balls — Compromised",
    category: "hyrox_compromised",
    subcategory: "run_to_wallball",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Run into wall balls",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Wall ball", "Run route / treadmill"],
    bestFor: ["compromised_running", "wall_ball_weakness"],
    avoidIf: [],
    tags: ["running", "wall_ball", "compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-wb-to-run",
    recommendedRegression: "hxspec-wb-efficiency",
    editableVariables: ["rounds", "runDistanceM", "wallBallReps"],
    programmingStandards: standards({
      purpose: "Execute wall-ball strategy after a quality run.",
      primaryAdaptation: "run_to_station_compromised",
      trainingPhase: ["specific", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_1",
      recommendedProgression: "Wall Balls → Run — Compromised",
      recommendedRegression: "Wall Balls — Efficiency",
      suggestedSessionPlacement: ["compromised_day"],
      adjacencyWarnings: [],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Run splits", "WB breaks", "RPE"],
    }),
    prescription: {
      objective: "Run → wall balls / RPE 7–8. Arrive at the wall with a planned break strategy still intact.",
      warmup: ["8 min easy run", "10 easy wall balls"],
      mainSet: [
        "5 rounds:",
        "600–800m @ prescribed HYROX / controlled-hard pace",
        "20–30 wall balls @ race weight / planned breaks",
        "75–90s recovery",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 4 min"],
      targetRPE: "7–8",
      whatToRecord: ["Run splits", "First set unbroken?", "RPE"],
      coachNote: "Short runs on purpose — keep run quality.",
    },
  }),
  spec({
    id: "hxspec-run-to-mixed",
    sessionLibraryId: "coach_hxspec_run_to_mixed",
    name: "Run → Mixed Stations — Compromised",
    category: "hyrox_compromised",
    subcategory: "run_to_mixed",
    level: "advanced",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Run into rotating stations",
    intensityType: "compromised",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Run route", "Sled or wall ball or sandbag or row"],
    bestFor: ["compromised_running", "mixed_hyrox"],
    avoidIf: ["beginner_as_written", "race_week"],
    tags: ["running", "mixed-hyrox", "compromised-running", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-engine-cluster",
    recommendedRegression: "hxspec-run-to-wb",
    editableVariables: ["rounds", "runDistanceM", "station"],
    programmingStandards: standards({
      purpose: "Short quality runs into varied station exposure — not a full race.",
      primaryAdaptation: "run_to_station_compromised",
      trainingPhase: ["specific"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Run surface", "Stations"],
      progressionFamily: "compromised_running",
      progressionLevel: "level_2",
      recommendedProgression: "Engine Cluster — Controlled",
      recommendedRegression: "Run → Wall Balls — Compromised",
      suggestedSessionPlacement: ["compromised_day"],
      adjacencyWarnings: ["race_simulation"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Run splits", "Stations used", "RPE"],
    }),
    prescription: {
      objective: "Run → mixed stations / RPE 7–8. Rotate stations so this does not become a race sim.",
      warmup: ["8 min easy run"],
      mainSet: [
        "6 rounds:",
        "500–800m @ prescribed HYROX / controlled-hard pace",
        "Then ONE station, rotating: 20m sled / 15 BBJ / 250m row / 20m farmers / 20m lunges / 20 wall balls",
        "75–90s recovery",
        "Do not complete a full HYROX sequence in one session",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 5 min"],
      targetRPE: "7–8",
      whatToRecord: ["Run splits", "Hardest station off the run", "RPE"],
      coachNote: "Variety over completeness. Keep run quality.",
    },
  }),
  spec({
    id: "hxspec-front-half-cluster",
    sessionLibraryId: "coach_hxspec_front_half_cluster",
    name: "Front Half — Technique Cluster",
    category: "hyrox_volume_builders",
    subcategory: "cluster · front_half",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 180,
    equipmentRequired: ["SkiErg", "Sled", "Open floor"],
    bestFor: ["front_half_skill"],
    avoidIf: [],
    tags: ["mixed-hyrox", "ski", "sled_push", "sled_pull", "bbj", "running", "technique", "moderate"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-engine-cluster",
    recommendedRegression: "hxspec-hyrox-technique-flow-front",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Front-half cluster at moderate intensity for transitions without race redline.",
      primaryAdaptation: "front_half_cluster",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["SkiErg", "Sled"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Engine Cluster — Controlled",
      recommendedRegression: "HYROX Technique Flow — Front Half",
      suggestedSessionPlacement: ["hyrox_specific_day"],
      adjacencyWarnings: ["race_simulation"],
      expectedRpe: "6",
      recommendedLoggingFields: ["Rounds", "RPE"],
    }),
    prescription: {
      objective: "Front-half cluster / RPE 6. Ski, sleds, BBJ, short run — moderate, repeatable.",
      warmup: ["5 min easy ski"],
      mainSet: [
        "4 rounds:",
        "400m Ski @ target Ski pace",
        "20m sled push + 20m sled pull @ race load or slightly under",
        "10 BBJ",
        "400m run @ easy-moderate / mechanical reset",
        "90s recovery",
      ],
      cooldown: ["Easy walk 4 min"],
      targetRPE: "6",
      whatToRecord: ["Rounds", "RPE"],
      coachNote: "Moderate cluster. Save true race output for execution sessions.",
    },
  }),
  spec({
    id: "hxspec-back-half-cluster",
    sessionLibraryId: "coach_hxspec_back_half_cluster",
    name: "Back Half — Strength Endurance Cluster",
    category: "hyrox_volume_builders",
    subcategory: "cluster · back_half",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Back-half station cluster",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    stationVolume: 220,
    equipmentRequired: ["RowErg", "Farmers handles", "Sandbag", "Wall ball"],
    bestFor: ["back_half_weakness"],
    avoidIf: ["race_week"],
    tags: ["mixed-hyrox", "row", "farmers", "lunges", "wall_ball", "strength-endurance", "hard"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-leg-se-cluster",
    recommendedRegression: "hxspec-hyrox-technique-flow-back",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Back-half strength-endurance cluster without a full race.",
      primaryAdaptation: "back_half_strength_endurance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["RowErg", "Farmers", "Sandbag", "Wall ball"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Leg Strength-Endurance Cluster",
      recommendedRegression: "HYROX Technique Flow — Back Half",
      suggestedSessionPlacement: ["hyrox_specific_day"],
      adjacencyWarnings: ["race_simulation", "heavy_leg_strength"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Rounds", "RPE"],
    }),
    prescription: {
      objective: "Back-half strength endurance cluster / RPE 7. Row, farmers, lunges, wall balls, short run.",
      warmup: ["5 min easy row"],
      mainSet: [
        "4 rounds:",
        "400m Row @ target Row pace",
        "30m farmers @ race load",
        "30m lunges @ race load",
        "20 wall balls",
        "300m easy-moderate run",
        "2 min recovery",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy walk 5 min"],
      targetRPE: "7",
      whatToRecord: ["Rounds completed", "Where quality dropped", "RPE"],
      coachNote: "Cluster, not a race. Recover enough to repeat.",
    },
  }),
  spec({
    id: "hxspec-leg-se-cluster",
    sessionLibraryId: "coach_hxspec_leg_se_cluster",
    name: "Leg Strength-Endurance Cluster",
    category: "hyrox_volume_builders",
    subcategory: "cluster · legs",
    level: "advanced",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Sled + lunge + wall-ball cluster",
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "very_high",
    stationVolume: 240,
    equipmentRequired: ["Sled", "Sandbag", "Wall ball"],
    bestFor: ["leg_endurance"],
    avoidIf: ["beginner_as_written", "race_week", "high_doms_state"],
    tags: ["sled_push", "sled_pull", "lunges", "wall_ball", "strength-endurance", "leg_endurance", "hard"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "advanced",
    recommendedProgression: "hxspec-back-half-cluster",
    recommendedRegression: "hxspec-sled-strength-endurance",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Leg strength-endurance via sleds, lunges and wall balls — high cost, not a race.",
      primaryAdaptation: "leg_strength_endurance",
      trainingPhase: ["specific"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "very_high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Sandbag", "Wall ball"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "advanced",
      recommendedProgression: "Back Half — Strength Endurance Cluster",
      recommendedRegression: "Sled — Strength Endurance",
      suggestedSessionPlacement: ["isolated_hard_station_day"],
      adjacencyWarnings: ["threshold_run", "compromised_running", "race_simulation"],
      expectedRpe: "8",
      recommendedLoggingFields: ["Rounds", "RPE", "Next-day legs"],
    }),
    prescription: {
      objective: "Leg strength-endurance cluster / RPE 8. Sled, lunges, wall balls — isolate this hard day.",
      warmup: ["6 min easy bike", "light sled + 10 wall balls"],
      mainSet: [
        "4 rounds:",
        "25m sled push + 25m sled pull @ race load / overload",
        "30m lunges @ race load",
        "20 wall balls",
        "2–3 min recovery",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 6 min"],
      targetRPE: "8",
      whatToRecord: ["Rounds", "Load", "RPE"],
      coachNote: "Do not place beside threshold or compromised running.",
    },
  }),
  spec({
    id: "hxspec-engine-cluster",
    sessionLibraryId: "coach_hxspec_engine_cluster",
    name: "Engine Cluster — Controlled",
    category: "hybrid_engine",
    subcategory: "cluster · engine",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Ski/row/BBJ/run cluster",
    intensityType: "hybrid_engine",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    qualityRunMinutes: 16,
    ergMinutes: 16,
    equipmentRequired: ["SkiErg", "RowErg", "Open floor", "Run route"],
    bestFor: ["engine", "mixed_hyrox"],
    avoidIf: ["race_week"],
    tags: ["ski", "row", "bbj", "running", "mixed-hyrox", "moderate", "hard"],
    progressionFamily: "mixed_erg_engine",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-hyrox-station-emom",
    recommendedRegression: "hxspec-front-half-cluster",
    editableVariables: ["rounds"],
    programmingStandards: standards({
      purpose: "Controlled engine cluster: ski, row, BBJ, running — repeatable, not maximal.",
      primaryAdaptation: "hybrid_engine_cluster",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["SkiErg", "RowErg", "Run surface"],
      progressionFamily: "mixed_erg_engine",
      progressionLevel: "level_2",
      recommendedProgression: "HYROX Station EMOM",
      recommendedRegression: "Front Half — Technique Cluster",
      suggestedSessionPlacement: ["engine_day"],
      adjacencyWarnings: ["race_simulation"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Erg splits", "RPE"],
    }),
    prescription: {
      objective: "Engine cluster / RPE 7. Ski, BBJ, row, run — controlled output you can repeat.",
      warmup: ["4 min easy ski"],
      mainSet: [
        "4 rounds:",
        "400m Ski @ target Ski pace",
        "10 BBJ",
        "400m Row @ target Row pace",
        "400m run @ prescribed HYROX / slightly easier than race",
        "90s recovery",
        GENERIC_PACE,
      ],
      cooldown: ["Easy walk 4 min"],
      targetRPE: "7",
      whatToRecord: ["Ski/row splits", "RPE"],
      coachNote: "If splits fade >3s, extend recovery rather than forcing.",
    },
  }),
  spec({
    id: "hxspec-sled-race-execution",
    sessionLibraryId: "coach_hxspec_sled_race_execution",
    name: "Sled — Race Execution",
    category: "hyrox_compromised",
    subcategory: "sled · race_execution",
    level: "advanced",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Race-pace sled + run with full recovery",
    intensityType: "race_execution",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 4,
    qualityRunMinutes: 20,
    equipmentRequired: ["Sled", "Run route / treadmill"],
    bestFor: ["race_specific", "sled_pacing"],
    avoidIf: ["beginner_as_written", "deload_week"],
    tags: ["sled", "running", "race-execution", "race-specific", "stimulus-race-execution", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "advanced",
    recommendedProgression: "hxspec-wb-race-execution",
    recommendedRegression: "hxspec-sled-to-run",
    editableVariables: ["rounds", "runDistanceM", "sledLoad"],
    programmingStandards: standards({
      purpose: "Practise exact race sled + run output with enough recovery to reproduce accurately.",
      primaryAdaptation: "race_execution",
      trainingPhase: ["specific", "peak"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "high",
      equipmentRequired: ["Sled", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "advanced",
      recommendedProgression: "Wall Balls — Race Execution",
      recommendedRegression: "Sled → Run — Compromised",
      suggestedSessionPlacement: ["race_specific_day"],
      adjacencyWarnings: ["race_simulation", "very_high_fatigue_station_day"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Run splits vs target", "Sled time/feel", "RPE"],
    }),
    prescription: {
      objective:
        "Sled race execution / RPE 7–8. Exact race output, pacing and transitions — recover enough to repeat accurately.",
      warmup: ["10 min easy run + strides", "2× light race-sled feel"],
      mainSet: [
        "3–4 rounds:",
        "1km @ prescribed HYROX race pace",
        "25m sled push + 25m sled pull @ race prescription",
        "Generous recovery (2.5–3.5 min) so each round can match the first",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy jog 8 min"],
      targetRPE: "7–8",
      whatToRecord: ["1km splits vs target", "Sled execution notes", "RPE"],
      coachNote: "Not a maximal workout. If round 3 is slower than round 1, you started too hot or recovered too little.",
    },
  }),
  spec({
    id: "hxspec-wb-race-execution",
    sessionLibraryId: "coach_hxspec_wb_race_execution",
    name: "Wall Balls — Race Execution",
    category: "hyrox_compromised",
    subcategory: "wall_ball · race_execution",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Race-pace run + wall-ball strategy",
    intensityType: "race_execution",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 3.2,
    qualityRunMinutes: 16,
    equipmentRequired: ["Wall ball", "Run route / treadmill"],
    bestFor: ["race_specific", "wall_ball_pacing"],
    avoidIf: ["beginner_as_written"],
    tags: ["wall_ball", "running", "race-execution", "race-specific", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "advanced",
    recommendedProgression: "hxspec-lunge-race-execution",
    recommendedRegression: "hxspec-wb-to-run",
    editableVariables: ["rounds", "wallBallReps", "runDistanceM"],
    programmingStandards: standards({
      purpose: "Rehearse race wall-ball break strategy off race-pace running, with enough recovery to copy the plan.",
      primaryAdaptation: "race_execution",
      trainingPhase: ["specific", "peak"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "high",
      equipmentRequired: ["Wall ball", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "advanced",
      recommendedProgression: "Lunges — Race Execution",
      recommendedRegression: "Wall Balls → Run — Compromised",
      suggestedSessionPlacement: ["race_specific_day"],
      adjacencyWarnings: ["high_wall_ball_volume"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Break strategy", "Run splits", "RPE"],
    }),
    prescription: {
      objective: "Wall ball race execution / RPE 7–8. Practise the planned race break strategy off race-pace running.",
      warmup: ["8 min easy run", "2×8 wall balls at race rhythm"],
      mainSet: [
        "3–4 rounds:",
        "800m @ prescribed race pace",
        "25–40 wall balls using planned race break strategy (write it down first)",
        "Adequate recovery (2–3 min) to reproduce the same pattern",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 6 min"],
      targetRPE: "7–8",
      whatToRecord: ["Break plan vs actual", "800m splits", "RPE"],
      coachNote: "The win is identical rounds, not a heroic last set.",
    },
  }),
  spec({
    id: "hxspec-lunge-race-execution",
    sessionLibraryId: "coach_hxspec_lunge_race_execution",
    name: "Lunges — Race Execution",
    category: "hyrox_compromised",
    subcategory: "lunge · race_execution",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Race-load lunges off race-pace run",
    intensityType: "race_execution",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 3,
    qualityRunMinutes: 15,
    equipmentRequired: ["Sandbag", "Run route / treadmill"],
    bestFor: ["race_specific", "lunge_pacing"],
    avoidIf: ["acute_knee_pain"],
    tags: ["lunges", "running", "race-execution", "race-specific", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "advanced",
    recommendedProgression: "hxspec-bbj-race-execution",
    recommendedRegression: "hxspec-lunge-to-run",
    editableVariables: ["rounds", "runDistanceM", "lungeDistanceM"],
    programmingStandards: standards({
      purpose: "Practise race-load lunges and the first running metres after the bag.",
      primaryAdaptation: "race_execution",
      trainingPhase: ["specific", "peak"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "high",
      equipmentRequired: ["Sandbag", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "advanced",
      recommendedProgression: "BBJ — Race Execution",
      recommendedRegression: "Lunges → Run — Compromised",
      suggestedSessionPlacement: ["race_specific_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Transition notes", "Run splits", "RPE"],
    }),
    prescription: {
      objective: "Lunge race execution / RPE 7–8. Race-load lunges, then practise the first running metres.",
      warmup: ["8 min easy run", "20m race-bag feel"],
      mainSet: [
        "3–4 rounds:",
        "600–800m @ prescribed race pace",
        "40m lunges @ race load",
        "Immediately 150–200m @ race posture/cadence (not a sprint)",
        "Then 2–3 min recovery",
        GENERIC_PACE,
        GENERIC_LOAD,
      ],
      cooldown: ["Easy jog 6 min"],
      targetRPE: "7–8",
      whatToRecord: ["Transition quality", "Run splits", "RPE"],
      coachNote: "The 150m after the bag is the teaching moment.",
    },
  }),
  spec({
    id: "hxspec-bbj-race-execution",
    sessionLibraryId: "coach_hxspec_bbj_race_execution",
    name: "BBJ — Race Execution",
    category: "hyrox_compromised",
    subcategory: "bbj · race_execution",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Race-specific BBJ off race-pace run",
    intensityType: "race_execution",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    runDistanceKm: 3,
    qualityRunMinutes: 15,
    equipmentRequired: ["Open floor", "Run route / treadmill"],
    bestFor: ["race_specific", "bbj_pacing"],
    avoidIf: ["acute_calf_issue"],
    tags: ["bbj", "running", "race-execution", "race-specific", "hard"],
    progressionFamily: "compromised_running",
    progressionLevel: "advanced",
    recommendedProgression: "hxspec-sled-race-execution",
    recommendedRegression: "hxspec-bbj-to-run",
    editableVariables: ["rounds", "bbjDistanceM", "runDistanceM"],
    programmingStandards: standards({
      purpose: "Rehearse sustainable race BBJ rhythm off prescribed race-pace running.",
      primaryAdaptation: "race_execution",
      trainingPhase: ["specific", "peak"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "high",
      equipmentRequired: ["Open floor", "Run surface"],
      progressionFamily: "compromised_running",
      progressionLevel: "advanced",
      recommendedProgression: "Sled — Race Execution",
      recommendedRegression: "BBJ → Run — Compromised",
      suggestedSessionPlacement: ["race_specific_day"],
      adjacencyWarnings: [],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Rhythm notes", "Run splits", "RPE"],
    }),
    prescription: {
      objective: "BBJ race execution / RPE 7–8. Race-specific BBJ volume with sustainable rhythm, not a sprint.",
      warmup: ["8 min easy run", "10m easy BBJ"],
      mainSet: [
        "3–4 rounds:",
        "600–800m @ prescribed race pace",
        "30–40m BBJ at planned race rhythm (same jump length, same breath)",
        "2–3 min recovery to reproduce the pattern",
        GENERIC_PACE,
      ],
      cooldown: ["Easy jog 6 min"],
      targetRPE: "7–8",
      whatToRecord: ["Rhythm consistency", "Run splits", "RPE"],
      coachNote: "Sustainable station rhythm is the skill.",
    },
  }),
  spec({
    id: "hxspec-hyrox-station-emom",
    sessionLibraryId: "coach_hxspec_hyrox_station_emom",
    name: "HYROX Station EMOM",
    category: "station_emom",
    subcategory: "emom · mixed_stations",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_density",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 160,
    equipmentRequired: ["Wall ball", "Sandbag", "Open floor", "SkiErg or RowErg"],
    bestFor: ["density", "mixed_hyrox"],
    avoidIf: [],
    tags: ["emom", "density", "mixed-hyrox", "wall_ball", "lunges", "bbj", "moderate"],
    progressionFamily: "station_emom_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-wb-erg-density",
    recommendedRegression: "hxspec-wb-efficiency-emom",
    editableVariables: ["emomMinutes", "stationReps"],
    programmingStandards: standards({
      purpose: "Rotating station density with a recovery minute so quality stays high.",
      primaryAdaptation: "station_density",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Sandbag", "Erg"],
      progressionFamily: "station_emom_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Wall Ball + Erg Density",
      recommendedRegression: "Wall Balls — Efficiency EMOM",
      suggestedSessionPlacement: ["density_day"],
      adjacencyWarnings: [],
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Minutes completed", "Where rest vanished", "RPE"],
    }),
    prescription: {
      objective: "HYROX station EMOM / RPE 6–7. Rotating density with a recovery minute — stay repeatable.",
      warmup: ["5 min easy mixed erg", "10 wall balls + 10m lunges"],
      mainSet: [
        "16 min EMOM (4 cycles):",
        "Min 1: 12–15 wall balls",
        "Min 2: 12–16 walking lunge steps @ moderate/race-under load",
        "Min 3: 6–8 BBJ or 8/6 cal Ski or 10/8 cal Row",
        "Min 4: recovery / easy breathe-down",
        "If leftover rest on work minutes is <10s, cut volume next cycle",
      ],
      cooldown: ["Easy bike 5 min"],
      targetRPE: "6–7",
      whatToRecord: ["Cycles completed", "Which minute got tight", "RPE"],
      coachNote: "Recovery minute is programmed on purpose.",
    },
  }),
  spec({
    id: "hxspec-sled-density",
    sessionLibraryId: "coach_hxspec_sled_density",
    name: "Sled — Density",
    category: "hyrox_volume_builders",
    subcategory: "sled · density",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Timed sled repeats",
    intensityType: "station_density",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 200,
    equipmentRequired: ["Sled", "Open floor"],
    bestFor: ["sled_density"],
    avoidIf: ["high_doms_state"],
    tags: ["sled", "sled_push", "sled_pull", "density", "hard"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_2",
    recommendedProgression: "hxspec-sled-strength-endurance",
    recommendedRegression: "hxspec-sled-technique-volume",
    editableVariables: ["workSeconds", "rounds"],
    programmingStandards: standards({
      purpose: "Timed sled repeat exposure at sub-race-to-race load without turning it into a max test.",
      primaryAdaptation: "sled_density",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Sled — Strength Endurance",
      recommendedRegression: "Sled — Technique + Volume",
      suggestedSessionPlacement: ["station_day"],
      adjacencyWarnings: ["heavy_leg_strength"],
      expectedRpe: "7",
      recommendedLoggingFields: ["Bouts", "Load", "RPE"],
    }),
    prescription: {
      objective: "Sled density / RPE 7. Short repeat exposure on the clock — technique still required.",
      warmup: ["5 min easy bike", "2×15m light sled"],
      mainSet: [
        "10 min: every 90s complete 15–20m sled push OR pull (alternate), remaining time rest",
        "Then 3 min walk",
        "Then 8 min: every 75–90s the opposite sled action",
        GENERIC_LOAD,
      ],
      cooldown: ["Easy bike 5 min"],
      targetRPE: "7",
      whatToRecord: ["Bouts hit", "Load", "RPE"],
      coachNote: "If you miss the interval, drop load, not rest.",
    },
  }),
  spec({
    id: "hxspec-wb-erg-density",
    sessionLibraryId: "coach_hxspec_wb_erg_density",
    name: "Wall Ball + Erg Density",
    category: "station_emom",
    subcategory: "density · wallball_erg",
    level: "intermediate",
    durationMinutes: 35,
    hardDay: true,
    hardDayReason: "Alternating wall-ball/erg minutes",
    intensityType: "station_density",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 140,
    ergMinutes: 12,
    equipmentRequired: ["Wall ball", "SkiErg or RowErg"],
    bestFor: ["density", "wall_ball_weakness"],
    avoidIf: [],
    tags: ["wall_ball", "ski", "row", "density", "emom", "hard"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_1",
    recommendedProgression: "hxspec-hyrox-station-emom",
    recommendedRegression: "hxspec-wb-efficiency-emom",
    editableVariables: ["emomMinutes", "wallBallReps", "ergCals"],
    programmingStandards: standards({
      purpose: "Alternate wall-ball and erg minutes to build density without a full mixed simulation.",
      primaryAdaptation: "mixed_density",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Ski or Row"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_1",
      recommendedProgression: "HYROX Station EMOM",
      recommendedRegression: "Wall Balls — Efficiency EMOM",
      suggestedSessionPlacement: ["density_day"],
      adjacencyWarnings: [],
      expectedRpe: "7",
      recommendedLoggingFields: ["Minutes", "WB reps", "Erg output", "RPE"],
    }),
    prescription: {
      objective: "Wall ball + erg density / RPE 7. Alternating minutes — sustainable, not a sprint.",
      warmup: ["4 min easy ski/row", "10 wall balls"],
      mainSet: [
        "12–14 min EMOM alternating:",
        "Odd: 10–15 wall balls (leave ≥12s rest)",
        "Even: 8/6–12/9 cal Ski or 10/8–14/11 cal Row @ controlled hard",
        "If rest disappears, cut the next work minute",
      ],
      cooldown: ["Easy erg 4 min"],
      targetRPE: "7",
      whatToRecord: ["Minutes completed", "Where rest vanished", "RPE"],
      coachNote: "Density with a ceiling. Not a race.",
    },
  }),
];
