/**
 * Coach programme-builder session library — 75 curated Hybrid365 sessions.
 * @see docs/hybrid365-hyrox-methodology.md
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";

export const COACH_SESSION_LIBRARY_DATA: CoachLibraryEntry[] = [
  buildCoachEntry({
    id: "th-5x5",
    sessionLibraryId: "hyrox_run_threshold_6x6",
    name: "Threshold Run \u2014 5 x 5 Minutes",
    category: "threshold_runs",
    subcategory: "threshold_intervals",
    level: "intermediate",
    durationMinutes: 60,
    thresholdMinutes: 25,
    runDistanceKm: 9,
    hardDay: true,
    hardDayReason: "Threshold run intervals",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track / treadmill"],
    bestFor: ["block_1", "threshold_intro"],
    avoidIf: ["consecutive_hard_days", "calf_pain"],
    tags: ["threshold", "run"],
    preferredDay: "Tue",
    similarSessions: ["th-6x5", "th-6x6", "th-3x10", "cruise-1k"],
    progressionOptions: ["5\u00d75 \u2192 6\u00d75 \u2192 6\u00d76"],
    regressionOptions: ["4\u00d74 min @ threshold"],
    editableVariables: ["reps", "repDurationMinutes", "recoverySeconds", "targetPace", "targetRPE", "coachNote"],
    prescription: {"objective": "Controlled threshold — finish with one rep spare.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["5×5 min @ threshold", "90s easy jog between"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Rep paces", "RPE", "HR if used"], "coachNote": "Key progression: 5×5 → 6×5 → 6×6.", "progression": "Progress reps before pace."},
  }),
  buildCoachEntry({
    id: "th-6x5",
    sessionLibraryId: "coach_th-6x5",
    name: "Threshold Run \u2014 6 x 5 Minutes",
    category: "threshold_runs",
    subcategory: "threshold_intervals",
    level: "intermediate",
    durationMinutes: 65,
    thresholdMinutes: 30,
    runDistanceKm: 10,
    hardDay: true,
    hardDayReason: "Threshold run intervals",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track / treadmill"],
    bestFor: ["week_2_progression"],
    avoidIf: ["poor_recovery"],
    tags: ["threshold"],
    preferredDay: "Tue",
    similarSessions: ["th-5x5", "th-6x6"],
    editableVariables: ["reps", "recoverySeconds", "targetPace"],
    prescription: {"objective": "Week-2 threshold progression.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["6×5 min @ threshold", "75–90s easy recovery"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Rep paces", "RPE", "HR if used"], "coachNote": "Reduce recovery before increasing pace."},
  }),
  buildCoachEntry({
    id: "th-6x6",
    sessionLibraryId: "hyrox_run_threshold_6x6",
    name: "Threshold Run \u2014 6 x 6 Minutes",
    category: "threshold_runs",
    subcategory: "threshold_intervals",
    level: "advanced",
    durationMinutes: 70,
    thresholdMinutes: 36,
    runDistanceKm: 11,
    hardDay: true,
    hardDayReason: "Threshold run intervals",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track / treadmill"],
    bestFor: ["staple_threshold"],
    avoidIf: ["beginner"],
    tags: ["threshold", "staple"],
    isStaple: true,
    preferredDay: "Tue",
    similarSessions: ["th-5x5", "th-6x5"],
    editableVariables: ["reps", "recoverySeconds", "targetPace"],
    prescription: {"objective": "Staple threshold — even splits all reps.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["6×6 min @ threshold", "60–75s easy between"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Rep paces", "RPE", "HR if used"], "coachNote": "Intermediate/advanced staple."},
  }),
  buildCoachEntry({
    id: "th-3x10",
    sessionLibraryId: "hyrox_run_threshold_3x10",
    name: "Threshold Run \u2014 3 x 10 Minutes",
    category: "threshold_runs",
    subcategory: "threshold_blocks",
    level: "intermediate",
    durationMinutes: 70,
    thresholdMinutes: 30,
    runDistanceKm: 10,
    hardDay: true,
    hardDayReason: "Long threshold blocks",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["block_2"],
    avoidIf: ["heavy_legs_day_before"],
    tags: ["threshold"],
    similarSessions: ["th-2x15", "continuous-th"],
    editableVariables: ["reps", "recoverySeconds", "targetPace"],
    prescription: {"objective": "Longer threshold blocks for durability.", "warmup": ["12 min easy", "Strides"], "mainSet": ["3×10 min @ threshold", "90–120s easy between"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Split times", "RPE"], "coachNote": "Stay controlled early."},
  }),
  buildCoachEntry({
    id: "th-2x15",
    sessionLibraryId: "coach_th-2x15",
    name: "Threshold Run \u2014 2 x 15 Minutes",
    category: "threshold_runs",
    subcategory: "threshold_blocks",
    level: "advanced",
    durationMinutes: 75,
    thresholdMinutes: 30,
    runDistanceKm: 11,
    hardDay: true,
    hardDayReason: "Sustained threshold",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "high",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["advanced"],
    avoidIf: ["beginner", "high_threshold_week"],
    tags: ["threshold", "advanced"],
    editableVariables: ["recoverySeconds", "targetPace"],
    prescription: {"objective": "Advanced sustained threshold.", "warmup": ["12 min easy"], "mainSet": ["2×15 min @ threshold", "90–120s easy"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Block paces", "RPE"], "coachNote": "Do not start rep 1 too fast."},
  }),
  buildCoachEntry({
    id: "cruise-1k",
    sessionLibraryId: "coach_cruise-1k",
    name: "Cruise Intervals \u2014 5\u20138 x 1km",
    category: "threshold_runs",
    subcategory: "distance_threshold",
    level: "intermediate",
    durationMinutes: 65,
    thresholdMinutes: 28,
    runDistanceKm: 10,
    hardDay: true,
    hardDayReason: "Distance threshold",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Measured 1km loop"],
    bestFor: ["distance_based_athletes"],
    avoidIf: [],
    tags: ["threshold", "cruise"],
    similarSessions: ["th-5x5", "mile-repeats"],
    editableVariables: ["reps", "targetPace"],
    prescription: {"objective": "Distance-based threshold reps.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["5–8×1km @ threshold/10km effort", "60–90s easy"], "cooldown": ["8 min easy"], "targetPace": "Threshold / 10km", "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Km splits", "RPE"], "coachNote": "TH minutes estimated from pace."},
  }),
  buildCoachEntry({
    id: "mile-repeats",
    sessionLibraryId: "coach_mile-repeats",
    name: "Mile Repeats \u2014 3\u20135 x 1 Mile",
    category: "threshold_runs",
    subcategory: "distance_threshold",
    level: "advanced",
    durationMinutes: 70,
    thresholdMinutes: 27,
    runDistanceKm: 12,
    hardDay: true,
    hardDayReason: "Mile threshold",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["strong_runners"],
    avoidIf: ["beginner"],
    tags: ["threshold", "mile"],
    editableVariables: ["reps", "targetPace"],
    prescription: {"objective": "Longer threshold mile reps.", "warmup": ["12 min easy"], "mainSet": ["3–5×1 mile @ threshold", "1–2 min easy"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Mile splits"], "coachNote": "Calculated TH from pace."},
  }),
  buildCoachEntry({
    id: "continuous-th",
    sessionLibraryId: "coach_continuous-th",
    name: "Continuous Threshold \u2014 20\u201330 Minutes",
    category: "threshold_runs",
    subcategory: "continuous_threshold",
    level: "advanced",
    durationMinutes: 60,
    thresholdMinutes: 25,
    runDistanceKm: 9,
    hardDay: true,
    hardDayReason: "Continuous threshold",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Running surface"],
    bestFor: ["advanced"],
    avoidIf: ["races_threshold", "hr_drift"],
    tags: ["threshold", "continuous"],
    editableVariables: ["repDurationMinutes", "targetPace"],
    prescription: {"objective": "Continuous threshold block.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["20–30 min continuous @ threshold"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Avg pace", "HR", "RPE"], "coachNote": "Avoid if athlete races threshold.", "safetyNote": "Stop if pace drops >5%."},
  }),
  buildCoachEntry({
    id: "threshold-hills",
    sessionLibraryId: "coach_threshold-hills",
    name: "Threshold Hills \u2014 10 x 2 Minutes",
    category: "threshold_runs",
    subcategory: "hill_threshold",
    level: "intermediate",
    durationMinutes: 55,
    thresholdMinutes: 20,
    runDistanceKm: 7,
    hardDay: true,
    hardDayReason: "Hill threshold",
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Hill 2\u20134%"],
    bestFor: ["lower_mileage"],
    avoidIf: ["calf_flare"],
    tags: ["threshold", "hills"],
    editableVariables: ["reps", "recoverySeconds"],
    prescription: {"objective": "Effort-based hill threshold.", "warmup": ["10 min easy", "Hill strides"], "mainSet": ["10×2 min uphill @ TH effort", "Jog down recovery"], "cooldown": ["8 min easy flat"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8 effort", "whatToRecord": ["Effort", "RPE"], "coachNote": "Not pace-based."},
  }),
  buildCoachEntry({
    id: "double-th-intro",
    sessionLibraryId: "coach_double-th-intro",
    name: "Double Threshold Intro \u2014 Run + Erg",
    category: "threshold_runs",
    subcategory: "double_threshold",
    level: "advanced",
    durationMinutes: 90,
    thresholdMinutes: 26,
    qualityRunMinutes: 15,
    runDistanceKm: 6,
    ergMinutes: 10,
    hardDay: true,
    hardDayReason: "Double threshold",
    intensityType: "threshold",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "none",
    equipmentRequired: ["Track", "SkiErg or RowErg"],
    bestFor: ["double_ready"],
    avoidIf: ["beginner", "not_ready_single_th"],
    tags: ["double", "threshold"],
    editableVariables: ["reps", "ergModality", "recoverySeconds"],
    prescription: {"objective": "Double threshold — advanced only.", "warmup": ["10 min easy run", "5 min easy erg"], "mainSet": ["AM: 5–6×3 min TH run · 60s rest", "PM: 8–12×1 min Ski/Row TH · 30s rest"], "cooldown": ["5 min easy each"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Run paces", "Erg splits", "RPE AM/PM"], "coachNote": "Only after single TH established.", "safetyNote": "Skip PM if AM RPE >8."},
  }),
  buildCoachEntry({
    id: "hm-tempo-3x10",
    sessionLibraryId: "hyrox_run_tempo_hm",
    name: "HM Pace Tempo \u2014 3 x 10 Minutes",
    category: "tempo_aerobic",
    subcategory: "hm_tempo",
    level: "intermediate",
    durationMinutes: 55,
    qualityRunMinutes: 30,
    runDistanceKm: 9,
    hardDay: true,
    hardDayReason: "Tempo / aerobic quality",
    intensityType: "tempo",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["aerobic_quality", "double_ready_thursday_am"],
    avoidIf: ["already_high_threshold_week"],
    tags: ["tempo", "hm"],
    editableVariables: ["reps", "recoverySeconds", "targetPace", "targetRPE"],
    prescription: {"objective": "HM tempo — below threshold unless HR drifts.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["3×10 min @ HM pace / upper steady", "2 min easy between"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Rep pace", "HR", "RPE"], "coachNote": "Optional secondary quality — not replacement for Tue TH."},
  }),
  buildCoachEntry({
    id: "alternating-tempo",
    sessionLibraryId: "coach_alternating-tempo",
    name: "Alternating Tempo \u2014 5 x 6 Minutes",
    category: "tempo_aerobic",
    subcategory: "alternating_tempo",
    level: "intermediate",
    durationMinutes: 55,
    qualityRunMinutes: 30,
    runDistanceKm: 8,
    hardDay: true,
    hardDayReason: "Tempo quality",
    intensityType: "tempo",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["overcook_tempo"],
    avoidIf: [],
    tags: ["tempo"],
    editableVariables: ["reps", "targetRPE"],
    prescription: {"objective": "Alternating steady/tempo blocks.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["5×6 min: 3 min steady / 3 min tempo"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Block RPE", "Pace"], "coachNote": "Best for athletes who overcook tempo."},
  }),
  buildCoachEntry({
    id: "progressive-tempo",
    sessionLibraryId: "coach_progressive-tempo",
    name: "Progressive Tempo Run",
    category: "tempo_aerobic",
    subcategory: "progression_tempo",
    level: "all",
    durationMinutes: 50,
    qualityRunMinutes: 25,
    runDistanceKm: 8,
    hardDay: true,
    hardDayReason: "Progressive tempo",
    intensityType: "tempo",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Running surface"],
    bestFor: ["aerobic_quality"],
    avoidIf: ["poor_recovery"],
    tags: ["tempo", "progression"],
    editableVariables: ["repDurationMinutes", "targetRPE"],
    prescription: {"objective": "Progression easy → steady → tempo.", "warmup": ["10 min easy"], "mainSet": ["30–45 min progression run"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7 building", "whatToRecord": ["Avg pace", "RPE", "HR"], "coachNote": "Aerobic quality without sharp intervals."},
  }),
  buildCoachEntry({
    id: "tempo-strides",
    sessionLibraryId: "coach_tempo-strides",
    name: "Tempo + Strides",
    category: "tempo_aerobic",
    subcategory: "tempo_strides",
    level: "intermediate",
    durationMinutes: 50,
    qualityRunMinutes: 25,
    runDistanceKm: 7,
    hardDay: true,
    hardDayReason: "Tempo + strides",
    intensityType: "tempo",
    impactType: "run",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["running_economy"],
    avoidIf: [],
    tags: ["tempo", "strides"],
    editableVariables: ["repDurationMinutes", "targetRPE"],
    prescription: {"objective": "Controlled tempo plus strides.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["20–30 min controlled tempo", "4–6×20s strides"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Tempo pace", "Stride quality"], "coachNote": "Economy and controlled quality."},
  }),
  buildCoachEntry({
    id: "5k-8x3",
    sessionLibraryId: "hyrox_run_5k_pace_8x3",
    name: "8 x 3 Minutes @ 5km Pace",
    category: "run_development",
    subcategory: "5k_pace_intervals",
    level: "advanced",
    durationMinutes: 60,
    qualityRunMinutes: 24,
    runDistanceKm: 9,
    hardDay: true,
    hardDayReason: "5k pace intervals",
    intensityType: "quality",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["block_3", "sharpening"],
    avoidIf: ["poor_recovery"],
    tags: ["5k_pace", "intervals"],
    progressionOptions: ["8\u219210 reps", "90s\u219245s rest"],
    editableVariables: ["reps", "recoverySeconds", "targetPace"],
    prescription: {"objective": "5k pace intervals — stop if pace drops.", "warmup": ["12 min easy", "Strides"], "mainSet": ["8×3 min @ 5k pace", "90s easy"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Rep paces", "RPE", "Form breakdown Y/N"], "coachNote": "Progress 8→10 reps; rest 90→45s.", "progression": "8 reps → 10 reps."},
  }),
  buildCoachEntry({
    id: "10x400-fast",
    sessionLibraryId: "coach_10x400-fast",
    name: "10 x 400m Controlled Fast",
    category: "run_development",
    subcategory: "speed_endurance",
    level: "intermediate",
    durationMinutes: 50,
    qualityRunMinutes: 18,
    runDistanceKm: 7,
    hardDay: true,
    hardDayReason: "Speed intervals",
    intensityType: "quality",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["speed_economy"],
    avoidIf: ["beginner"],
    tags: ["400m", "speed"],
    editableVariables: ["reps", "targetPace"],
    prescription: {"objective": "Controlled fast 400s without huge volume.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["10×400m @ 5k/3k controlled", "60s easy"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8", "whatToRecord": ["400 splits", "RPE"], "coachNote": "Faster economy work."},
  }),
  buildCoachEntry({
    id: "5x1km-10k",
    sessionLibraryId: "coach_5x1km-10k",
    name: "5 x 1km @ 10km Pace",
    category: "run_development",
    subcategory: "10k_pace",
    level: "intermediate",
    durationMinutes: 55,
    qualityRunMinutes: 20,
    runDistanceKm: 8,
    hardDay: true,
    hardDayReason: "10k pace reps",
    intensityType: "quality",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["bridge_tempo_speed"],
    avoidIf: [],
    tags: ["10k_pace"],
    editableVariables: ["reps", "targetPace"],
    prescription: {"objective": "Bridge tempo and faster work.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["5×1km @ 10km pace", "90s easy"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Km splits"], "coachNote": "Controlled — not all-out."},
  }),
  buildCoachEntry({
    id: "ski-th",
    sessionLibraryId: "hyrox_erg_ski_threshold_8x4",
    name: "SkiErg Threshold \u2014 8 x 4 Minutes",
    category: "erg_intervals",
    subcategory: "ski_threshold",
    level: "intermediate",
    durationMinutes: 50,
    thresholdMinutes: 32,
    ergMinutes: 45,
    hardDay: true,
    intensityType: "threshold",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["SkiErg"],
    bestFor: ["running_limited", "ski_weakness"],
    avoidIf: ["shoulder_niggle"],
    tags: ["ski", "threshold"],
    editableVariables: ["reps", "repDurationMinutes", "recoverySeconds", "targetSplit"],
    prescription: {"objective": "Ski threshold — low run impact.", "warmup": ["5 min easy ski", "Shoulder prep"], "mainSet": ["8×4 min @ ski threshold", "60–90s easy"], "cooldown": ["5 min easy ski"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Avg split", "Watts", "RPE"], "coachNote": "~5s/500m faster than race if HR supports."},
  }),
  buildCoachEntry({
    id: "row-th",
    sessionLibraryId: "hyrox_erg_row_threshold_8x4",
    name: "RowErg Threshold \u2014 8 x 4 Minutes",
    category: "erg_intervals",
    subcategory: "row_threshold",
    level: "intermediate",
    durationMinutes: 50,
    thresholdMinutes: 32,
    ergMinutes: 45,
    hardDay: true,
    intensityType: "threshold",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["RowErg"],
    bestFor: ["row_weakness", "pm_threshold_option"],
    avoidIf: ["low_back_flare"],
    tags: ["row", "threshold"],
    editableVariables: ["reps", "targetSplit"],
    prescription: {"objective": "Row threshold for station durability.", "warmup": ["5 min easy row"], "mainSet": ["8×4 min @ row threshold", "60–90s easy"], "cooldown": ["5 min easy row"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["500m splits", "RPE"], "coachNote": "PM option for advanced if spaced."},
  }),
  buildCoachEntry({
    id: "mixed-erg-th",
    sessionLibraryId: "coach_mixed-erg-th",
    name: "Ski/Row Mixed Threshold",
    category: "erg_intervals",
    subcategory: "mixed_threshold",
    level: "intermediate",
    durationMinutes: 50,
    thresholdMinutes: 32,
    ergMinutes: 45,
    hardDay: true,
    intensityType: "threshold",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["SkiErg", "RowErg"],
    bestFor: ["engine_no_run_impact"],
    avoidIf: [],
    tags: ["ski", "row", "threshold"],
    editableVariables: ["reps", "ergModality"],
    prescription: {"objective": "Mixed erg threshold.", "warmup": ["5 min each easy"], "mainSet": ["4×4 min Ski + 4×4 min Row", "60s recovery"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Splits each modality"], "coachNote": "Engine without run damage."},
  }),
  buildCoachEntry({
    id: "bike-th",
    sessionLibraryId: "coach_bike-th",
    name: "Bike Threshold \u2014 5 x 5 Minutes",
    category: "erg_intervals",
    subcategory: "bike_threshold",
    level: "intermediate",
    durationMinutes: 45,
    thresholdMinutes: 25,
    bikeMinutes: 40,
    hardDay: true,
    intensityType: "threshold",
    impactType: "bike",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Bike"],
    bestFor: ["injured", "low_impact_threshold"],
    avoidIf: [],
    tags: ["bike", "threshold"],
    editableVariables: ["reps", "recoverySeconds"],
    prescription: {"objective": "Bike threshold without impact.", "warmup": ["5 min easy spin"], "mainSet": ["5×5 min bike threshold", "2 min easy"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Power/HR", "RPE"], "coachNote": "For athletes needing TH without run."},
  }),
  buildCoachEntry({
    id: "mixed-erg-easy",
    sessionLibraryId: "hyrox_erg_mixed_aerobic",
    name: "Mixed Erg Aerobic",
    category: "easy_erg",
    subcategory: "mixed_z2",
    level: "all",
    durationMinutes: 90,
    ergMinutes: 90,
    bikeMinutes: 45,
    hardDay: false,
    intensityType: "easy",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["SkiErg", "RowErg", "Bike"],
    bestFor: ["high_volume_aerobic"],
    avoidIf: ["needs_run_skill"],
    tags: ["z2", "mixed_erg"],
    editableVariables: ["durationMinutes", "targetRPE"],
    prescription: {"objective": "High-volume Z1/low Z2 mixed erg.", "warmup": ["3 min each easy"], "mainSet": ["3 rounds: 15 min bike · 10 min row · 5 min ski @ easy"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "2–4", "whatToRecord": ["Duration", "RPE"], "coachNote": "True easy — not sneaky threshold."},
  }),
  buildCoachEntry({
    id: "gym-aerobic-upper",
    sessionLibraryId: "hyrox_gym_aerobic_upper_grip",
    name: "Easy Gym Aerobic + Upper/Grip",
    category: "easy_erg",
    subcategory: "gym_aerobic_upper",
    level: "all",
    durationMinutes: 75,
    ergMinutes: 50,
    bikeMinutes: 45,
    strengthMinutes: 10,
    hardDay: false,
    intensityType: "easy",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    equipmentRequired: ["Bike", "SkiErg", "DBs", "Pull-up bar"],
    bestFor: ["monday_friday_support"],
    avoidIf: [],
    tags: ["z2", "upper", "grip"],
    isOptionalAddOn: true,
    editableVariables: ["durationMinutes", "upperAddOn"],
    prescription: {"objective": "Easy aerobic + upper/grip support.", "warmup": ["5 min easy"], "mainSet": ["45–75 min easy bike/ski/row", "10 min upper EMOM: pull-ups / push-ups", "DB grip holds"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "2–4", "whatToRecord": ["Duration", "RPE", "Grip hold time"], "coachNote": "Monday/Friday support — optional add-on OK."},
  }),
  buildCoachEntry({
    id: "easy-bike",
    sessionLibraryId: "hyrox_erg_bike_z2",
    name: "Easy Bike Z2",
    category: "easy_erg",
    subcategory: "bike_z2",
    level: "all",
    durationMinutes: 60,
    bikeMinutes: 60,
    hardDay: false,
    intensityType: "easy",
    impactType: "bike",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Bike"],
    bestFor: ["recovery_support", "doubles"],
    avoidIf: [],
    tags: ["bike", "z2"],
    editableVariables: ["durationMinutes", "targetRPE"],
    prescription: {"objective": "Easy bike aerobic.", "warmup": ["5 min easy spin"], "mainSet": ["45–90 min Z1/low Z2 cycling"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "2–4", "whatToRecord": ["Duration", "HR", "RPE"], "coachNote": "Scale Z1 vs Z2 to weekly hours."},
  }),
  buildCoachEntry({
    id: "easy-ski-row",
    sessionLibraryId: "coach_easy-ski-row",
    name: "Easy Ski/Row Aerobic",
    category: "easy_erg",
    subcategory: "easy_ski_row",
    level: "all",
    durationMinutes: 55,
    ergMinutes: 55,
    hardDay: false,
    intensityType: "easy",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["SkiErg", "RowErg"],
    bestFor: ["easy_day"],
    avoidIf: [],
    tags: ["z2", "ski", "row"],
    editableVariables: ["durationMinutes", "targetRPE"],
    prescription: {"objective": "Easy ski/row aerobic.", "warmup": ["3 min each easy"], "mainSet": ["40–75 min easy ski/row split"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "2–4", "whatToRecord": ["Duration", "Splits", "RPE"], "coachNote": "Conversational effort."},
  }),
  buildCoachEntry({
    id: "long-bike",
    sessionLibraryId: "coach_long-bike",
    name: "Long Bike Z2",
    category: "easy_erg",
    subcategory: "long_bike",
    level: "advanced",
    durationMinutes: 120,
    bikeMinutes: 120,
    hardDay: false,
    intensityType: "easy",
    impactType: "bike",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Bike"],
    bestFor: ["high_volume_support"],
    avoidIf: ["fatigued_legs"],
    tags: ["bike", "long"],
    editableVariables: ["durationMinutes"],
    prescription: {"objective": "Long low-impact aerobic.", "warmup": ["5 min easy"], "mainSet": ["90–150 min bike Z1/low Z2"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "2–4", "whatToRecord": ["Duration", "Fuel", "RPE"], "coachNote": "Fueling practice for pros."},
  }),
  buildCoachEntry({
    id: "recovery-flush",
    sessionLibraryId: "coach_recovery-flush",
    name: "Recovery Flush",
    category: "easy_erg",
    subcategory: "recovery",
    level: "all",
    durationMinutes: 35,
    ergMinutes: 30,
    bikeMinutes: 15,
    hardDay: false,
    intensityType: "easy",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Bike", "SkiErg", "RowErg"],
    bestFor: ["recovery_days"],
    avoidIf: ["complete_rest_prescribed"],
    tags: ["recovery"],
    editableVariables: ["durationMinutes"],
    prescription: {"objective": "Very easy flush — feel better after.", "warmup": ["Mobility 5 min"], "mainSet": ["25–45 min very easy rotating erg"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "1–2", "whatToRecord": ["RPE", "Leg feel after"], "coachNote": "RPE 1–2 only."},
  }),
  buildCoachEntry({
    id: "pull-push-emom",
    sessionLibraryId: "coach_pull-push-emom",
    name: "Pull-Up + Push-Up EMOM",
    category: "upper_grip",
    subcategory: "upper_emom",
    level: "all",
    durationMinutes: 15,
    strengthMinutes: 10,
    stationVolume: 10,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "low",
    stationStress: "low",
    equipmentRequired: ["Pull-up bar"],
    bestFor: ["upper_support"],
    avoidIf: ["shoulder_injury"],
    tags: ["emom", "upper"],
    isOptionalAddOn: true,
    editableVariables: ["reps", "load"],
    prescription: {"objective": "Quick upper density add-on.", "warmup": ["Band shoulders"], "mainSet": ["10 min EMOM: min1 6–8 pull-ups · min2 15–20 push-ups"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6", "whatToRecord": ["Reps completed"], "coachNote": "Scale assisted pull-ups / incline push-ups."},
  }),
  buildCoachEntry({
    id: "grip-holds",
    sessionLibraryId: "hyrox_gym_aerobic_upper_grip",
    name: "Heavy DB Grip Holds",
    category: "upper_grip",
    subcategory: "grip",
    level: "all",
    durationMinutes: 20,
    strengthMinutes: 15,
    stationVolume: 5,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    equipmentRequired: ["Heavy DBs"],
    bestFor: ["grip_carry_weakness"],
    avoidIf: ["grip_injury"],
    tags: ["grip"],
    editableVariables: ["sets", "holdSeconds", "load"],
    prescription: {"objective": "Grip capacity above race weight where safe.", "warmup": ["Wrist warm-up"], "mainSet": ["4–5×45–60s heavy DB holds", "Rest 60–90s"], "cooldown": ["Stretch forearms"], "targetPace": null, "targetLoad": "Above race farmer weight", "targetHR": null, "targetRPE": null, "whatToRecord": ["Load", "Hold time", "RPE"], "coachNote": "Heavier than farmer race weight if possible."},
  }),
  buildCoachEntry({
    id: "carry-grip",
    sessionLibraryId: "coach_carry-grip",
    name: "Carry + Grip Builder",
    category: "upper_grip",
    subcategory: "carry_grip",
    level: "intermediate",
    durationMinutes: 35,
    runDistanceKm: 0,
    strengthMinutes: 30,
    stationVolume: 4,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Farmer handles", "DBs"],
    bestFor: ["carry_weakness"],
    avoidIf: [],
    tags: ["carry", "grip"],
    editableVariables: ["rounds", "load", "distanceM"],
    prescription: {"objective": "Carry and grip combined.", "warmup": ["Light carries"], "mainSet": ["4 rounds: 40–60m farmer carry · 45s DB hold · 90s rest"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7", "whatToRecord": ["Load", "Distance", "Grip failure"], "coachNote": "Record grip failure point."},
  }),
  buildCoachEntry({
    id: "sled-pull-upper",
    sessionLibraryId: "coach_sled-pull-upper",
    name: "Sled Pull Upper Support",
    category: "upper_grip",
    subcategory: "sled_pull_support",
    level: "intermediate",
    durationMinutes: 45,
    strengthMinutes: 40,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    equipmentRequired: ["Cable", "DBs", "Rope"],
    bestFor: ["sled_pull_limiter"],
    avoidIf: [],
    tags: ["sled_pull", "upper"],
    editableVariables: ["sets", "reps", "load"],
    prescription: {"objective": "Upper support for sled pull.", "warmup": ["Band shoulders"], "mainSet": ["Lat pulldown 4×10", "Seated row 4×10", "Rope pulls 5×20–30s", "DB holds 3×max"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Loads", "Hold times"], "coachNote": "Sled pull / grip-limited athletes."},
  }),
  buildCoachEntry({
    id: "upper-support",
    sessionLibraryId: "coach_upper-support",
    name: "Upper Strength Support",
    category: "upper_grip",
    subcategory: "upper_support",
    level: "all",
    durationMinutes: 45,
    strengthMinutes: 40,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Gym"],
    bestFor: ["general_upper"],
    avoidIf: ["day_before_wb_max"],
    tags: ["upper"],
    editableVariables: ["exercises", "sets", "reps"],
    prescription: {"objective": "Moderate upper — don't compromise WB/sled.", "warmup": ["Band prep"], "mainSet": ["Pull · push · shoulder accessory · core/bracing — higher reps"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Loads", "RPE"], "coachNote": "Should not compromise wall ball sessions."},
  }),
  buildCoachEntry({
    id: "legs",
    sessionLibraryId: "hyrox_strength_heavy_legs",
    name: "Lower Strength Endurance \u2014 Hyrox Legs",
    category: "strength_endurance",
    subcategory: "lower_strength_endurance",
    level: "all",
    durationMinutes: 65,
    strengthMinutes: 55,
    stationVolume: 12,
    hardDay: true,
    hardDayReason: "Lower-body strength endurance",
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Gym", "Sandbag", "Sled optional"],
    bestFor: ["sled_lunge_wb_durability"],
    avoidIf: ["day_before_threshold"],
    tags: ["legs", "staple"],
    isStaple: true,
    preferredDay: "Thu",
    editableVariables: ["sets", "reps", "tempo", "load", "coachNote"],
    prescription: {"objective": "Hyrox leg endurance — tempo reps not max strength.", "warmup": ["Activation", "Light squat pattern"], "mainSet": ["A: Tempo hack/squat 4×8–10 · 3s lower", "B: RDL 4×8", "C: Sandbag lunges 3×20–30m", "D: Quad extension 3×15–20", "E: Calf iso 3–4×30–45s"], "cooldown": ["Stretch quads/calves"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7", "whatToRecord": ["Loads", "RPE", "Lunge breaks"], "coachNote": "Thursday staple — hard due to local fatigue.", "safetyNote": "Avoid DOMS before key runs."},
  }),
  buildCoachEntry({
    id: "hack-squat-focus",
    sessionLibraryId: "coach_hack-squat-focus",
    name: "Tempo Hack Squat Focus",
    category: "strength_endurance",
    subcategory: "hack_squat",
    level: "intermediate",
    durationMinutes: 50,
    strengthMinutes: 45,
    stationVolume: 8,
    hardDay: true,
    hardDayReason: "Leg strength endurance",
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Hack squat", "Calf machine"],
    bestFor: ["sled_lunge_wb"],
    avoidIf: [],
    tags: ["hack_squat"],
    editableVariables: ["sets", "reps", "tempo"],
    prescription: {"objective": "Hack squat eccentric focus.", "warmup": ["Light sets"], "mainSet": ["5×8 hack squat @ 3s eccentric", "Superset calf raises", "3×20 quad extensions"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7", "whatToRecord": ["Load", "RPE"], "coachNote": "Sled/lunge/WB leg endurance."},
  }),
  buildCoachEntry({
    id: "lunge-durability",
    sessionLibraryId: "coach_lunge-durability",
    name: "Lunge Durability Session",
    category: "strength_endurance",
    subcategory: "lunge_durability",
    level: "intermediate",
    durationMinutes: 50,
    strengthMinutes: 45,
    stationVolume: 6,
    hardDay: true,
    hardDayReason: "Lunge volume",
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Sandbag"],
    bestFor: ["lunge_weakness"],
    avoidIf: ["knee_pain"],
    tags: ["lunge"],
    editableVariables: ["sets", "distanceM", "load"],
    prescription: {"objective": "Lunge-specific durability.", "warmup": ["Lunge pattern prep"], "mainSet": ["4–6×20–30m sandbag lunges · 90s rest", "Reverse lunges 3×10/side", "Calf iso 3×45s"], "cooldown": ["Hip stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Breaks", "Load", "RPE"], "coachNote": "Walk lunges if form breaks."},
  }),
  buildCoachEntry({
    id: "sled-support-strength",
    sessionLibraryId: "coach_sled-support-strength",
    name: "Sled Support Strength",
    category: "strength_endurance",
    subcategory: "sled_strength",
    level: "intermediate",
    durationMinutes: 55,
    strengthMinutes: 50,
    stationVolume: 12,
    hardDay: true,
    hardDayReason: "Sled strength",
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Sled", "Leg press"],
    bestFor: ["sled_weakness"],
    avoidIf: ["low_back_acute"],
    tags: ["sled"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Sled-specific strength volume.", "warmup": ["Empty sled pushes"], "mainSet": ["Heavy sled push 6×12.5m", "Sled pull 6×12.5m", "Leg press 3×15", "Calf/quad finisher"], "cooldown": ["Walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Load", "Times", "RPE"], "coachNote": "Frequent sled exposure."},
  }),
  buildCoachEntry({
    id: "quad-calf",
    sessionLibraryId: "coach_quad-calf",
    name: "Quad + Calf Durability",
    category: "strength_endurance",
    subcategory: "quad_calf",
    level: "all",
    durationMinutes: 45,
    strengthMinutes: 40,
    hardDay: true,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    equipmentRequired: ["Gym"],
    bestFor: ["quad_calf_breakdown"],
    avoidIf: [],
    tags: ["quad", "calf"],
    editableVariables: ["sets", "reps"],
    prescription: {"objective": "Quad and calf durability.", "warmup": ["Light bike 5 min"], "mainSet": ["Spanish squat 4×45s", "Quad extension 4×20", "Seated calf 4×15–20", "Calf iso 3×45s"], "cooldown": ["Calf stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["RPE", "Hold times"], "coachNote": "Late-race leg support."},
  }),
  buildCoachEntry({
    id: "posterior-chain",
    sessionLibraryId: "coach_posterior-chain",
    name: "Posterior Chain Support",
    category: "strength_endurance",
    subcategory: "posterior",
    level: "intermediate",
    durationMinutes: 50,
    strengthMinutes: 45,
    hardDay: true,
    hardDayReason: "Posterior chain work",
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["Gym"],
    bestFor: ["posterior_chain"],
    avoidIf: [],
    tags: ["hinge"],
    editableVariables: ["sets", "reps", "load"],
    prescription: {"objective": "Posterior chain support.", "warmup": ["Hinge prep"], "mainSet": ["RDL/hinge 4×8", "Ham curl 3×12–15", "Back extension 3×12", "Calf accessory"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Loads", "RPE"], "coachNote": "Moderate hard session."},
  }),
  buildCoachEntry({
    id: "full-body-se",
    sessionLibraryId: "coach_full-body-se",
    name: "Full-Body Strength Endurance",
    category: "strength_endurance",
    subcategory: "full_body",
    level: "all",
    durationMinutes: 55,
    strengthMinutes: 50,
    hardDay: true,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    equipmentRequired: ["Gym"],
    bestFor: ["limited_days"],
    avoidIf: [],
    tags: ["full_body"],
    editableVariables: ["exercises", "sets", "reps"],
    prescription: {"objective": "Full-body strength endurance circuit.", "warmup": ["Movement prep"], "mainSet": ["Squat/lunge · hinge · push/pull · core/grip — higher reps, controlled rest"], "cooldown": ["Mobility"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Loads", "RPE"], "coachNote": "Good when time-limited."},
  }),
  buildCoachEntry({
    id: "wb-emom",
    sessionLibraryId: "hyrox_compromised_run_wallballs",
    name: "Wall Ball EMOM",
    category: "station_emom",
    subcategory: "wall_ball_emom",
    level: "all",
    durationMinutes: 15,
    stationVolume: 120,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "high",
    equipmentRequired: ["Wall ball"],
    bestFor: ["wall_ball_weakness"],
    avoidIf: ["shoulder_pain"],
    tags: ["emom", "wall_ball"],
    isOptionalAddOn: true,
    editableVariables: ["reps", "durationMinutes"],
    prescription: {"objective": "Wall ball density EMOM.", "warmup": ["WB technique"], "mainSet": ["10 min EMOM × 10–15 wall balls"], "cooldown": ["Shoulder mobility"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": null, "whatToRecord": ["Reps per min", "Breaks"], "coachNote": "Progress 10×10 → 10×12 → 12×12.", "progression": "10×10 → 12×12 → deload 8×10"},
  }),
  buildCoachEntry({
    id: "wb-density",
    sessionLibraryId: "coach_wb-density",
    name: "Wall Ball Density Builder",
    category: "station_emom",
    subcategory: "wall_ball_density",
    level: "intermediate",
    durationMinutes: 25,
    stationVolume: 100,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "high",
    equipmentRequired: ["Wall ball"],
    bestFor: ["wb_strategy"],
    avoidIf: [],
    tags: ["wall_ball", "density"],
    editableVariables: ["rounds", "reps", "restSeconds"],
    prescription: {"objective": "Wall ball density rounds.", "warmup": ["WB warm-up"], "mainSet": ["5 rounds: 20 wall balls · 60s rest"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Reps", "Rest used"], "coachNote": "Reduce rest / increase reps over block."},
  }),
  buildCoachEntry({
    id: "wb-under-fatigue",
    sessionLibraryId: "coach_wb-under-fatigue",
    name: "Wall Balls Under Fatigue",
    category: "station_emom",
    subcategory: "wall_ball_fatigue",
    level: "intermediate",
    durationMinutes: 35,
    ergMinutes: 15,
    stationVolume: 100,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Wall ball", "RowErg"],
    bestFor: ["wb_breathing_limiter"],
    avoidIf: [],
    tags: ["wall_ball", "row"],
    editableVariables: ["rounds", "reps"],
    prescription: {"objective": "WB when breathing is limiter.", "warmup": ["Easy row"], "mainSet": ["3–4 rounds: 500m row · 25 wall balls · 90s rest"], "cooldown": ["Easy bike"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["WB breaks", "Row split"], "coachNote": "Breathing control on WB."},
  }),
  buildCoachEntry({
    id: "bbj-emom",
    sessionLibraryId: "hyrox_compromised_sled_burpee",
    name: "Burpee Broad Jump EMOM",
    category: "station_emom",
    subcategory: "bbj_emom",
    level: "intermediate",
    durationMinutes: 15,
    stationVolume: 80,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Floor space"],
    bestFor: ["bbj_weakness"],
    avoidIf: ["low_back_acute"],
    tags: ["burpee", "emom"],
    isOptionalAddOn: true,
    editableVariables: ["reps", "durationMinutes"],
    prescription: {"objective": "BBJ rhythm EMOM.", "warmup": ["Hip hinge prep"], "mainSet": ["10–12 min EMOM: min1 6–10 BBJ · min2 walk/reset"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7", "whatToRecord": ["Reps", "Rhythm"], "coachNote": "Confidence and rhythm."},
  }),
  buildCoachEntry({
    id: "burpee-volume",
    sessionLibraryId: "coach_burpee-volume",
    name: "Burpee Volume Builder",
    category: "station_emom",
    subcategory: "burpee_volume",
    level: "intermediate",
    durationMinutes: 25,
    stationVolume: 100,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Floor space"],
    bestFor: ["burpee_weakness"],
    avoidIf: [],
    tags: ["burpee"],
    editableVariables: ["rounds", "distanceM"],
    prescription: {"objective": "BBJ volume progression.", "warmup": ["Movement prep"], "mainSet": ["5×20m BBJ · 60–90s rest"], "cooldown": ["Walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": null, "whatToRecord": ["Times", "RPE"], "coachNote": "Progress 20m → 30m → 40m.", "progression": "20m → 30m → 40m"},
  }),
  buildCoachEntry({
    id: "lunge-emom",
    sessionLibraryId: "coach_lunge-emom",
    name: "Sandbag Lunge EMOM",
    category: "station_emom",
    subcategory: "lunge_emom",
    level: "intermediate",
    durationMinutes: 15,
    stationVolume: 10,
    hardDay: false,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Sandbag"],
    bestFor: ["lunge_tolerance"],
    avoidIf: ["knee_pain"],
    tags: ["lunge", "emom"],
    isOptionalAddOn: true,
    editableVariables: ["durationSeconds", "load"],
    prescription: {"objective": "Lunge EMOM without chaos.", "warmup": ["Lunge pattern"], "mainSet": ["10 min EMOM: 20–30s sandbag lunges each minute"], "cooldown": ["Hip stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Reps", "Load"], "coachNote": "Controlled technique."},
  }),
  buildCoachEntry({
    id: "sled-density",
    sessionLibraryId: "hyrox_strength_lower_sled",
    name: "Sled Density Repeats",
    category: "station_emom",
    subcategory: "sled_density",
    level: "intermediate",
    durationMinutes: 30,
    stationVolume: 8,
    hardDay: true,
    intensityType: "steady",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Sled"],
    bestFor: ["sled_exposure"],
    avoidIf: ["low_back_acute"],
    tags: ["sled", "density"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Frequent sled exposure.", "warmup": ["Empty sled"], "mainSet": ["Every 2 min × 5–8: 12.5m sled push or pull"], "cooldown": ["Walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Load", "Times"], "coachNote": "Technique and density."},
  }),
  buildCoachEntry({
    id: "mixed-station-emom",
    sessionLibraryId: "coach_mixed-station-emom",
    name: "Mixed Station EMOM",
    category: "station_emom",
    subcategory: "mixed_emom",
    level: "intermediate",
    durationMinutes: 20,
    stationVolume: 16,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Wall ball", "Floor", "DBs", "SkiErg"],
    bestFor: ["mixed_station"],
    avoidIf: [],
    tags: ["emom", "mixed"],
    isOptionalAddOn: true,
    editableVariables: ["durationMinutes"],
    prescription: {"objective": "Mixed station exposure.", "warmup": ["Movement prep"], "mainSet": ["16 min EMOM: WB · burpees · farmer hold · easy ski"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7", "whatToRecord": ["Reps per station"], "coachNote": "Attach to hard days."},
  }),
  buildCoachEntry({
    id: "carry-wb-density",
    sessionLibraryId: "coach_carry-wb-density",
    name: "Carry + Wall Ball Density",
    category: "station_emom",
    subcategory: "carry_wb",
    level: "intermediate",
    durationMinutes: 30,
    stationVolume: 80,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Farmers", "Wall ball"],
    bestFor: ["grip_wb_fatigue"],
    avoidIf: [],
    tags: ["carry", "wall_ball"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Grip plus wall ball fatigue.", "warmup": ["Light carry"], "mainSet": ["4 rounds: 100m farmer carry · 20 wall balls · 90s rest"], "cooldown": ["Grip stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Load", "WB breaks"], "coachNote": "Record grip failure."},
  }),
  buildCoachEntry({
    id: "overload",
    sessionLibraryId: "hyrox_compromised_threshold_run_station_overload",
    name: "Threshold Run Into Station Overload",
    category: "hyrox_compromised",
    subcategory: "saturday_key",
    level: "advanced",
    durationMinutes: 65,
    thresholdMinutes: 27,
    qualityRunMinutes: 27,
    runDistanceKm: 5,
    stationVolume: 6,
    hardDay: true,
    hardDayReason: "Saturday key \u2014 threshold into station overload",
    intensityType: "threshold",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Stations"],
    bestFor: ["saturday_key", "intermediate_ready"],
    avoidIf: ["beginner", "poor_recovery", "race_week"],
    tags: ["threshold", "compromised", "staple"],
    isStaple: true,
    preferredDay: "Sat",
    similarSessions: ["run-wb", "run-mixed-stations", "mini-test"],
    progressionOptions: ["8\u219210\u00d73 min", "90s\u219245s rest", "750m run blocks"],
    editableVariables: ["reps", "runDistanceM", "station", "stationMinutes", "restSeconds"],
    prescription: {"objective": "Hybrid365 Saturday staple — TH run into station overload.", "warmup": ["10 min easy", "Strides / mobility"], "mainSet": ["Part 1: 8×3 min @ 5k pace · 90s rest", "Part 2: 750m run + 3 min station + 750m run ×2 · 120s between blocks"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Run pace drop-off %", "Station reps", "RPE", "Film final 750m"], "coachNote": "Station from athlete weakness.", "progression": "8→10 reps; rest 90→45s."},
  }),
  buildCoachEntry({
    id: "run-wb",
    sessionLibraryId: "hyrox_compromised_run_wallballs",
    name: "Run + Wall Balls Builder",
    category: "hyrox_compromised",
    subcategory: "run_wall_ball",
    level: "intermediate",
    durationMinutes: 55,
    runDistanceKm: 4,
    stationVolume: 100,
    hardDay: true,
    hardDayReason: "Compromised running",
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Wall ball"],
    bestFor: ["wall_ball_weakness"],
    avoidIf: ["shoulder_pain"],
    tags: ["compromised", "wall_ball"],
    similarSessions: ["wb-under-fatigue", "overload", "run-mixed-stations"],
    editableVariables: ["rounds", "runDistanceM", "stationReps"],
    prescription: {"objective": "Run after wall ball fatigue.", "warmup": ["Easy jog", "WB prep"], "mainSet": ["4 rounds: 800m run · 25 wall balls · 90s rest"], "cooldown": ["8 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Run splits", "WB breaks"], "coachNote": "Progress reps/rest/run distance.", "progression": "More reps · less rest · 1km runs."},
  }),
  buildCoachEntry({
    id: "run-sled-push",
    sessionLibraryId: "coach_run-sled-push",
    name: "Run + Sled Push Builder",
    category: "hyrox_compromised",
    subcategory: "run_sled_push",
    level: "intermediate",
    durationMinutes: 55,
    runDistanceKm: 3.5,
    stationVolume: 4,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Sled"],
    bestFor: ["sled_push"],
    avoidIf: ["low_back_acute"],
    tags: ["sled", "compromised"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Run after sled push.", "warmup": ["Jog", "Empty sled"], "mainSet": ["4 rounds: 600–800m run · 12.5–25m sled push · 90s rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Run splits", "Sled feel"], "coachNote": "Progress race load and run distance."},
  }),
  buildCoachEntry({
    id: "run-sled-pull",
    sessionLibraryId: "coach_run-sled-pull",
    name: "Run + Sled Pull Builder",
    category: "hyrox_compromised",
    subcategory: "run_sled_pull",
    level: "intermediate",
    durationMinutes: 55,
    runDistanceKm: 3.5,
    stationVolume: 4,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Sled"],
    bestFor: ["sled_pull"],
    avoidIf: [],
    tags: ["sled_pull", "compromised"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Sled pull then run rhythm.", "warmup": ["Jog", "Sled prep"], "mainSet": ["4 rounds: 600–800m run · 12.5–25m sled pull · 90s rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Run splits", "Pull time"], "coachNote": "Race-load progression."},
  }),
  buildCoachEntry({
    id: "run-burpee",
    sessionLibraryId: "coach_run-burpee",
    name: "Run + Burpee Builder",
    category: "hyrox_compromised",
    subcategory: "run_burpee",
    level: "intermediate",
    durationMinutes: 50,
    runDistanceKm: 3,
    stationVolume: 120,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Track", "Floor"],
    bestFor: ["burpee_weakness"],
    avoidIf: [],
    tags: ["burpee", "compromised"],
    editableVariables: ["rounds", "distanceM"],
    prescription: {"objective": "BBJ then run.", "warmup": ["Jog"], "mainSet": ["4 rounds: 600m run · 20–30m BBJ · 90s rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": null, "whatToRecord": ["Run splits", "BBJ pace"], "coachNote": "Progress to 800m / 40m BBJ.", "progression": "600m/20m → 800m/40m"},
  }),
  buildCoachEntry({
    id: "run-lunges",
    sessionLibraryId: "hyrox_compromised_run_lunges",
    name: "Run + Lunges Builder",
    category: "hyrox_compromised",
    subcategory: "run_lunges",
    level: "intermediate",
    durationMinutes: 55,
    runDistanceKm: 3.5,
    stationVolume: 4,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Sandbag"],
    bestFor: ["lunge_weakness"],
    avoidIf: ["knee_pain"],
    tags: ["lunges", "compromised"],
    editableVariables: ["rounds", "distanceM", "load"],
    prescription: {"objective": "Sandbag lunges then run.", "warmup": ["Jog", "Lunge prep"], "mainSet": ["3–4 rounds: 800m run · 30–40m sandbag lunges · 2 min rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Lunge breaks", "Run pace"], "coachNote": "Late-race legs focus."},
  }),
  buildCoachEntry({
    id: "run-carry",
    sessionLibraryId: "coach_run-carry",
    name: "Run + Farmer Carry Builder",
    category: "hyrox_compromised",
    subcategory: "run_carry",
    level: "intermediate",
    durationMinutes: 50,
    runDistanceKm: 3,
    stationVolume: 4,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Track", "Farmers"],
    bestFor: ["carry_weakness"],
    avoidIf: ["grip_injury"],
    tags: ["carry", "compromised"],
    editableVariables: ["rounds", "load"],
    prescription: {"objective": "Carry then run — grip and pace drop-off.", "warmup": ["Light carry"], "mainSet": ["4 rounds: 600m run · 100m carry · 90s rest"], "cooldown": ["Stretch grip"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Grip failure", "Run splits"], "coachNote": "Record pace drop-off."},
  }),
  buildCoachEntry({
    id: "run-ski-row",
    sessionLibraryId: "coach_run-ski-row",
    name: "Run + Ski/Row Builder",
    category: "hyrox_compromised",
    subcategory: "run_erg",
    level: "intermediate",
    durationMinutes: 55,
    runDistanceKm: 4,
    ergMinutes: 20,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    equipmentRequired: ["Track", "SkiErg", "RowErg"],
    bestFor: ["erg_fatigue"],
    avoidIf: [],
    tags: ["ski", "row", "compromised"],
    editableVariables: ["rounds", "ergModality"],
    prescription: {"objective": "Erg fatigue into run rhythm.", "warmup": ["Easy jog"], "mainSet": ["4 rounds: 800m run · 500m Ski/Row · 90s rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Erg splits", "Run splits"], "coachNote": "Erg fatigue into running."},
  }),
  buildCoachEntry({
    id: "mini-test",
    sessionLibraryId: "hyrox_compromised_mini_test",
    name: "Mini Hyrox Compromised Test",
    category: "hyrox_compromised",
    subcategory: "mini_test",
    level: "intermediate",
    durationMinutes: 50,
    runDistanceKm: 2.4,
    stationVolume: 80,
    hardDay: true,
    hardDayReason: "Benchmark test",
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Sandbag", "Wall ball"],
    bestFor: ["testing", "benchmark"],
    avoidIf: ["taper", "injury"],
    tags: ["test", "compromised"],
    editableVariables: ["stationReps", "runDistanceM"],
    prescription: {"objective": "Standardised compromised benchmark.", "warmup": ["10 min easy", "Station prep"], "mainSet": ["1km run · 40m lunges · 40m BBJ · 1km run"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Total time", "Run splits", "Drop-off %", "RPE"], "coachNote": "Film final 1km split."},
  }),
  buildCoachEntry({
    id: "half-hyrox",
    sessionLibraryId: "coach_half-hyrox",
    name: "Half Hyrox Simulation",
    category: "hyrox_compromised",
    subcategory: "simulation",
    level: "advanced",
    durationMinutes: 90,
    runDistanceKm: 4,
    stationVolume: 4,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Full station kit"],
    bestFor: ["race_phase"],
    avoidIf: ["early_beginner"],
    tags: ["simulation"],
    editableVariables: ["rounds", "stations"],
    prescription: {"objective": "Half race simulation.", "warmup": ["Full warm-up"], "mainSet": ["4×1km run + 4 stations by weakness/phase"], "cooldown": ["Easy flush"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Splits", "Station times", "RPE"], "coachNote": "Specific block — not early beginners."},
  }),
  buildCoachEntry({
    id: "late-race-legs",
    sessionLibraryId: "coach_late-race-legs",
    name: "Late-Race Legs Builder",
    category: "hyrox_compromised",
    subcategory: "late_race",
    level: "advanced",
    durationMinutes: 65,
    runDistanceKm: 3,
    stationVolume: 90,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Sandbag", "Wall ball"],
    bestFor: ["late_race_fatigue"],
    avoidIf: [],
    tags: ["late_race"],
    editableVariables: ["rounds"],
    prescription: {"objective": "Late-race leg and WB fatigue.", "warmup": ["Jog"], "mainSet": ["3 rounds: 1km run · 40m lunges · 30 wall balls · 2–3 min rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8", "whatToRecord": ["Run splits", "WB breaks"], "coachNote": "Lunge/WB fatigue tolerance."},
  }),
  buildCoachEntry({
    id: "run-mixed-stations",
    sessionLibraryId: "coach_run-mixed-stations",
    name: "Run + Mixed Stations Builder",
    category: "hyrox_compromised",
    subcategory: "mixed_stations",
    level: "intermediate",
    durationMinutes: 60,
    runDistanceKm: 4,
    stationVolume: 10,
    hardDay: true,
    intensityType: "race_pace",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Stations"],
    bestFor: ["flexible_compromised"],
    avoidIf: [],
    tags: ["compromised", "template"],
    similarSessions: ["run-wb", "overload"],
    editableVariables: ["rounds", "stations", "runDistanceM"],
    prescription: {"objective": "Flexible compromised template.", "warmup": ["Jog", "Station prep"], "mainSet": ["3–5 rounds: 600–800m run · 2 weakness stations · 90–120s rest"], "cooldown": ["Easy jog"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "7–8", "whatToRecord": ["Run splits", "Station times"], "coachNote": "Select stations by weakness."},
  }),
  buildCoachEntry({
    id: "parkrun-5k",
    sessionLibraryId: "hyrox_test_5k_tt",
    name: "5km Time Trial",
    category: "testing",
    subcategory: "run_benchmark",
    level: "all",
    durationMinutes: 50,
    runDistanceKm: 5,
    hardDay: true,
    hardDayReason: "Benchmark test",
    intensityType: "test",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["5km route"],
    bestFor: ["pace_calculator", "progress"],
    avoidIf: ["taper", "injury"],
    tags: ["test", "5k"],
    editableVariables: ["targetPace"],
    prescription: {"objective": "Primary run benchmark for pace prescription.", "warmup": ["15 min easy", "Strides"], "mainSet": ["5km time trial — even effort"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9–10", "whatToRecord": ["Total time", "Splits", "Conditions", "RPE"], "coachNote": "Update pace zones after — not every week."},
  }),
  buildCoachEntry({
    id: "tt-10k",
    sessionLibraryId: "coach_tt-10k",
    name: "10km Time Trial",
    category: "testing",
    subcategory: "run_benchmark",
    level: "advanced",
    durationMinutes: 70,
    runDistanceKm: 10,
    hardDay: true,
    hardDayReason: "Benchmark test",
    intensityType: "test",
    impactType: "run",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["10km route"],
    bestFor: ["threshold_tempo_accuracy"],
    avoidIf: ["taper"],
    tags: ["test", "10k"],
    editableVariables: ["targetPace"],
    prescription: {"objective": "10km benchmark for TH/tempo accuracy.", "warmup": ["15 min easy"], "mainSet": ["10km TT — even or slight negative split"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9", "whatToRecord": ["Time", "Splits", "HR"], "coachNote": "Race pace projection marker."},
  }),
  buildCoachEntry({
    id: "ski-1km-test",
    sessionLibraryId: "hyrox_test_1k_ski",
    name: "1km SkiErg Test",
    category: "testing",
    subcategory: "erg_benchmark",
    level: "all",
    durationMinutes: 35,
    ergMinutes: 15,
    hardDay: true,
    hardDayReason: "Erg benchmark",
    intensityType: "test",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["SkiErg"],
    bestFor: ["ski_threshold_targets"],
    avoidIf: ["shoulder_injury"],
    tags: ["test", "ski"],
    editableVariables: ["targetSplit"],
    prescription: {"objective": "Ski benchmark for erg pacing.", "warmup": ["5 min easy ski"], "mainSet": ["1000m SkiErg max effort"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9–10", "whatToRecord": ["Time", "Avg split", "Stroke rate"], "coachNote": "Same damper each retest."},
  }),
  buildCoachEntry({
    id: "row-1km-test",
    sessionLibraryId: "hyrox_test_1k_row",
    name: "1km RowErg Test",
    category: "testing",
    subcategory: "erg_benchmark",
    level: "all",
    durationMinutes: 35,
    ergMinutes: 15,
    hardDay: true,
    hardDayReason: "Erg benchmark",
    intensityType: "test",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    equipmentRequired: ["RowErg"],
    bestFor: ["row_threshold_targets"],
    avoidIf: ["low_back_acute"],
    tags: ["test", "row"],
    editableVariables: ["targetSplit"],
    prescription: {"objective": "Row benchmark for erg pacing.", "warmup": ["5 min easy row"], "mainSet": ["1000m row max effort"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9–10", "whatToRecord": ["Time", "500m splits", "Drag factor"], "coachNote": "Record drag factor."},
  }),
  buildCoachEntry({
    id: "wb-benchmark",
    sessionLibraryId: "hyrox_test_wallball",
    name: "Wall Ball Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    level: "all",
    durationMinutes: 30,
    stationVolume: 100,
    hardDay: true,
    hardDayReason: "Station benchmark",
    intensityType: "test",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "high",
    equipmentRequired: ["Wall ball"],
    bestFor: ["wall_ball_limiter"],
    avoidIf: ["shoulder_pain"],
    tags: ["test", "wall_ball"],
    editableVariables: ["reps", "load"],
    prescription: {"objective": "Wall ball benchmark.", "warmup": ["WB technique"], "mainSet": ["100 wall balls for time OR max unbroken at race load"], "cooldown": ["Shoulder mobility"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9", "whatToRecord": ["Time", "Reps", "Breaks", "Ball weight"], "coachNote": "Same target height each test."},
  }),
  buildCoachEntry({
    id: "sled-benchmark",
    sessionLibraryId: "hyrox_test_sled",
    name: "Sled Push/Pull Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    level: "all",
    durationMinutes: 40,
    stationVolume: 2,
    hardDay: true,
    intensityType: "test",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Sled"],
    bestFor: ["sled_limiter"],
    avoidIf: ["low_back_acute"],
    tags: ["test", "sled"],
    editableVariables: ["load"],
    prescription: {"objective": "Sled benchmark at race load.", "warmup": ["Empty sled"], "mainSet": ["50m push + 50m pull @ race load — timed", "2–3 attempts full rest"], "cooldown": ["Walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "9", "whatToRecord": ["Push time", "Pull time", "Surface", "RPE"], "coachNote": "Same surface each test."},
  }),
  buildCoachEntry({
    id: "lunge-benchmark",
    sessionLibraryId: "hyrox_test_lunge",
    name: "Sandbag Lunge Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    level: "all",
    durationMinutes: 35,
    stationVolume: 100,
    hardDay: true,
    intensityType: "test",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Sandbag"],
    bestFor: ["lunge_limiter"],
    avoidIf: ["knee_pain"],
    tags: ["test", "lunge"],
    editableVariables: ["load", "distanceM"],
    prescription: {"objective": "Lunge benchmark.", "warmup": ["Lunge pattern"], "mainSet": ["100m timed lunges OR 4×25m repeatability"], "cooldown": ["Hip stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Time", "Breaks", "Load"], "coachNote": "Walk steps — no hopping."},
  }),
  buildCoachEntry({
    id: "carry-benchmark",
    sessionLibraryId: "hyrox_test_farmer",
    name: "Farmer Carry Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    level: "all",
    durationMinutes: 30,
    stationVolume: 200,
    hardDay: true,
    intensityType: "test",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Farmer handles"],
    bestFor: ["carry_limiter"],
    avoidIf: ["grip_injury"],
    tags: ["test", "farmer"],
    editableVariables: ["load", "distanceM"],
    prescription: {"objective": "Farmer carry benchmark.", "warmup": ["Light carries"], "mainSet": ["200m @ race load for time OR max hold"], "cooldown": ["Grip stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Time", "Load", "Grip breaks"], "coachNote": "Upright posture — quick feet."},
  }),
  buildCoachEntry({
    id: "bbj-benchmark",
    sessionLibraryId: "coach_bbj-benchmark",
    name: "Burpee Broad Jump Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    level: "intermediate",
    durationMinutes: 30,
    stationVolume: 80,
    hardDay: true,
    intensityType: "test",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    equipmentRequired: ["Floor space"],
    bestFor: ["bbj_limiter"],
    avoidIf: [],
    tags: ["test", "bbj"],
    editableVariables: ["distanceM"],
    prescription: {"objective": "BBJ benchmark.", "warmup": ["Movement prep"], "mainSet": ["80m for time OR 4×20m repeatability"], "cooldown": ["Stretch"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Time", "RPE"], "coachNote": "Rhythm and repeatability marker."},
  }),
  buildCoachEntry({
    id: "mini-compromised-test",
    sessionLibraryId: "hyrox_compromised_mini_test",
    name: "Mini Compromised Test",
    category: "testing",
    subcategory: "compromised_benchmark",
    level: "intermediate",
    durationMinutes: 50,
    runDistanceKm: 2.4,
    stationVolume: 80,
    hardDay: true,
    hardDayReason: "Compromised benchmark",
    intensityType: "test",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    equipmentRequired: ["Track", "Stations"],
    bestFor: ["repeatable_marker"],
    avoidIf: ["taper"],
    tags: ["test", "compromised"],
    editableVariables: ["runDistanceM", "stationReps"],
    prescription: {"objective": "Same as Mini Hyrox Compromised Test — repeatable marker.", "warmup": ["10 min easy"], "mainSet": ["1km run · 40m lunges · 40m BBJ · 1km run"], "cooldown": ["10 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "8–9", "whatToRecord": ["Total time", "Run drop-off", "RPE"], "coachNote": "Use every 4–6 weeks."},
  }),
  buildCoachEntry({
    id: "race-primer",
    sessionLibraryId: "coach_race-primer",
    name: "Race Week Primer",
    category: "race_week",
    subcategory: "primer",
    level: "all",
    durationMinutes: 45,
    qualityRunMinutes: 9,
    runDistanceKm: 5,
    hardDay: false,
    intensityType: "moderate",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    equipmentRequired: ["Track", "Light stations"],
    bestFor: ["race_week"],
    avoidIf: ["fatigue"],
    tags: ["race_week"],
    editableVariables: ["pickupReps"],
    prescription: {"objective": "Race week sharpness — not fatigue.", "warmup": ["15 min easy"], "mainSet": ["Short easy run", "3–4 race-pace pickups", "Light station touches"], "cooldown": ["Easy walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "5–6", "whatToRecord": ["RPE", "How legs feel"], "coachNote": "Sharp, not tired."},
  }),
  buildCoachEntry({
    id: "short-th-touch",
    sessionLibraryId: "coach_short-th-touch",
    name: "Short Threshold Touch",
    category: "race_week",
    subcategory: "threshold_touch",
    level: "advanced",
    durationMinutes: 40,
    thresholdMinutes: 9,
    runDistanceKm: 5,
    hardDay: false,
    intensityType: "threshold",
    impactType: "run",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Track"],
    bestFor: ["early_race_week"],
    avoidIf: ["late_race_week", "fatigued"],
    tags: ["race_week", "threshold"],
    editableVariables: ["reps", "targetPace"],
    prescription: {"objective": "Short controlled threshold touch.", "warmup": ["10 min easy"], "mainSet": ["3×3 min controlled threshold · 90s easy"], "cooldown": ["5 min easy"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "6–7", "whatToRecord": ["Paces", "RPE"], "coachNote": "Early race week only if appropriate."},
  }),
  buildCoachEntry({
    id: "station-technique",
    sessionLibraryId: "coach_station-technique",
    name: "Station Technique Touch",
    category: "race_week",
    subcategory: "technique",
    level: "all",
    durationMinutes: 30,
    stationVolume: 20,
    hardDay: false,
    intensityType: "easy",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    equipmentRequired: ["Stations"],
    bestFor: ["race_week"],
    avoidIf: [],
    tags: ["race_week", "technique"],
    editableVariables: ["station", "reps"],
    prescription: {"objective": "Light technique — no fatigue.", "warmup": ["Easy movement"], "mainSet": ["Light wall balls, sled feel, burpee rhythm, carries"], "cooldown": ["Mobility"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "3–4", "whatToRecord": ["Feel", "RPE"], "coachNote": "No fatigue — confidence only."},
  }),
  buildCoachEntry({
    id: "easy-shakeout",
    sessionLibraryId: "hyrox_run_easy",
    name: "Easy Shakeout Run",
    category: "race_week",
    subcategory: "shakeout",
    level: "all",
    durationMinutes: 35,
    qualityRunMinutes: 0,
    runDistanceKm: 5,
    hardDay: false,
    intensityType: "easy",
    impactType: "run",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Running surface"],
    bestFor: ["race_week"],
    avoidIf: [],
    tags: ["race_week", "easy"],
    editableVariables: ["durationMinutes"],
    prescription: {"objective": "Easy shakeout with strides.", "warmup": ["5 min easy"], "mainSet": ["20–30 min easy + 4 strides"], "cooldown": ["Walk"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "3–4", "whatToRecord": ["Pace", "RPE"], "coachNote": "Keep nerves calm."},
  }),
  buildCoachEntry({
    id: "mobility-recovery",
    sessionLibraryId: "coach_mobility-recovery",
    name: "Mobility / Recovery",
    category: "race_week",
    subcategory: "mobility",
    level: "all",
    durationMinutes: 40,
    ergMinutes: 10,
    bikeMinutes: 15,
    hardDay: false,
    intensityType: "easy",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "none",
    equipmentRequired: ["Mat", "Bike optional"],
    bestFor: ["race_week", "recovery"],
    avoidIf: [],
    tags: ["mobility", "recovery"],
    editableVariables: ["durationMinutes"],
    prescription: {"objective": "Mobility and recovery — race week or rest day.", "warmup": ["Breathing"], "mainSet": ["20–40 min mobility, easy spin, soft tissue"], "cooldown": ["Relaxation"], "targetPace": null, "targetLoad": null, "targetHR": null, "targetRPE": "1–2", "whatToRecord": ["How body feels"], "coachNote": "Parasympathetic recovery."},
  }),
];
