/**
 * HYROX batch sessions — high-fatigue station / leg / threshold programming.
 * Available in 1-1 HYROX programme builder admin session library.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";

const HYROX_SOURCE = "Hybrid365 library" as const;

const ADJACENCY_SAFETY =
  "Space from heavy leg strength, threshold runs, long compromised running, race simulation and sled/lunge overload unless deliberately planned.";

export const HYROX_BATCH_COACH_SESSIONS: CoachLibraryEntry[] = [
  // ——— Session 1: Echo / BBJ / Pull / Wall Ball Conditioning Stack ———
  buildCoachEntry({
    id: "hyrox-echo-bbj-stack",
    sessionLibraryId: "hyrox_station_echo_bbj_pull_wallball_stack",
    name: "Echo / BBJ / Pull / Wall Ball Conditioning Stack",
    category: "hyrox_compromised",
    subcategory: "hyrox_station_conditioning · non_running_compromised_conditioning",
    level: "intermediate",
    durationMinutes: 75,
    hardDay: true,
    hardDayReason: "Station overload — high aerobic power + muscular endurance",
    intensityType: "station_overload",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    bikeMinutes: 40,
    stationVolume: 250,
    equipmentRequired: ["Echo bike", "Sled pull setup", "Wall ball", "Open floor space"],
    bestFor: [
      "general_hyrox_build",
      "station_capacity_block",
      "leg_endurance_block",
      "hard_day",
      "secondary_hyrox_conditioning_day",
    ],
    avoidIf: [
      "beginner_as_written",
      "deload_week_full_volume",
      "race_week",
      "high_doms_state",
      "poor_recovery_state",
      "heavy_leg_strength",
      "threshold_run",
      "race_simulation",
    ],
    tags: [
      "hyrox",
      "station_overload",
      "non_running_compromised_conditioning",
      "hyrox_station_conditioning",
      "burpee",
      "sled_pull",
      "wall_ball",
      "echo_bike",
      "high_fatigue_hyrox_key_session",
    ],
    source: HYROX_SOURCE,
    similarSessions: ["overload", "kieran-bike-wb", "run-wb"],
    progressionOptions: [
      "Improve total time",
      "Reduce recovery",
      "Increase Echo output",
      "Reduce wall ball breaks",
      "Increase sled load",
      "Add running in later phase",
    ],
    regressionOptions: [
      "Beginner: 3×20 cal Echo + 20m BBJ · 2 rounds Part B scaled",
      "Intermediate: 4×30 cal + 30m BBJ · 2–3 scaled Part B rounds",
    ],
    editableVariables: ["rounds", "echoCalories", "bbjDistanceM", "sledLoad", "wallBallReps", "recovery"],
    hyroxMetadata: {
      primaryCategory: "hyrox_station_conditioning",
      secondaryCategory: "non_running_compromised_conditioning",
      sessionType: "station_overload",
      trainingGoals: [
        "hyrox_station_endurance",
        "muscular_endurance",
        "aerobic_power",
        "fatigue_resistance",
      ],
      energySystem: "threshold_high_aerobic",
      fatigueCost: "high",
      muscleDamageRisk: "moderate_high",
      impactTypeDetail: "low_running_impact_high_muscular_load",
      runningVolume: 0,
      runIncluded: false,
      hyroxSpecificity: "moderate_high",
      raceSimulation: false,
      stationFocus: ["burpee_broad_jump", "sled_pull", "wall_balls", "bike_erg_conditioning"],
      weaknessTargets: [
        "wall_balls",
        "burpees",
        "sled_pull",
        "leg_endurance",
        "station_fatigue_tolerance",
      ],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [
        "beginner_as_written",
        "deload_week_full_volume",
        "race_week",
        "high_doms_state",
        "poor_recovery_state",
      ],
      bestWeekPlacement: ["hard_day", "secondary_hyrox_conditioning_day", "station_overload_day"],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "threshold_run",
        "long_compromised_running",
        "race_simulation",
        "heavy_sled_day",
      ],
      bestTrainingPhase: ["general_hyrox_build", "station_capacity_block", "leg_endurance_block"],
      progressionMethods: [
        "improve_total_time",
        "reduce_recovery",
        "increase_echo_output",
        "reduce_wall_ball_breaks",
        "increase_sled_load",
        "add_running_in_later_phase",
      ],
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      highWallBallVolume: true,
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective:
        "High-fatigue non-running HYROX station conditioning — build station durability and aerobic power without extra running impact.",
      warmup: ["5–8 min easy Echo or bike", "BBJ + wall ball movement prep", "Light sled pull feel"],
      mainSet: [
        "Part A — 5 rounds: 40 cal Echo bike · 40m burpee broad jumps",
        "5 min easy recovery",
        "Part B — 3 rounds: 40 cal Echo · 40m sled pull @ pro load · 40 cal Echo · 50 wall balls · 3 min easy bike recovery",
        "Beginner: 3×20 cal + 20m BBJ · 2 rounds Part B scaled (20 cal / light sled / 20 WB)",
        "Intermediate: 4×30 cal + 30m BBJ · 2–3 scaled Part B rounds",
        "Advanced/Pro: as written — control Echo intensity and plan wall ball breaks",
      ],
      cooldown: ["5–8 min easy bike", "Hip flexor + shoulder mobility"],
      targetRPE: "8–9",
      whatToRecord: ["Round times", "Echo output", "BBJ rhythm", "Sled pull time", "Wall ball breaks", "RPE"],
      coachNote:
        "High-fatigue non-running HYROX station conditioning session. Useful for building station durability and aerobic power without extra running impact. Manage carefully around leg strength, threshold running and race-specific compromised sessions.",
      safetyNote: ADJACENCY_SAFETY,
      progression: "Improve pacing before adding load or reducing recovery.",
      regression: "Reduce rounds and distances — keep movement quality.",
    },
  }),

  // ——— Session 2: Threshold Bike Into Leg Endurance Builder ———
  buildCoachEntry({
    id: "hyrox-th-bike-leg-endurance",
    sessionLibraryId: "threshold_bike_leg_endurance_builder",
    name: "Threshold Bike Into Leg Endurance Builder",
    category: "strength_endurance",
    subcategory: "leg_endurance · hyrox_strength_endurance",
    level: "intermediate",
    durationMinutes: 75,
    hardDay: true,
    hardDayReason: "Threshold bike + lower-body muscular endurance overload",
    intensityType: "threshold_bike_plus_lower_body_endurance",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    thresholdMinutes: 24,
    bikeMinutes: 35,
    strengthMinutes: 45,
    stationVolume: 200,
    equipmentRequired: [
      "Bike or Assault bike",
      "Hack squat or leg press",
      "Barbell or dumbbells for RDL",
      "Wall ball",
      "Open space for lunges",
    ],
    bestFor: [
      "general_hyrox_build",
      "leg_endurance_block",
      "station_capacity_block",
      "hard_lower_body_day",
      "hyrox_leg_endurance_non_running",
    ],
    avoidIf: [
      "beginner_as_written",
      "race_week_full_volume",
      "deload_week_full_volume",
      "high_doms_state",
      "poor_recovery_state",
      "recent_heavy_leg_day",
      "knee_pain",
    ],
    tags: [
      "hyrox",
      "hyrox_leg_endurance_non_running",
      "leg_endurance",
      "wall_ball",
      "lunge",
      "threshold",
      "bike",
      "high_fatigue_hyrox_key_session",
    ],
    source: HYROX_SOURCE,
    progressionOptions: [
      "Increase bike watts",
      "Reduce bike recovery",
      "Increase hack squat load",
      "Improve lunge split time",
      "Increase wall ball EMOM density",
    ],
    regressionOptions: [
      "Beginner: easy bike + goblet squats + short lunge + 6 min EMOM WB",
      "Intermediate: 6 bike rounds + reduced hack squat + 8–10 min EMOM",
    ],
    editableVariables: ["bikeWatts", "bikeRounds", "hackSquatLoad", "lungeDistanceM", "wallBallReps", "emomMinutes"],
    hyroxMetadata: {
      primaryCategory: "leg_endurance",
      secondaryCategory: "hyrox_strength_endurance",
      sessionType: "threshold_bike_plus_lower_body_endurance",
      trainingGoals: [
        "hyrox_leg_endurance",
        "quad_durability",
        "wall_ball_capacity",
        "lunge_endurance",
        "calf_durability",
        "fatigue_resistance",
        "aerobic_power",
      ],
      energySystem: "threshold_high_aerobic",
      fatigueCost: "high",
      muscleDamageRisk: "high",
      impactTypeDetail: "no_running_impact_high_muscular_load",
      runningVolume: 0,
      runIncluded: false,
      hyroxSpecificity: "high_station_specificity",
      raceSimulation: false,
      stationFocus: ["lunges", "wall_balls", "lower_body_strength_endurance", "bike_threshold", "calf_durability"],
      weaknessTargets: [
        "leg_endurance",
        "wall_balls",
        "lunges",
        "quad_fatigue",
        "post_race_doms",
        "station_durability",
      ],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [
        "beginner_as_written",
        "race_week_full_volume",
        "deload_week_full_volume",
        "high_doms_state",
        "poor_recovery_state",
        "recent_heavy_leg_day",
        "athlete_with_knee_pain",
      ],
      bestWeekPlacement: [
        "hard_lower_body_day",
        "hyrox_strength_endurance_day",
        "pm_session_after_threshold_day",
        "secondary_hard_day",
      ],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "long_compromised_running",
        "race_simulation",
        "hill_sprints",
        "hard_track_session",
        "heavy_sled_push_pull",
        "high_volume_lunges",
        "high_volume_wall_balls",
      ],
      bestTrainingPhase: [
        "general_hyrox_build",
        "off_season_strength_endurance",
        "leg_endurance_block",
        "station_capacity_block",
      ],
      progressionMethods: [
        "increase_bike_watts",
        "improve_bike_watt_consistency",
        "reduce_bike_recovery",
        "increase_hack_squat_load",
        "reduce_hack_squat_rest",
        "improve_lunge_split_time",
        "increase_wall_ball_density",
        "extend_wall_ball_emom_duration",
      ],
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      highWallBallVolume: true,
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective:
        "High-fatigue HYROX leg endurance — threshold bike work plus lower-body muscular endurance for quad, lunge and wall ball durability.",
      warmup: ["10–15 min Zone 1 bike", "Leg activation", "Wall ball prep 10 reps light"],
      mainSet: [
        "Part A: 20 min Zone 1 bike",
        "Part B — 8 rounds: 3 min Assault bike @ target watts · 60 sec rest",
        "Part C — 4 rounds: 12 tempo hack squats · 40 sec rest",
        "Part D — 3 rounds: 8 Romanian deadlifts",
        "Part E — 2 rounds: full station walking lunges 80m (targets ~2:20 / 2:10)",
        "Part F — 3 rounds: 8 calf isometrics",
        "Part G — 10 min EMOM: 20 wall balls every minute (200 total)",
        "Beginner/Intermediate: see scaling in progressionOptions",
      ],
      cooldown: ["Easy spin 5–8 min", "Quad + hip flexor stretch"],
      targetRPE: "8–9",
      whatToRecord: ["Bike watts per round", "Hack squat load", "Lunge times", "Wall ball breaks", "RPE", "Quad fatigue"],
      coachNote:
        "High-fatigue HYROX leg endurance session combining threshold bike work with lower-body muscular endurance. Very useful for building quad, lunge and wall ball durability without additional running impact. Place carefully around heavy leg strength and hard run sessions.",
      safetyNote: ADJACENCY_SAFETY,
    },
  }),

  // ——— Session 3: Ski Threshold Into Erg / Wall Ball Conditioning Stack ———
  buildCoachEntry({
    id: "hyrox-ski-erg-wb-stack",
    sessionLibraryId: "ski_threshold_erg_wallball_conditioning_stack",
    name: "Ski Threshold Into Erg / Wall Ball Conditioning Stack",
    category: "erg_intervals",
    subcategory: "hyrox_erg_conditioning · wall_ball_fatigue_resistance",
    level: "intermediate",
    durationMinutes: 75,
    hardDay: true,
    hardDayReason: "Ski threshold + erg/wall ball circuit density",
    intensityType: "non_running_hyrox_threshold_conditioning",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "high",
    sessionStress: "high",
    thresholdMinutes: 20,
    ergMinutes: 55,
    bikeMinutes: 25,
    stationVolume: 140,
    equipmentRequired: ["Bike or Assault bike", "SkiErg", "RowErg", "Wall ball"],
    bestFor: [
      "general_hyrox_build",
      "station_capacity_block",
      "erg_weakness_block",
      "wall_ball_capacity_block",
      "non_running_hyrox_erg_wallball_conditioning",
    ],
    avoidIf: [
      "beginner_as_written",
      "race_week_full_volume",
      "deload_week_full_volume",
      "poor_recovery_state",
      "high_wall_ball_doms",
      "shoulder_elbow_irritation",
      "recent_high_volume_wall_balls",
    ],
    tags: [
      "hyrox",
      "non_running_hyrox_erg_wallball_conditioning",
      "ski",
      "row",
      "wall_ball",
      "threshold",
      "erg",
      "high_fatigue_hyrox_key_session",
    ],
    source: HYROX_SOURCE,
    progressionOptions: [
      "Improve ski pace consistency",
      "Reduce ski rest",
      "Improve bike/row pace",
      "Reduce circuit rest",
      "Add final row + wall ball extension",
    ],
    regressionOptions: [
      "Beginner: 3 ski rounds + 4 scaled erg/WB rounds, no final extension",
      "Intermediate: 4 ski rounds + 5 circuits, optional 750m + 20 WB finish",
    ],
    editableVariables: ["skiPace", "bikeWatts", "rowPace", "wallBallReps", "rounds", "recovery"],
    hyroxMetadata: {
      primaryCategory: "hyrox_erg_conditioning",
      secondaryCategory: "wall_ball_fatigue_resistance",
      sessionType: "non_running_hyrox_threshold_conditioning",
      trainingGoals: [
        "ski_threshold_capacity",
        "row_threshold_capacity",
        "wall_ball_capacity",
        "erg_durability",
        "station_fatigue_resistance",
        "aerobic_power",
        "upper_body_pulling_endurance",
      ],
      energySystem: "threshold_high_aerobic",
      fatigueCost: "high",
      muscleDamageRisk: "moderate",
      impactTypeDetail: "no_running_impact_moderate_high_muscular_load",
      runningVolume: 0,
      runIncluded: false,
      hyroxSpecificity: "high_station_specificity",
      raceSimulation: false,
      stationFocus: [
        "ski_erg",
        "row_erg",
        "wall_balls",
        "bike_threshold",
        "upper_body_pulling_endurance",
        "squat_endurance",
      ],
      weaknessTargets: [
        "ski_erg",
        "row_erg",
        "wall_balls",
        "erg_pacing",
        "late_race_wall_ball_fatigue",
        "station_durability",
      ],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [
        "beginner_as_written",
        "race_week_full_volume",
        "deload_week_full_volume",
        "poor_recovery_state",
        "high_wall_ball_doms",
        "shoulder_elbow_irritation",
        "recent_high_volume_wall_balls",
      ],
      bestWeekPlacement: [
        "hard_conditioning_day",
        "secondary_hyrox_engine_day",
        "non_running_hard_day",
        "pm_session_for_advanced_athlete",
      ],
      avoidAdjacentTo: [
        "high_volume_wall_balls",
        "hard_ski_threshold",
        "heavy_upper_pulling",
        "long_compromised_running",
        "race_simulation",
        "hard_run_threshold_for_non_advanced_athlete",
        "heavy_leg_endurance_day",
      ],
      bestTrainingPhase: [
        "general_hyrox_build",
        "station_capacity_block",
        "erg_weakness_block",
        "wall_ball_capacity_block",
      ],
      progressionMethods: [
        "improve_ski_pace_consistency",
        "reduce_ski_rest",
        "increase_ski_reps",
        "improve_bike_watt_consistency",
        "improve_row_pace_consistency",
        "reduce_circuit_rest",
        "increase_wall_ball_density",
        "add_final_row_wall_ball_extension",
      ],
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      highWallBallVolume: true,
    },
    prescription: {
      objective:
        "High-fatigue non-running HYROX erg and wall ball conditioning — build SkiErg, RowErg and wall ball durability.",
      warmup: ["10–15 min easy bike", "Ski + row prep", "10 light wall balls"],
      mainSet: [
        "Part A: 20 min bike Zone 1",
        "Part B — 5 rounds: 4 min SkiErg @ 1:45–1:50/500m · 45 sec rest",
        "Part C: 5 min easy bike flow",
        "Part D — 6 rounds: 3 min Assault bike @ 400w · 20 wall balls · 500m row @ 1:45/500m · 60 sec rest",
        "Final round: 1km row + 40 extra wall balls",
        "Beginner/Intermediate: see regressionOptions",
      ],
      cooldown: ["Easy bike 5–8 min", "Lat + shoulder stretch"],
      targetRPE: "8–9",
      whatToRecord: ["Ski splits", "Bike watts", "Row splits", "Wall ball breaks", "RPE"],
      coachNote:
        "High-fatigue non-running HYROX erg and wall ball conditioning session. Strong option for building SkiErg, RowErg and wall ball durability without additional running impact. Best for intermediate-scaled, advanced and pro athletes.",
      safetyNote: ADJACENCY_SAFETY,
    },
  }),

  // ——— Session 4: Threshold Run Into Wall Ball Density + Bike Finish ———
  buildCoachEntry({
    id: "hyrox-th-run-wb-bike",
    sessionLibraryId: "threshold_run_wall_ball_density_bike_finish",
    name: "Threshold Run Into Wall Ball Density + Bike Finish",
    category: "threshold_runs",
    subcategory: "threshold_run · wall_ball_fatigue_resistance",
    level: "intermediate",
    durationMinutes: 65,
    hardDay: true,
    hardDayReason: "Sustained threshold running + dense wall balls",
    intensityType: "threshold_run_into_hyrox_station_density",
    impactType: "run",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    thresholdMinutes: 30,
    qualityRunMinutes: 30,
    runDistanceKm: 6,
    bikeMinutes: 15,
    stationVolume: 200,
    equipmentRequired: ["Treadmill or run space", "Wall ball", "C2 bike or bike erg"],
    bestFor: [
      "specific_hyrox_build",
      "wall_ball_weakness_block",
      "threshold_development_block",
      "threshold_run_into_wall_ball_density",
      "key_hard_day",
    ],
    avoidIf: [
      "beginner_as_written",
      "race_week_full_volume",
      "deload_week_full_volume",
      "poor_recovery_state",
      "high_quad_doms",
      "knee_pain",
      "achilles_or_calf_issue",
      "recent_high_volume_wall_balls",
    ],
    tags: [
      "hyrox",
      "threshold",
      "threshold_run_into_wall_ball_density",
      "wall_ball",
      "run",
      "bike",
      "high_fatigue_hyrox_key_session",
    ],
    source: HYROX_SOURCE,
    progressionOptions: [
      "Improve threshold pace",
      "Reduce run recovery",
      "Increase wall ball density",
      "Use heavier wall ball",
      "Extend bike Zone 3 duration",
    ],
    regressionOptions: [
      "Beginner: 2×6–8 min tempo + 6 min EMOM WB + easy bike",
      "Intermediate: 3×8 min threshold + 8 min EMOM + 10–12 min bike Z2–3",
    ],
    editableVariables: ["thresholdPace", "runRounds", "wallBallReps", "wallBallLoad", "bikeDurationMinutes"],
    hyroxMetadata: {
      primaryCategory: "threshold_run",
      secondaryCategory: "wall_ball_fatigue_resistance",
      sessionType: "threshold_run_into_hyrox_station_density",
      trainingGoals: [
        "threshold_run_durability",
        "wall_ball_capacity",
        "late_race_fatigue_resistance",
        "squat_endurance",
        "hyrox_specific_conditioning",
        "aerobic_power",
      ],
      energySystem: "threshold_high_aerobic",
      fatigueCost: "high",
      muscleDamageRisk: "moderate_high",
      impactTypeDetail: "moderate_running_impact_high_muscular_load",
      runningVolume: "30_min_threshold",
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["running", "wall_balls", "squat_endurance", "bike_zone_3"],
      weaknessTargets: [
        "threshold_running",
        "wall_balls",
        "late_race_wall_ball_fatigue",
        "breathing_under_fatigue",
        "squat_durability",
        "hyrox_finish_strength",
      ],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [
        "beginner_as_written",
        "race_week_full_volume",
        "deload_week_full_volume",
        "poor_recovery_state",
        "high_quad_doms",
        "knee_pain",
        "achilles_or_calf_issue",
        "recent_high_volume_wall_balls",
      ],
      bestWeekPlacement: [
        "key_hard_day",
        "threshold_day",
        "hyrox_specific_conditioning_day",
        "wall_ball_weakness_day",
      ],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "high_volume_wall_balls",
        "long_compromised_running",
        "hard_track_vo2",
        "sled_lunge_overload",
        "race_simulation",
        "another_threshold_run",
      ],
      bestTrainingPhase: [
        "specific_hyrox_build",
        "wall_ball_weakness_block",
        "threshold_development_block",
        "race_specific_preparation",
      ],
      progressionMethods: [
        "improve_threshold_pace",
        "reduce_run_recovery",
        "increase_wall_ball_density",
        "use_heavier_wall_ball",
        "extend_bike_zone_3_duration",
        "reduce_transition_time",
        "add_compromised_run_after_wall_balls_in_later_phase",
      ],
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      highWallBallVolume: true,
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective:
        "Hard HYROX-specific threshold session — sustained threshold running with high-density wall balls and Zone 3 bike finish.",
      warmup: ["10 min easy run", "Strides", "Wall ball prep"],
      mainSet: [
        "Part A — 3 rounds: 10 min run @ threshold pace · 90 sec walk/rest",
        "3 min rest after final rep",
        "Part B — 10 min EMOM: 20 wall balls every minute (200 total) @ race/heavy load",
        "Part C: 15 min C2 bike @ Zone 3",
        "Beginner/Intermediate: see regressionOptions",
      ],
      cooldown: ["5–8 min easy bike or walk", "Quad + calf stretch"],
      targetRPE: "8–9",
      whatToRecord: ["Threshold run pace/HR", "Wall ball breaks", "Bike avg watts/HR", "RPE", "Breathing control"],
      coachNote:
        "Hard HYROX-specific threshold session combining sustained threshold running with high-density wall balls and a Zone 3 bike finish. Strong for late-race wall ball durability. Place carefully around heavy leg work and other hard run sessions.",
      safetyNote: ADJACENCY_SAFETY,
    },
  }),

  // ——— Session 5: Threshold Run + Hill Sprint Into Wall Ball / Ski Finish ———
  buildCoachEntry({
    id: "hyrox-th-hill-wb-ski",
    sessionLibraryId: "threshold_run_hill_sprint_wallball_ski_finish",
    name: "Threshold Run + Hill Sprint Into Wall Ball / Ski Finish",
    category: "hyrox_compromised",
    subcategory: "threshold_run · race_specific_hyrox_fatigue_resistance",
    level: "advanced",
    durationMinutes: 70,
    hardDay: true,
    hardDayReason: "Very high fatigue — threshold + hill sprints + dense WB + ski finish",
    intensityType: "threshold_run_hill_sprint_station_finish",
    impactType: "run",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "very_high",
    thresholdMinutes: 32,
    qualityRunMinutes: 38,
    runDistanceKm: 7,
    ergMinutes: 10,
    stationVolume: 230,
    equipmentRequired: [
      "Outdoor run space or treadmill",
      "Incline treadmill or hill",
      "Wall ball",
      "SkiErg",
    ],
    bestFor: [
      "late_race_specific_phase",
      "wall_ball_weakness_block",
      "peak_hyrox_preparation",
      "saturday_key_session",
      "race_specific_hyrox_fatigue_resistance",
      "high_fatigue_hyrox_key_session",
    ],
    avoidIf: [
      "beginner",
      "low_intermediate_as_written",
      "race_week_full_volume",
      "deload_week_full_volume",
      "poor_recovery_state",
      "high_quad_doms",
      "calf_or_achilles_issue",
      "knee_pain",
      "recent_hill_sprint_session",
      "recent_high_volume_wall_balls",
    ],
    tags: [
      "hyrox",
      "very_high_stress",
      "race_specific_hyrox_fatigue_resistance",
      "high_fatigue_hyrox_key_session",
      "threshold",
      "hill_sprints",
      "wall_ball",
      "ski",
    ],
    source: HYROX_SOURCE,
    progressionOptions: [
      "Improve threshold pace at same HR",
      "Reduce threshold recovery",
      "Increase hill sprint reps",
      "Improve ski finish pace",
    ],
    regressionOptions: [
      "Intermediate: 3×6–8 min threshold + 6×30s incline + 8 min EMOM WB + 6–8 min ski",
      "Beginner: do not use full structure — inspired scaled version only",
    ],
    editableVariables: ["thresholdPace", "hillSprintReps", "inclinePercent", "wallBallReps", "skiPace"],
    hyroxMetadata: {
      primaryCategory: "threshold_run",
      secondaryCategory: "race_specific_hyrox_fatigue_resistance",
      sessionType: "threshold_run_hill_sprint_station_finish",
      trainingGoals: [
        "threshold_run_durability",
        "late_race_wall_ball_capacity",
        "ski_erg_under_fatigue",
        "leg_power_endurance",
        "calf_quad_resilience",
        "hyrox_specific_fatigue_tolerance",
        "race_confidence",
      ],
      energySystem: "threshold_high_aerobic_with_anaerobic_spikes",
      fatigueCost: "very_high",
      muscleDamageRisk: "high",
      impactTypeDetail: "high_running_impact_high_muscular_load",
      runningVolume: "32_min_threshold_plus_6_min_incline_sprints",
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["running", "hill_sprints", "wall_balls", "ski_erg", "late_race_leg_fatigue"],
      weaknessTargets: [
        "threshold_running",
        "wall_balls",
        "late_race_wall_ball_fatigue",
        "ski_erg_finish",
        "leg_fatigue_resistance",
        "mental_tolerance",
      ],
      suitableLevels: ["advanced_scaled", "pro"],
      notSuitableFor: [
        "beginner",
        "low_intermediate_as_written",
        "race_week_full_volume",
        "deload_week_full_volume",
        "poor_recovery_state",
        "high_quad_doms",
        "calf_or_achilles_issue",
        "knee_pain",
        "recent_hill_sprint_session",
        "recent_high_volume_wall_balls",
      ],
      bestWeekPlacement: [
        "saturday_key_session",
        "race_specific_key_day",
        "final_big_session_before_taper",
        "wall_ball_weakness_overload_day",
      ],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "hard_track_vo2",
        "sled_lunge_overload",
        "another_threshold_run",
        "high_volume_wall_balls",
        "long_run_next_day",
        "hard_calf_achilles_loading",
        "race_simulation_within_72h",
      ],
      bestTrainingPhase: [
        "late_race_specific_phase",
        "wall_ball_weakness_block",
        "peak_hyrox_preparation",
        "final_big_sessions_before_taper",
      ],
      progressionMethods: [
        "improve_threshold_pace_at_same_hr",
        "reduce_threshold_recovery",
        "increase_hill_sprint_reps",
        "increase_wall_ball_density",
        "improve_ski_finish_pace",
        "reduce_station_transition_time",
        "improve_total_execution_quality",
      ],
      requiresAdvancedOrPro: true,
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      includesHillSprints: true,
      highWallBallVolume: true,
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective:
        "Very high-fatigue HYROX key session — threshold running, incline sprint fatigue, dense wall balls and SkiErg finish.",
      warmup: ["12 min easy run", "Strides", "Hill prep", "Wall ball + ski prep"],
      mainSet: [
        "Part A — 4 rounds: 8 min run @ threshold (e.g. 3:25/km) · 80 sec rest",
        "3 min easy jog transition",
        "Part B — 8 rounds: 45 sec hill/incline run @ 10% · 45 sec rest",
        "Part C — 10 min EMOM: 23 wall balls @ race weight every minute (230 total)",
        "Part D: Rest 3 min · 10 min SkiErg @ threshold/race-pressure (e.g. 1:49/500m)",
        "Beginner: do not use full structure",
        "Intermediate/Advanced: see regressionOptions",
        "Pro: as written with strict execution standards",
      ],
      cooldown: ["Easy walk 5 min", "Calf + quad mobility"],
      targetRPE: "9–10",
      whatToRecord: [
        "Threshold run paces",
        "Hill sprint quality",
        "Wall ball breaks",
        "Ski finish split",
        "RPE",
        "Leg feel next day",
      ],
      coachNote:
        "Very high-fatigue HYROX key session combining threshold running, incline sprint fatigue, dense wall balls and a SkiErg finish. Best for advanced/pro athletes in the late race-specific phase or final big sessions before taper. Requires careful placement and recovery management.",
      safetyNote:
        "Advanced/pro only. No calf/Achilles/knee issues. Not within 72h of race simulation. " + ADJACENCY_SAFETY,
    },
  }),

  // ——— Session 6: Assault Bike Into Lunge / Wall Ball Density ———
  buildCoachEntry({
    id: "hyrox-bike-lunge-wb-density",
    sessionLibraryId: "assault_bike_lunge_wallball_density",
    name: "Assault Bike Into Lunge / Wall Ball Density",
    category: "station_emom",
    subcategory: "hyrox_leg_endurance · wall_ball_lunge_capacity",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Fixed-window race-weight lunge + wall ball density",
    intensityType: "fixed_window_station_density",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    bikeMinutes: 30,
    stationVolume: 430,
    equipmentRequired: [
      "Assault bike",
      "Wall ball",
      "Race-weight lunge load",
      "Open space for lunges",
    ],
    bestFor: [
      "general_hyrox_build",
      "station_capacity_block",
      "lunge_weakness_block",
      "wall_ball_weakness_block",
      "leg_endurance_block",
      "fixed_window_station_density",
      "hyrox_leg_endurance_non_running",
    ],
    avoidIf: [
      "beginner_as_written",
      "race_week_full_volume",
      "deload_week_full_volume",
      "poor_recovery_state",
      "high_quad_doms",
      "knee_pain",
      "hip_flexor_irritation",
      "recent_high_volume_lunges",
      "recent_high_volume_wall_balls",
    ],
    tags: [
      "hyrox",
      "fixed_window_station_density",
      "hyrox_leg_endurance_non_running",
      "lunge",
      "wall_ball",
      "bike",
      "race_weight",
      "high_fatigue_hyrox_key_session",
    ],
    source: HYROX_SOURCE,
    progressionOptions: [
      "Increase bike watt consistency",
      "Increase lunge/wall ball reps",
      "Progress to race weight",
      "Reduce interval window",
      "Improve unbroken wall balls",
    ],
    regressionOptions: [
      "Beginner: 6×5 min — 2 min bike + 10–12 lunges + 8–10 WB",
      "Intermediate: 8×5 min — 2:30–3 min bike + 16–20 lunges + 12–15 WB",
    ],
    editableVariables: ["rounds", "bikeWatts", "lungeReps", "lungeLoad", "wallBallReps", "windowMinutes"],
    hyroxMetadata: {
      primaryCategory: "hyrox_leg_endurance",
      secondaryCategory: "wall_ball_lunge_capacity",
      sessionType: "fixed_window_station_density",
      trainingGoals: [
        "lunge_endurance",
        "wall_ball_capacity",
        "quad_durability",
        "glute_endurance",
        "station_fatigue_resistance",
        "race_weight_exposure",
        "aerobic_durability",
      ],
      energySystem: "aerobic_zone2_zone3",
      fatigueCost: "high",
      muscleDamageRisk: "high",
      impactTypeDetail: "no_running_impact_high_muscular_load",
      runningVolume: 0,
      runIncluded: false,
      hyroxSpecificity: "high_station_specificity",
      raceSimulation: false,
      stationFocus: [
        "lunges",
        "wall_balls",
        "assault_bike",
        "lower_body_station_density",
        "race_weight_exposure",
      ],
      weaknessTargets: [
        "lunges",
        "wall_balls",
        "leg_endurance",
        "quad_fatigue",
        "late_race_station_fatigue",
        "station_durability",
      ],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [
        "beginner_as_written",
        "race_week_full_volume",
        "deload_week_full_volume",
        "poor_recovery_state",
        "high_quad_doms",
        "knee_pain",
        "hip_flexor_irritation",
        "recent_high_volume_lunges",
        "recent_high_volume_wall_balls",
      ],
      bestWeekPlacement: [
        "hyrox_leg_endurance_day",
        "station_capacity_day",
        "secondary_hard_day",
        "non_running_hard_day",
        "pm_session_for_advanced_athlete",
      ],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "hard_threshold_run",
        "hill_sprint_session",
        "sled_lunge_overload",
        "long_compromised_running",
        "race_simulation",
        "high_volume_wall_balls",
        "long_run_next_day",
      ],
      bestTrainingPhase: [
        "general_hyrox_build",
        "station_capacity_block",
        "lunge_weakness_block",
        "wall_ball_weakness_block",
        "leg_endurance_block",
      ],
      progressionMethods: [
        "increase_bike_watt_consistency",
        "increase_lunge_reps",
        "increase_wall_ball_reps",
        "progress_to_race_weight",
        "reduce_interval_window",
        "improve_unbroken_wall_balls",
        "improve_lunge_speed",
        "add_compromised_run_in_later_phase",
      ],
      blocksRaceWeekFullVolume: true,
      blocksDeloadWeekFullVolume: true,
      highWallBallVolume: true,
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective:
        "Fixed-window HYROX lower-body station density — steady Assault bike, race-weight reverse lunges and race-weight wall balls.",
      warmup: ["5–8 min easy bike", "Lunge + wall ball prep", "Hip flexor mobility"],
      mainSet: [
        "10 rounds, every 5 minutes:",
        "3 min Assault bike @ steady/easy effort",
        "25 reverse lunges @ race weight",
        "18 wall balls @ race weight",
        "Rest remainder of 5 min",
        "Total: 30 min bike · 250 reverse lunges · 180 wall balls · ~50 min block",
        "Beginner: 6 rounds scaled · Intermediate: 8 rounds scaled",
        "Advanced/Pro: as written",
      ],
      cooldown: ["Easy spin 5 min", "Quad + hip flexor stretch"],
      targetRPE: "7–9",
      whatToRecord: [
        "Bike watts consistency",
        "Lunge pace/breaks",
        "Wall ball breaks",
        "Rest remaining each round",
        "RPE",
      ],
      coachNote:
        "Fixed-window HYROX lower-body station density session using steady Assault bike pressure, race-weight reverse lunges and race-weight wall balls. Excellent for building lunge and wall ball durability without extra running impact. High muscular fatigue cost — place carefully around heavy leg work and hard run sessions.",
      safetyNote: ADJACENCY_SAFETY,
    },
  }),
];
