/**
 * HYROX Volume Builders — audited, executable coach library sessions.
 *
 * Purpose: movement efficiency, local muscular endurance, station repeatability.
 * NOT maximal conditioning. NOT race simulation.
 *
 * Additive only — does not alter published athlete programmes.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";
import type { ProgrammingSessionStandards } from "@/app/lib/hyrox-team/modules/programmingSystem/types";

const SRC = "Hybrid365 library" as const;

const BUILDER_ADJACENCY = [
  "heavy_leg_strength",
  "race_simulation",
  "long_compromised_running",
  "very_high_fatigue_station_day",
];

function standards(partial: ProgrammingSessionStandards): ProgrammingSessionStandards {
  return partial;
}

function volumeBuilder(
  input: Omit<Parameters<typeof buildCoachEntry>[0], "category">
): CoachLibraryEntry {
  return buildCoachEntry({
    ...input,
    category: "hyrox_volume_builders",
    source: SRC,
    tags: Array.from(
      new Set([...(input.tags ?? []), "hyrox", "hyrox_volume_builder", "not_race_simulation"])
    ),
  });
}

/** Submaximal sled load cue used across sled builders. */
const SLED_LOAD_CUE =
  "Load: submaximal — complete every bout with unbroken technique and 2–3 effort units in reserve (not a max-load test).";

export const HYROX_VOLUME_BUILDER_COACH_SESSIONS: CoachLibraryEntry[] = [
  // ——— 1. Sled Capacity Builder (L1) ———
  volumeBuilder({
    id: "vb-sled-capacity-l1",
    sessionLibraryId: "hyrox_vb_sled_capacity_l1",
    name: "Sled Capacity Builder",
    subcategory: "sled_builders · capacity",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 360,
    strengthMinutes: 35,
    equipmentRequired: ["Sled", "Open floor ≥25m"],
    bestFor: ["station_capacity_block", "sled_weakness", "pairs_with_threshold"],
    avoidIf: ["high_doms_state", "race_week", "fresh_heavy_legs"],
    tags: ["sled", "sled_push", "sled_pull", "sled_builders", "pairs_with_threshold", "limiter_sled"],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-sled-pull-push-bbj-wb-l1",
    recommendedRegression: "Cut to 3 push + 3 pull · +15s rest · lighter sled",
    progressionOptions: ["Add 1 bout each", "Shorten rest to 45s", "Slight load increase if unbroken"],
    regressionOptions: ["3×25m each", "90s rest", "Lighter load"],
    editableVariables: ["sledLoad", "distanceM", "bouts", "restSeconds"],
    programmingStandards: standards({
      purpose: "Build sled push/pull local endurance and technical consistency at sub-max load.",
      primaryAdaptation: "sled_local_muscular_endurance",
      secondaryAdaptation: "station_pacing",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Open floor ≥25m"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Sled Pull / Push + Burpee Wall Ball Density",
      recommendedRegression: "3×25m push + 3×25m pull · 90s rest",
      suggestedSessionPlacement: [
        "secondary_station_day",
        "not_day_before_key_threshold",
        "pairs_after_easy_run",
      ],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: [
        "Sled load",
        "Push bouts completed",
        "Pull bouts completed",
        "Technique notes",
        "Session RPE",
      ],
    }),
    prescription: {
      objective:
        "Develop sled capacity with fixed rest and submaximal loading — stop if form collapses.",
      warmup: [
        "5 min easy bike or row",
        "2×10 bodyweight squats + 2×10 hip hinges",
        "2×15m light sled push + 2×15m light sled pull (build feel)",
      ],
      mainSet: [
        "SECTION A — Sled push: 4×25m · 60s walk rest between reps",
        SLED_LOAD_CUE,
        "Technical standard: upright torso, short steps, continuous drive — no grinding finish",
        "Transition: 2 min easy walk after Section A",
        "SECTION B — Sled pull: 4×25m · 60s walk rest between reps",
        "Technical standard: hips low, long pulls, strap tension constant",
        "Stop rule: if you cannot complete 25m unbroken with quality, drop load and finish remaining bouts",
      ],
      cooldown: ["5 min easy bike", "Hip flexor + posterior chain stretch 2 min"],
      targetLoad: "Submaximal — 2–3 RIR on every bout",
      targetRPE: "6–7",
      whatToRecord: ["Load", "Bouts completed", "Any load drops", "Session RPE"],
      coachNote:
        "Volume builder, not a max sled test. Prefer unbroken quality over heavier plates.",
      safetyNote: "Space from heavy legs and race simulation.",
      progression: "Progress to Sled Pull / Push + Burpee Wall Ball Density (same sled doses, denser second half).",
      regression: "3×25m push + 3×25m pull · 90s rest · lighter sled.",
    },
  }),

  // ——— 2. Coach-brief core session ———
  volumeBuilder({
    id: "vb-sled-pull-push-bbj-wb-l1",
    sessionLibraryId: "hyrox_vb_sled_pull_push_bbj_wb_l1",
    name: "Sled Pull / Push + Burpee Wall Ball Density",
    subcategory: "sled_builders · mixed_density",
    level: "intermediate",
    durationMinutes: 55,
    hardDay: true,
    hardDayReason: "Sled volume + BBJ/WB density — still submaximal builder",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    stationVolume: 475,
    strengthMinutes: 40,
    equipmentRequired: ["Sled", "Wall ball", "Open floor ≥30m"],
    bestFor: ["station_capacity_block", "sled_weakness", "wall_ball_weakness", "build_block"],
    avoidIf: ["beginner_as_written", "race_week", "high_doms_state", "poor_recovery_state"],
    tags: [
      "sled",
      "sled_push",
      "sled_pull",
      "burpee",
      "wall_ball",
      "density",
      "coach_brief_core",
      "limiter_sled",
      "limiter_wall_ball",
    ],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-continuous-station-l1",
    recommendedRegression: "vb-sled-capacity-l1",
    progressionOptions: [
      "Keep sled doses; add 1 BBJ/WB round",
      "Shorten Section 3 rest to 45s if unbroken",
    ],
    regressionOptions: [
      "Sled Capacity Builder only",
      "Section 3: 3 rounds · 20m BBJ + 20 WB",
    ],
    editableVariables: ["sledLoad", "wallBallReps", "bbjDistanceM", "rounds"],
    programmingStandards: standards({
      purpose:
        "Combine controlled sled capacity with burpee–wall ball density without race simulation.",
      primaryAdaptation: "sled_and_station_density",
      secondaryAdaptation: "wall_ball_repeatability",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 55,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Wall ball", "Open floor ≥30m"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Continuous Station Builder",
      recommendedRegression: "Sled Capacity Builder",
      suggestedSessionPlacement: ["key_station_day", "not_adjacent_threshold", "not_race_sim_day"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "threshold_run"],
      expectedRpe: "7–8",
      recommendedLoggingFields: [
        "Sled load",
        "Section 1–2 completion",
        "BBJ/WB round times",
        "Wall ball breaks",
        "Session RPE",
      ],
    }),
    prescription: {
      objective:
        "Execute fixed sled pull/push doses then controlled burpee broad jump + wall ball density — leave one gear in reserve.",
      warmup: [
        "5 min easy bike or row",
        "2×15m light sled push + 2×15m light sled pull",
        "10 wall balls + 10m easy burpee broad jumps",
      ],
      mainSet: [
        "SECTION 1 — Sled pull: 5×25m · 60s rest between reps",
        SLED_LOAD_CUE,
        "Technical standard: hips low, continuous strap tension, no stop-start mid-bout",
        "Transition: 2 min easy walk after Section 1",
        "SECTION 2 — Sled push: 4×25m · 60s rest between reps",
        "Technical standard: short steps, upright drive — stop and drop load if form fails",
        "Transition: 3 min easy walk / easy bike after Section 2",
        "SECTION 3 — Burpee + wall ball density: 5 rounds of:",
        "30m burpee broad jumps",
        "25 wall balls (competition ball if technique allows; otherwise one size lighter)",
        "60s rest between rounds",
        "Intensity cap: RPE ≤8 on any round; if wall balls break >2 times in a set, reduce to 20 reps for remaining rounds",
        "Technical standard: soft BBJ landings; wall ball full depth + target height every rep",
      ],
      cooldown: ["6–8 min easy bike", "Hip flexors + calves 2 min"],
      targetLoad: "Sled submaximal; wall ball competition standard when unbroken quality holds",
      targetRPE: "7–8",
      whatToRecord: [
        "Sled load",
        "Pull/push bouts completed",
        "Section 3 round times",
        "Wall ball break pattern",
        "Session RPE",
      ],
      coachNote:
        "Coach-brief core volume builder. Fixed rest and stop rules keep this below race simulation.",
      safetyNote: "Do not pair with threshold run or heavy legs same day.",
      progression: "Add 1 Section 3 round or trim Section 3 rest to 45s only if all rounds stay ≤RPE 8.",
      regression: "Use Sled Capacity Builder; or Section 3 as 3 rounds of 20m BBJ + 20 wall balls.",
    },
  }),

  // ——— 3. Station Density Builder ———
  volumeBuilder({
    id: "vb-station-density-l1",
    sessionLibraryId: "hyrox_vb_station_density_l1",
    name: "Station Density Builder",
    subcategory: "mixed_station_builders · density",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 400,
    equipmentRequired: ["Wall ball", "Sled", "Open floor ≥20m"],
    bestFor: ["station_capacity_block", "density_block", "pairs_with_threshold"],
    avoidIf: ["poor_recovery_state", "race_week"],
    tags: ["mixed", "density", "wall_ball", "sled", "burpee", "pairs_with_threshold"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-station-pyramid-l1",
    recommendedRegression: "4 rounds · 15 wall balls · skip BBJ",
    editableVariables: ["rounds", "wallBallReps", "restSeconds"],
    programmingStandards: standards({
      purpose: "Raise station density with fixed short recoveries while protecting technique.",
      primaryAdaptation: "station_density",
      secondaryAdaptation: "transition_efficiency",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Sled", "Open floor ≥20m"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Station Pyramid",
      recommendedRegression: "4 rounds · reduced reps",
      suggestedSessionPlacement: ["midweek_station_day", "pairs_well_with_threshold"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Round times", "Wall ball breaks", "Session RPE"],
    }),
    prescription: {
      objective: "5 quality density rounds at RPE 6–7 — no race transitions.",
      warmup: [
        "5 min easy erg",
        "10 wall balls + 15m light sled push + 6 burpee broad jumps",
      ],
      mainSet: [
        "5 rounds:",
        "20 wall balls",
        "20m sled push (submaximal load)",
        "10 burpee broad jumps",
        "75s easy walk rest between rounds",
        "Stop rule: if any movement form fails mid-round, finish the round easier and drop 2 wall balls next round",
      ],
      cooldown: ["5 min easy bike", "Calves + hips 2 min"],
      targetRPE: "6–7",
      targetLoad: "Sled submaximal; competition wall ball if unbroken sets hold",
      whatToRecord: ["Each round time", "Wall ball breaks", "Session RPE"],
      coachNote: "Density via fixed rest — do not chase round PRs.",
      progression: "Progress to Station Pyramid (changing set lengths).",
      regression: "4 rounds · 15 wall balls · omit BBJ.",
    },
  }),

  // ——— 4. Wall Ball Density ———
  volumeBuilder({
    id: "vb-wallball-density-l1",
    sessionLibraryId: "hyrox_vb_wallball_density_l1",
    name: "Wall Ball Density",
    subcategory: "wall_ball_builders · density",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 220,
    equipmentRequired: ["Wall ball", "Target at competition height"],
    bestFor: ["wall_ball_weakness", "station_capacity_block", "limiter_wall_ball"],
    avoidIf: ["shoulder_irritation", "high_doms_quads"],
    tags: ["wall_ball", "wall_ball_builders", "limiter_wall_ball"],
    progressionFamily: "wall_ball_density_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-wallball-fatigue-l1",
    recommendedRegression: "EMOM 10 × 8 reps · lighter ball on max sets",
    editableVariables: ["emomMinutes", "emomReps", "maxSetTarget"],
    programmingStandards: standards({
      purpose: "Increase wall ball set length and breathing rhythm under control.",
      primaryAdaptation: "wall_ball_density",
      secondaryAdaptation: "breathing_under_fatigue",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Target at competition height"],
      progressionFamily: "wall_ball_density_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Wall Ball Under Fatigue",
      recommendedRegression: "Shorter EMOM · lighter ball",
      suggestedSessionPlacement: ["upper_or_station_day", "not_after_heavy_legs"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "heavy_squat_day"],
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Largest unbroken set", "Total reps", "Session RPE"],
    }),
    prescription: {
      objective: "Build wall ball density with EMOM structure then capped max sets — no failure chasing.",
      warmup: ["2 min jump rope or easy bike", "2×10 light wall balls", "Ankle + shoulder openers"],
      mainSet: [
        "SECTION A — EMOM 12: 10 wall balls each minute (must leave ≥15s buffer)",
        "If you miss the buffer twice, drop to 8 reps for remaining minutes",
        "Transition: 2 min easy walk",
        "SECTION B — 3 sets: target 25 unbroken wall balls · 2 min rest between sets",
        "Stop each set at first technical break or at 25 — whichever comes first",
        "Technical standard: full squat depth, ball to target height, soft catch every rep",
      ],
      cooldown: ["Easy walk 3 min", "Hip flexors 2 min"],
      targetLoad: "Competition ball when Section A stays unbroken; otherwise one size lighter",
      targetRPE: "6–7",
      whatToRecord: ["EMOM reps held", "Largest unbroken set", "Total reps", "Session RPE"],
      coachNote: "Density first. Do not take sets to failure.",
      progression: "Wall Ball Under Fatigue (same skill under aerobic pre-fatigue).",
      regression: "EMOM 10 × 8 · Section B target 15–20.",
    },
  }),

  // ——— 5. Wall Ball Under Fatigue ———
  volumeBuilder({
    id: "vb-wallball-fatigue-l1",
    sessionLibraryId: "hyrox_vb_wallball_fatigue_l1",
    name: "Wall Ball Under Fatigue",
    subcategory: "wall_ball_builders · under_fatigue",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Wall balls after controlled aerobic pre-fatigue",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    bikeMinutes: 16,
    stationVolume: 140,
    equipmentRequired: ["Bike or row", "Wall ball"],
    bestFor: ["wall_ball_weakness", "specific_block", "limiter_wall_ball"],
    avoidIf: ["beginner_as_written", "race_week", "deload_week_full_volume"],
    tags: ["wall_ball", "under_fatigue", "limiter_wall_ball"],
    progressionFamily: "wall_ball_density_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-continuous-station-l1",
    recommendedRegression: "vb-wallball-density-l1",
    editableVariables: ["preFatigueMinutes", "wallBallReps", "rounds"],
    programmingStandards: standards({
      purpose: "Hold wall ball standards after controlled aerobic fatigue — still a builder.",
      primaryAdaptation: "wall_ball_under_fatigue",
      secondaryAdaptation: "aerobic_support",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "high",
      equipmentRequired: ["Bike or row", "Wall ball"],
      progressionFamily: "wall_ball_density_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Continuous Station Builder",
      recommendedRegression: "Wall Ball Density",
      suggestedSessionPlacement: ["hard_station_day", "not_adjacent_threshold"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "threshold_run"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Pre-fatigue modality", "WB unbroken lengths", "Session RPE"],
    }),
    prescription: {
      objective: "4 controlled rounds of Z2 bike then quality wall balls — bike stays conversational.",
      warmup: ["5 min easy bike", "2×10 wall balls"],
      mainSet: [
        "4 rounds:",
        "4 min bike @ Z2 / conversational (RPE ≤5)",
        "Immediately: 35 wall balls unbroken if possible",
        "If broken, take ≤2 short breaks; do not sit down",
        "90s easy walk rest after wall balls",
        "Stop rule: if wall ball form collapses (depth/target), end the set and reduce next round to 25",
      ],
      cooldown: ["5 min easy bike", "Quads + shoulders 2 min"],
      targetRPE: "7–8",
      whatToRecord: ["WB set lengths", "Round RPE", "Session RPE"],
      coachNote: "Do not raise bike intensity to 'make it harder'.",
      progression: "Continuous Station Builder when ready for multi-station continuous work.",
      regression: "Wall Ball Density (fresh).",
    },
  }),

  // ——— 6. Burpee Economy ———
  volumeBuilder({
    id: "vb-burpee-economy-l1",
    sessionLibraryId: "hyrox_vb_burpee_economy_l1",
    name: "Burpee Economy",
    subcategory: "burpee_builders · economy",
    level: "intermediate",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "technical_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 84,
    equipmentRequired: ["Open floor"],
    bestFor: ["burpee_weakness", "base_block", "technical_day", "limiter_burpee"],
    avoidIf: ["wrist_shoulder_irritation"],
    tags: ["burpee", "burpee_builders", "technical_builder", "limiter_burpee"],
    progressionFamily: "burpee_economy_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-burpee-density-l1",
    recommendedRegression: "6×6 step-back burpees · 75s rest",
    editableVariables: ["sets", "reps", "restSeconds"],
    programmingStandards: standards({
      purpose: "Improve burpee rhythm and economy at a fixed sustainable cadence.",
      primaryAdaptation: "burpee_economy",
      secondaryAdaptation: "pacing_awareness",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "moderate",
      technicalDemand: "high",
      equipmentRequired: ["Open floor"],
      progressionFamily: "burpee_economy_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Burpee Density",
      recommendedRegression: "Fewer sets · step-back pattern",
      suggestedSessionPlacement: ["technique_day", "easy_adjacent", "deload"],
      adjacencyWarnings: ["heavy_push_day", "race_simulation"],
      expectedRpe: "5–6",
      recommendedLoggingFields: ["Cadence notes", "Form cues", "Session RPE"],
    }),
    prescription: {
      objective: "8×8 burpees at smooth cadence — technical builder, not a sprint.",
      warmup: ["World's greatest stretch ×5/side", "10 slow burpees focusing on soft landings"],
      mainSet: [
        "8 sets × 8 chest-to-floor burpees",
        "60s walk rest between sets",
        "Cadence target: ~3 seconds/rep (smooth, not rushed)",
        "Cue: soft landing · quick feet · relaxed shoulders · full hip extension",
        "Finisher: 2×20 step-back burpees easy · 60s rest (optional if RPE still ≤6)",
      ],
      cooldown: ["2 min breathing reset", "Hip mobility 2 min"],
      targetRPE: "5–6",
      whatToRecord: ["Cadence feel", "Technique notes", "Session RPE"],
      coachNote: "Speed is not the goal. If breathing spikes, slow the cadence.",
      progression: "Burpee Density (EMOM structure).",
      regression: "6×6 step-back burpees · 75s rest.",
    },
  }),

  // ——— 7. Burpee Density ———
  volumeBuilder({
    id: "vb-burpee-density-l1",
    sessionLibraryId: "hyrox_vb_burpee_density_l1",
    name: "Burpee Density",
    subcategory: "burpee_builders · density",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 157,
    equipmentRequired: ["Open floor ≥20m"],
    bestFor: ["burpee_weakness", "station_capacity_block", "limiter_burpee"],
    avoidIf: ["poor_recovery_state"],
    tags: ["burpee", "density", "limiter_burpee"],
    progressionFamily: "burpee_economy_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-alternating-station-l1",
    recommendedRegression: "vb-burpee-economy-l1",
    editableVariables: ["emomMinutes", "emomReps", "bbjReps"],
    programmingStandards: standards({
      purpose: "Raise sustainable burpee density with clock structure and a fixed BBJ finisher.",
      primaryAdaptation: "burpee_density",
      secondaryAdaptation: "fatigue_resistance",
      trainingPhase: ["build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Open floor ≥20m"],
      progressionFamily: "burpee_economy_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Alternating Station Builder",
      recommendedRegression: "Burpee Economy",
      suggestedSessionPlacement: ["station_day", "pairs_with_easy_aerobic"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["EMOM reps held", "BBJ quality", "Session RPE"],
    }),
    prescription: {
      objective: "EMOM burpees with buffer, then fixed BBJ sets — miss the minute = drop reps, never sprint catch-up.",
      warmup: ["5 min easy jog or bike", "2×6 burpees + 10m BBJ feel"],
      mainSet: [
        "SECTION A — EMOM 14: 8 burpees each minute (leave ≥12s buffer)",
        "If buffer missed twice, drop to 6 burpees for remaining minutes",
        "Transition: 2 min easy walk",
        "SECTION B — 3×15 burpee broad jumps · 90s rest between sets",
        "Technical standard: soft landings, hips fully open, no flopping chest",
      ],
      cooldown: ["Easy walk 3 min", "Shoulder openers"],
      targetRPE: "6–7",
      whatToRecord: ["EMOM reps", "BBJ set quality", "Session RPE"],
      coachNote: "Clock discipline over total volume.",
      progression: "Alternating Station Builder pairing burpees with a limiter station.",
      regression: "Burpee Economy.",
    },
  }),

  // ——— 8. Lunge Durability ———
  volumeBuilder({
    id: "vb-lunge-durability-l1",
    sessionLibraryId: "hyrox_vb_lunge_durability_l1",
    name: "Lunge Durability",
    subcategory: "lunge_builders · durability",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    strengthMinutes: 30,
    stationVolume: 240,
    equipmentRequired: ["Open floor ≥40m", "Optional dumbbells 2×"],
    bestFor: ["lunge_weakness", "single_leg_block", "limiter_lunge"],
    avoidIf: ["acute_knee_irritation", "high_doms_quads"],
    tags: ["lunge", "lunge_builders", "single_leg", "limiter_lunge"],
    progressionFamily: "lunge_durability_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-heavy-station-l1",
    recommendedRegression: "3×30m bodyweight only · 90s rest",
    editableVariables: ["distanceM", "loadKg", "sets"],
    programmingStandards: standards({
      purpose: "Build walking lunge durability and single-leg control for race stations.",
      primaryAdaptation: "lunge_durability",
      secondaryAdaptation: "single_leg_stability",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Open floor ≥40m", "Optional dumbbells"],
      progressionFamily: "lunge_durability_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Heavy Station Builder",
      recommendedRegression: "Shorter bodyweight lunges",
      suggestedSessionPlacement: ["strength_endurance_day", "not_day_before_threshold"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "threshold_run"],
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Distance", "Load", "Knee notes", "Session RPE"],
    }),
    prescription: {
      objective: "Accumulate 200m walking lunges + tempo reverse lunges with upright posture.",
      warmup: ["Glute bridge 2×12", "2×20m bodyweight walking lunges"],
      mainSet: [
        "SECTION A — 5×40m walking lunges · 75s rest between sets",
        "Load: bodyweight or light DBs (≤20% bodyweight total) — unbroken 40m required",
        "Technical standard: upright torso, front knee tracks toes, back knee soft touch",
        "Transition: 2 min easy walk",
        "SECTION B — 2×12 reverse lunges/leg @ 3-1-1 tempo · 90s rest between sets",
        "Stop rule: sharp knee pain = end session; mild fatigue burn is expected",
      ],
      cooldown: ["Easy bike 4 min", "Quad stretch 90s/side"],
      targetRPE: "6–7",
      whatToRecord: ["Load used", "Distance completed", "Symmetry notes", "Session RPE"],
      coachNote: "Protect threshold day — manage DOMS deliberately.",
      progression: "Heavy Station Builder (heavier sled/carry emphasis).",
      regression: "3×30m bodyweight · 90s rest · skip Section B.",
    },
  }),

  // ——— 9. Carry Capacity ———
  volumeBuilder({
    id: "vb-carry-capacity-l1",
    sessionLibraryId: "hyrox_vb_carry_capacity_l1",
    name: "Carry Capacity",
    subcategory: "carry_builders · capacity",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    strengthMinutes: 30,
    stationVolume: 330,
    equipmentRequired: ["Dumbbells or kettlebells", "Open floor ≥40m"],
    bestFor: ["carry_weakness", "grip_support", "limiter_carry", "limiter_grip"],
    avoidIf: ["acute_grip_injury"],
    tags: ["carry", "carry_builders", "grip", "limiter_carry", "limiter_grip"],
    progressionFamily: "carry_capacity_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-grip-builder-l1",
    recommendedRegression: "4×30m farmers · lighter pair",
    editableVariables: ["distanceM", "loadKg", "rounds"],
    programmingStandards: standards({
      purpose: "Build farmers carry capacity and posture under fixed distances.",
      primaryAdaptation: "carry_capacity",
      secondaryAdaptation: "grip_endurance",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "low",
      equipmentRequired: ["Dumbbells or kettlebells", "Open floor ≥40m"],
      progressionFamily: "carry_capacity_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Grip Builder",
      recommendedRegression: "Shorter / lighter carries",
      suggestedSessionPlacement: ["upper_grip_day", "pairs_with_easy_run"],
      adjacencyWarnings: ["max_deadlift_day"],
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Load", "Drops", "Distance", "Session RPE"],
    }),
    prescription: {
      objective: "6×40m farmers + 3×30m suitcase carries — tall posture, quiet feet, minimal drops.",
      warmup: ["Dead hang 2×20s", "2×20m light farmers feel"],
      mainSet: [
        "SECTION A — 6×40m farmers carry · 75s rest between sets",
        "Load: challenging but planned unbroken 40m (if you drop, rest remaining time and continue)",
        "Technical standard: ribs stacked, eyes forward, no leaning",
        "Transition: 2 min easy walk",
        "SECTION B — 3×30m suitcase carry each side · 60s rest between sides/sets",
        "Same load family as farmers or one notch lighter",
      ],
      cooldown: ["Forearm stretch 2 min", "Easy walk 2 min"],
      targetRPE: "6–7",
      whatToRecord: ["Load", "Number of drops", "Session RPE"],
      coachNote: "If grip fails before 30m twice, drop load one notch immediately.",
      progression: "Grip Builder (hangs + carries).",
      regression: "4×30m farmers · lighter pair · skip suitcase.",
    },
  }),

  // ——— 10. Mixed Station Flow ———
  volumeBuilder({
    id: "vb-mixed-station-flow-l1",
    sessionLibraryId: "hyrox_vb_mixed_station_flow_l1",
    name: "Mixed Station Flow",
    subcategory: "mixed_station_builders · flow",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 400,
    equipmentRequired: ["Wall ball", "Sled", "Dumbbells", "Open floor ≥20m"],
    bestFor: ["general_hyrox_build", "transition_practice", "pairs_with_threshold"],
    avoidIf: ["race_week"],
    tags: ["mixed", "flow", "pairs_with_threshold"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-station-density-l1",
    recommendedRegression: "3 flows · drop burpees",
    editableVariables: ["rounds", "restSeconds"],
    programmingStandards: standards({
      purpose: "Practise multi-station flow and efficient transitions at builder effort.",
      primaryAdaptation: "station_flow_efficiency",
      secondaryAdaptation: "aerobic_support",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Sled", "Dumbbells", "Open floor ≥20m"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Station Density Builder",
      recommendedRegression: "Fewer flows",
      suggestedSessionPlacement: ["hyrox_volume_day", "pairs_well_with_threshold"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Flow times", "Sticky transitions", "Session RPE"],
    }),
    prescription: {
      objective: "5 continuous station flows with fixed rest — transitions matter more than speed.",
      warmup: ["5 min easy erg", "1 rehearsal flow at 50% effort"],
      mainSet: [
        "5 flows:",
        "20 wall balls → 20m sled push → 20m farmers carry → 10 burpees",
        "120s easy walk rest between flows",
        "Intensity cap: each flow RPE ≤7; do not sprint transitions",
        "Technical standard: set implements deliberately; no chaotic bouncing between stations",
      ],
      cooldown: ["Easy bike 5 min", "Hips + grip 2 min"],
      targetRPE: "6–7",
      whatToRecord: ["Each flow time", "Sticky station", "Session RPE"],
      coachNote: "Builder flow. Transition quality is the coaching focus.",
      progression: "Station Density Builder (shorter rest, denser rounds).",
      regression: "3 flows · omit burpees.",
    },
  }),

  // ——— 11. Mixed Erg Flow ———
  volumeBuilder({
    id: "vb-mixed-erg-flow-l1",
    sessionLibraryId: "hyrox_vb_mixed_erg_flow_l1",
    name: "Mixed Erg Flow",
    subcategory: "erg_flow_builders · mixed",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "aerobic_builder",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    sessionStress: "moderate",
    ergMinutes: 40,
    equipmentRequired: ["SkiErg", "RowErg"],
    bestFor: ["aerobic_support", "low_impact_day", "pairs_with_threshold"],
    avoidIf: [],
    tags: ["erg", "erg_flow_builders", "ski", "row", "pairs_with_threshold"],
    progressionFamily: "erg_flow_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-aerobic-station-l1",
    recommendedRegression: "3 rounds · 4 min blocks",
    editableVariables: ["blockMinutes", "rounds"],
    programmingStandards: standards({
      purpose: "Build mixed-erg aerobic flow that supports stations without run impact.",
      primaryAdaptation: "mixed_erg_aerobic",
      secondaryAdaptation: "modality_transitions",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "low",
      technicalDemand: "low",
      equipmentRequired: ["SkiErg", "RowErg"],
      progressionFamily: "erg_flow_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Aerobic Station Builder",
      recommendedRegression: "Shorter blocks",
      suggestedSessionPlacement: ["easy_adjacent", "recovery_support", "pairs_well_with_threshold"],
      adjacencyWarnings: ["hard_threshold_erg_day"],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Splits", "Session RPE", "Modality order"],
    }),
    prescription: {
      objective: "4×(5 min Ski + 5 min Row) at Z1–low Z2 — if HR drifts to threshold, slow down.",
      warmup: ["3 min easy Ski", "3 min easy Row"],
      mainSet: [
        "4 rounds continuous:",
        "5 min Ski @ Z1–low Z2 (RPE 4–5)",
        "5 min Row @ Z1–low Z2 (RPE 4–5)",
        "No rest between modalities or rounds unless form collapses — then 60s easy and resume",
        "Total work: 40 min",
      ],
      cooldown: ["2 min easy Ski", "2 min easy Row"],
      targetHR: "Z1–low Z2",
      targetRPE: "4–5",
      whatToRecord: ["Average splits", "Session RPE"],
      coachNote: "True builder aerobic — not sneaky threshold.",
      progression: "Aerobic Station Builder (erg + light stations).",
      regression: "3 rounds · 4 min blocks.",
    },
  }),

  // ——— 12. Technical Builder ———
  volumeBuilder({
    id: "vb-technical-builder-l1",
    sessionLibraryId: "hyrox_vb_technical_builder_l1",
    name: "Technical Builder",
    subcategory: "mixed_station_builders · technical",
    level: "all",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "technical_builder",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    stationVolume: 60,
    equipmentRequired: ["Sled", "Wall ball", "Dumbbells", "Ski or Row optional"],
    bestFor: ["technique_focus", "return_to_train", "deload"],
    avoidIf: [],
    tags: ["technical_builder", "skill", "deload"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "deload",
    recommendedProgression: "vb-mixed-station-flow-l1",
    recommendedRegression: "Two stations only · same structure",
    editableVariables: ["stations"],
    programmingStandards: standards({
      purpose: "Low-fatigue technical rehearsal of race stations with full recoveries.",
      primaryAdaptation: "station_technique",
      secondaryAdaptation: "confidence",
      trainingPhase: ["base", "deload", "return_to_train"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "low",
      technicalDemand: "high",
      equipmentRequired: ["Sled", "Wall ball", "Dumbbells"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "deload",
      recommendedProgression: "Mixed Station Flow",
      recommendedRegression: "Two stations only",
      suggestedSessionPlacement: ["deload", "easy_day", "post_travel"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Technique notes", "Optional film", "Session RPE"],
    }),
    prescription: {
      objective: "Skill practice only — full recoveries, RPE ≤5, no density chase.",
      warmup: ["3 min easy erg", "General hip/ankle/shoulder mobility 3 min"],
      mainSet: [
        "Rotate these 5 stations × 2 quality sets each:",
        "1) Sled push 15m easy · rest 60s · repeat",
        "2) Wall balls 8 reps perfect · rest 60s · repeat",
        "3) Walking lunges 20m easy · rest 60s · repeat",
        "4) Farmers carry 20m light · rest 60s · repeat",
        "5) Ski or Row 45s easy technique · rest 60s · repeat",
        "Full recoveries — treat as coaching rehearsal",
      ],
      cooldown: ["Easy walk 3 min"],
      targetRPE: "4–5",
      whatToRecord: ["Cues that worked", "Session RPE"],
      coachNote: "Ideal deload / return-to-train session.",
      progression: "Mixed Station Flow when ready for linked volume.",
      regression: "Stations 1–2 only, same set structure.",
    },
  }),

  // ——— 13. Continuous Station Builder ———
  volumeBuilder({
    id: "vb-continuous-station-l1",
    sessionLibraryId: "hyrox_vb_continuous_station_l1",
    name: "Continuous Station Builder",
    subcategory: "mixed_station_builders · continuous",
    level: "advanced",
    durationMinutes: 50,
    hardDay: true,
    hardDayReason: "Continuous station blocks — still below race redline",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    stationVolume: 240,
    equipmentRequired: ["Wall ball", "Sled", "Dumbbells", "Open floor"],
    bestFor: ["specific_block", "advanced_station_capacity"],
    avoidIf: ["beginner_as_written", "race_week", "poor_recovery_state"],
    tags: ["continuous", "mixed"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_3",
    recommendedProgression: "vb-long-station-l1",
    recommendedRegression: "vb-station-density-l1",
    editableVariables: ["blockMinutes", "blocks"],
    programmingStandards: standards({
      purpose: "Continuous multi-station builder for advanced athletes — not race simulation.",
      primaryAdaptation: "continuous_station_capacity",
      secondaryAdaptation: "fatigue_management",
      trainingPhase: ["specific"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "high",
      technicalDemand: "high",
      equipmentRequired: ["Wall ball", "Sled", "Dumbbells", "Open floor"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_3",
      recommendedProgression: "Long Station Builder",
      recommendedRegression: "Station Density Builder",
      suggestedSessionPlacement: ["key_station_day"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "threshold_run", "heavy_leg_strength"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Blocks completed", "Limiting station", "Session RPE"],
    }),
    prescription: {
      objective: "3×8 min continuous station rotation @ RPE 7–8 with fixed recoveries.",
      warmup: ["8 min easy mixed erg", "1 min each: wall ball, light sled, carry, burpee feel"],
      mainSet: [
        "3 blocks × 8 min continuous rotation:",
        "Cycle in order as needed: 15 wall balls → 15m sled push → 15m farmers → 8 burpees → repeat",
        "Stay moving for the full 8 min; planned mini-breaks ≤10s only",
        "2 min 30s easy walk rest between blocks",
        "Intensity cap: leave one gear in reserve — this is not a race rehearsal",
        "Stop rule: if movement quality collapses, walk 20s then resume lighter",
      ],
      cooldown: ["Easy bike 6–8 min"],
      targetRPE: "7–8",
      whatToRecord: ["Blocks completed", "Limiting station", "Session RPE"],
      coachNote: "Advanced builder. Protect key runs the following day.",
      progression: "Long Station Builder (longer total work).",
      regression: "Station Density Builder.",
    },
  }),

  // ——— 14. Long Station Builder ———
  volumeBuilder({
    id: "vb-long-station-l1",
    sessionLibraryId: "hyrox_vb_long_station_l1",
    name: "Long Station Builder",
    subcategory: "mixed_station_builders · long",
    level: "advanced",
    durationMinutes: 60,
    hardDay: true,
    hardDayReason: "Long station volume tolerance",
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    stationVolume: 300,
    equipmentRequired: ["Full station access", "One erg"],
    bestFor: ["specific_block", "volume_tolerance"],
    avoidIf: ["beginner_as_written", "race_week", "deload_week_full_volume"],
    tags: ["long", "volume"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "advanced",
    recommendedProgression: "Maintain quality; do not add race simulation same week",
    recommendedRegression: "vb-continuous-station-l1",
    editableVariables: ["totalWorkMinutes"],
    programmingStandards: standards({
      purpose: "Longer station volume tolerance with even pacing and planned breaks.",
      primaryAdaptation: "station_volume_tolerance",
      secondaryAdaptation: "pacing_discipline",
      trainingPhase: ["specific", "peak"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 60,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Full station access", "One erg"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "advanced",
      recommendedProgression: "Hold volume; improve evenness",
      recommendedRegression: "Continuous Station Builder",
      suggestedSessionPlacement: ["peak_volume_week_mid"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "threshold_run", "long_run"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Work blocks completed", "Break strategy", "Session RPE"],
    }),
    prescription: {
      objective: "7×5 min station work blocks (35 min total work) with 75s easy between — finish trainable tomorrow.",
      warmup: ["10 min easy aerobic", "Station priming 4 min"],
      mainSet: [
        "7 blocks × 5 min work @ builder effort (RPE 7–8):",
        "Block menu (rotate across session): wall balls, sled push/pull, lunges, farmers, burpees, 3 min easy erg",
        "75s easy walk rest between blocks",
        "Even pacing — last block ≈ first block effort",
        "Never all-out; stop rule if you cannot speak short phrases during rest",
      ],
      cooldown: ["Easy flush 8 min", "Mobility 3 min"],
      targetRPE: "7–8",
      whatToRecord: ["Blocks completed", "Break strategy", "Session RPE"],
      coachNote: "Peak volume tool. Guard recovery for key runs.",
      progression: "Improve evenness / reduce unplanned breaks — do not add a race sim same week.",
      regression: "Continuous Station Builder (3×8 min).",
    },
  }),

  // ——— 15. Station Pyramid ———
  volumeBuilder({
    id: "vb-station-pyramid-l1",
    sessionLibraryId: "hyrox_vb_station_pyramid_l1",
    name: "Station Pyramid",
    subcategory: "mixed_station_builders · pyramid",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 200,
    equipmentRequired: ["Wall ball", "Dumbbells", "Open floor ≥20m"],
    bestFor: ["station_capacity_block", "pacing_practice"],
    avoidIf: [],
    tags: ["pyramid", "wall_ball", "mixed"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-station-emom-l1",
    recommendedRegression: "vb-station-density-l1",
    editableVariables: ["repScheme"],
    programmingStandards: standards({
      purpose: "Pyramid station volume to teach pacing across changing set lengths.",
      primaryAdaptation: "station_pacing",
      secondaryAdaptation: "density",
      trainingPhase: ["build"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Dumbbells", "Open floor ≥20m"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Station EMOM",
      recommendedRegression: "Station Density Builder",
      suggestedSessionPlacement: ["midweek_station_day"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Scheme completed", "Breaks on peak set", "Session RPE"],
    }),
    prescription: {
      objective: "Complete wall ball pyramid 10-15-20-15-10 with fixed carry + burpee between ladder steps.",
      warmup: ["5 min easy erg", "2×8 wall balls + 20m light farmers"],
      mainSet: [
        "Wall ball pyramid: 10 → 15 → 20 → 15 → 10",
        "After every ladder step:",
        "20m farmers carry + 6 burpees",
        "Then 75s easy rest before the next ladder step",
        "Do not smash the peak 20 — target even breathing and ≤1 planned break on the 20",
      ],
      cooldown: ["Easy walk 3 min", "Shoulders 2 min"],
      targetRPE: "6–7",
      whatToRecord: ["Breaks on 20", "Session RPE"],
      coachNote: "Smooth ladder — peak set is controlled, not a max effort.",
      progression: "Station EMOM (clock density).",
      regression: "Station Density Builder; or pyramid 10-15-15-10 only.",
    },
  }),

  // ——— 16. Station EMOM ———
  volumeBuilder({
    id: "vb-station-emom-l1",
    sessionLibraryId: "hyrox_vb_station_emom_l1",
    name: "Station EMOM",
    subcategory: "mixed_station_builders · emom",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 180,
    equipmentRequired: ["Wall ball", "Dumbbells", "Open floor ≥20m"],
    bestFor: ["density_block", "time_efficient"],
    avoidIf: [],
    tags: ["emom", "mixed", "wall_ball"],
    progressionFamily: "station_emom_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-alternating-station-l1",
    recommendedRegression: "EMOM 12 · 8 wall balls / 6 burpees",
    editableVariables: ["minutes", "reps"],
    programmingStandards: standards({
      purpose: "Clock-driven station volume with predictable density and buffer rules.",
      primaryAdaptation: "station_density",
      secondaryAdaptation: "work_capacity",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 40,
      estimatedFatigueCost: "moderate",
      technicalDemand: "low",
      equipmentRequired: ["Wall ball", "Dumbbells", "Open floor ≥20m"],
      progressionFamily: "station_emom_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Alternating Station Builder",
      recommendedRegression: "Shorter EMOM",
      suggestedSessionPlacement: ["time_efficient_station_day"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Minutes completed", "Missed buffers", "Session RPE"],
    }),
    prescription: {
      objective: "EMOM 18 alternating wall balls and farmers/burpees — leave buffer most minutes.",
      warmup: ["Easy erg 4 min", "8 wall balls + 20m light farmers"],
      mainSet: [
        "EMOM 18 alternating:",
        "Odd minutes: 12 wall balls",
        "Even minutes: 20m farmers carry OR 8 burpees (choose one for the whole session)",
        "Must leave ≥10s buffer; if missed twice, drop wall balls to 10 / burpees to 6",
      ],
      cooldown: ["Easy flush 4 min"],
      targetRPE: "6–7",
      whatToRecord: ["Reps held", "Missed minutes", "Session RPE"],
      coachNote: "Missed minute = drop reps next time, not sprint catch-up.",
      progression: "Alternating Station Builder (longer paired rounds).",
      regression: "EMOM 12 with reduced reps.",
    },
  }),

  // ——— 17. Alternating Station Builder ———
  volumeBuilder({
    id: "vb-alternating-station-l1",
    sessionLibraryId: "hyrox_vb_alternating_station_l1",
    name: "Alternating Station Builder",
    subcategory: "mixed_station_builders · alternating",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 280,
    equipmentRequired: ["Two primary stations (see pairs)"],
    bestFor: ["limiter_focus", "pairs_with_threshold"],
    avoidIf: [],
    tags: ["alternating", "pairs_with_threshold", "limiter_focus"],
    progressionFamily: "mixed_station_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-station-density-l1",
    recommendedRegression: "5 rounds of one station only",
    editableVariables: ["pair", "rounds"],
    programmingStandards: standards({
      purpose: "Alternate two limiter stations to raise repeatability without full mixed chaos.",
      primaryAdaptation: "paired_station_repeatability",
      secondaryAdaptation: "local_endurance",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Two primary stations"],
      progressionFamily: "mixed_station_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Station Density Builder",
      recommendedRegression: "Single station work",
      suggestedSessionPlacement: ["limiter_focus_day", "pairs_well_with_threshold"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Pair used", "Round times", "Session RPE"],
    }),
    prescription: {
      objective: "7 rounds of a fixed two-station pair with matched effort and 75s rest.",
      warmup: ["5 min easy", "2 rehearsal pairs at 50%"],
      mainSet: [
        "Choose ONE pair for the session:",
        "Pair A: 20 wall balls + 20m farmers carry",
        "Pair B: 20m sled push + 20m walking lunges",
        "Pair C: 10 burpees + 45s Ski @ easy-steady",
        "7 rounds of the chosen pair · 75s easy rest between rounds",
        "Keep round 7 within 10% of round 1 time",
      ],
      cooldown: ["Easy aerobic 5 min"],
      targetRPE: "6–7",
      whatToRecord: ["Pair", "Fastest/slowest round", "Session RPE"],
      coachNote: "Ideal when testing week flagged a clear station limiter.",
      progression: "Station Density Builder (three-movement density).",
      regression: "5 rounds · or single-station density only.",
    },
  }),

  // ——— 18. Heavy Station Builder ———
  volumeBuilder({
    id: "vb-heavy-station-l1",
    sessionLibraryId: "hyrox_vb_heavy_station_l1",
    name: "Heavy Station Builder",
    subcategory: "mixed_station_builders · heavy",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Heavier station loading — controlled sets only",
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "high",
    stationStress: "moderate",
    sessionStress: "high",
    strengthMinutes: 35,
    stationVolume: 280,
    equipmentRequired: ["Sled", "Heavy DBs/KBs", "Optional sandbag"],
    bestFor: ["strength_support", "sled_carry_block", "limiter_sled"],
    avoidIf: ["beginner_as_written", "high_doms_state", "race_week"],
    tags: ["heavy", "sled", "carry", "limiter_sled"],
    progressionFamily: "sled_capacity_builder",
    progressionLevel: "advanced",
    recommendedProgression: "Maintain; do not stack with heavy legs same week day",
    recommendedRegression: "vb-sled-capacity-l1",
    editableVariables: ["load", "distanceM", "sets"],
    programmingStandards: standards({
      purpose: "Heavier station loading for strength-endurance transfer — still controlled sets.",
      primaryAdaptation: "heavy_station_strength_endurance",
      secondaryAdaptation: "postural_strength",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["Sled", "Heavy DBs/KBs", "Optional sandbag"],
      progressionFamily: "sled_capacity_builder",
      progressionLevel: "advanced",
      recommendedProgression: "Hold load quality",
      recommendedRegression: "Sled Capacity Builder",
      suggestedSessionPlacement: ["strength_station_day"],
      adjacencyWarnings: [...BUILDER_ADJACENCY, "lower_strength_max"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Loads", "Distances", "Unbroken success", "Session RPE"],
    }),
    prescription: {
      objective: "Heavy but crisp sled and carry sets for 30–40m — stop before grind city.",
      warmup: ["5 min easy bike", "Build-up: 2×15m medium sled push + 2×15m medium pull"],
      mainSet: [
        "SECTION A — 5×30m heavy sled push · 2 min rest between reps",
        "Load: hardest load you can complete unbroken with quality (not a 10m max test)",
        "Transition: 2 min easy walk",
        "SECTION B — 4×30m heavy farmers · 90s rest between sets",
        "Optional SECTION C — 3×20m sandbag bear-hug carry · 90s rest",
        "Stop rule: if a bout requires a mid-distance stop, drop load for remaining bouts",
      ],
      cooldown: ["Easy bike 5 min", "Hips 2 min"],
      targetRPE: "7–8",
      whatToRecord: ["Loads", "Unbroken success Y/N", "Session RPE"],
      coachNote: "Space ~48h from lower max strength when possible.",
      progression: "Small load bumps only if all bouts unbroken.",
      regression: "Sled Capacity Builder loads and volumes.",
    },
  }),

  // ——— 19. Aerobic Station Builder ———
  volumeBuilder({
    id: "vb-aerobic-station-l1",
    sessionLibraryId: "hyrox_vb_aerobic_station_l1",
    name: "Aerobic Station Builder",
    subcategory: "mixed_station_builders · aerobic",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: false,
    intensityType: "aerobic_builder",
    impactType: "mixed",
    muscularStress: "low",
    stationStress: "low",
    sessionStress: "moderate",
    ergMinutes: 30,
    stationVolume: 90,
    equipmentRequired: ["Erg", "Wall ball", "Dumbbells", "Open floor"],
    bestFor: ["base_block", "aerobic_support", "pairs_with_threshold"],
    avoidIf: [],
    tags: ["aerobic", "pairs_with_threshold"],
    progressionFamily: "erg_flow_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-station-tempo-l1",
    recommendedRegression: "vb-mixed-erg-flow-l1",
    editableVariables: ["ergMinutes", "rounds"],
    programmingStandards: standards({
      purpose: "Blend easy aerobic erg work with light station touches.",
      primaryAdaptation: "aerobic_base_with_stations",
      secondaryAdaptation: "recovery_active",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "low",
      technicalDemand: "low",
      equipmentRequired: ["Erg", "Wall ball", "Dumbbells", "Open floor"],
      progressionFamily: "erg_flow_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Station Tempo Builder",
      recommendedRegression: "Mixed Erg Flow",
      suggestedSessionPlacement: ["easy_day", "pairs_well_with_threshold"],
      adjacencyWarnings: [],
      expectedRpe: "4–5",
      recommendedLoggingFields: ["Duration", "Session RPE"],
    }),
    prescription: {
      objective: "3 rounds of 10 min easy erg + 3 min light station circuit — stations stay technique-focused.",
      warmup: [
        "Easy erg 5 min @ Z1",
        "8 wall balls + 20m easy farmers + 20m easy lunges (rehearsal)",
      ],
      mainSet: [
        "3 rounds:",
        "10 min erg @ Z1–low Z2 (RPE 4–5)",
        "Then 3 min light circuit continuous:",
        "8 wall balls · 20m easy farmers · 20m easy lunges · repeat until 3 min ends",
        "60s easy walk between rounds",
        "Stations must stay RPE ≤5 — no density chase",
      ],
      cooldown: ["Easy 3 min"],
      targetHR: "Z1–low Z2 on erg",
      targetRPE: "4–5",
      whatToRecord: ["Session RPE", "Notes"],
      coachNote: "Pairs well beside threshold if recovery is good.",
      progression: "Station Tempo Builder.",
      regression: "Mixed Erg Flow (no stations).",
    },
  }),

  // ——— 20. Station Tempo Builder ———
  volumeBuilder({
    id: "vb-station-tempo-l1",
    sessionLibraryId: "hyrox_vb_station_tempo_l1",
    name: "Station Tempo Builder",
    subcategory: "mixed_station_builders · tempo",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "moderate",
    sessionStress: "moderate",
    stationVolume: 200,
    equipmentRequired: ["Wall ball", "Open floor", "Light sled or DBs"],
    bestFor: ["build_block", "pairs_with_threshold"],
    avoidIf: ["race_week"],
    tags: ["tempo", "pairs_with_threshold"],
    progressionFamily: "station_density_builder",
    progressionLevel: "level_2",
    recommendedProgression: "vb-station-density-l1",
    recommendedRegression: "vb-aerobic-station-l1",
    editableVariables: ["intervals", "restSeconds"],
    programmingStandards: standards({
      purpose: "Steady station tempo intervals — controlled quality above easy, below race.",
      primaryAdaptation: "station_tempo_capacity",
      secondaryAdaptation: "pacing",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "moderate",
      technicalDemand: "moderate",
      equipmentRequired: ["Wall ball", "Open floor", "Light sled or DBs"],
      progressionFamily: "station_density_builder",
      progressionLevel: "level_2",
      recommendedProgression: "Station Density Builder",
      recommendedRegression: "Aerobic Station Builder",
      suggestedSessionPlacement: ["quality_station_day", "pairs_well_with_threshold"],
      adjacencyWarnings: BUILDER_ADJACENCY,
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Interval evenness", "Session RPE"],
    }),
    prescription: {
      objective: "5×4 min station tempo @ RPE 6–7 with 90s rest — last interval ≈ first.",
      warmup: ["5–8 min easy", "2 min station priming"],
      mainSet: [
        "5 intervals × 4 min continuous station tempo:",
        "Within each 4 min cycle: 12 wall balls → 15m light sled or farmers → 6 burpees → repeat",
        "90s easy walk rest between intervals",
        "Even output rule: interval 5 within ~10% effort of interval 1",
        "Intensity cap: strong-but-controlled — not a smash",
      ],
      cooldown: ["Easy 5 min"],
      targetRPE: "6–7",
      whatToRecord: ["Evenness notes", "Session RPE"],
      coachNote: "Threshold discipline applied to stations.",
      progression: "Station Density Builder (more compact rounds).",
      regression: "Aerobic Station Builder.",
    },
  }),

  // ——— 21. Grip Builder ———
  volumeBuilder({
    id: "vb-grip-builder-l1",
    sessionLibraryId: "hyrox_vb_grip_builder_l1",
    name: "Grip Builder",
    subcategory: "carry_builders · grip",
    level: "intermediate",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "station_builder",
    impactType: "strength",
    muscularStress: "moderate",
    stationStress: "low",
    sessionStress: "moderate",
    strengthMinutes: 25,
    equipmentRequired: ["Pull-up bar", "Dumbbells/KBs"],
    bestFor: ["grip_weakness", "carry_support", "limiter_grip"],
    avoidIf: ["elbow_tendinopathy_flare"],
    tags: ["grip", "grip_station_builder", "limiter_grip"],
    progressionFamily: "grip_station_builder",
    progressionLevel: "level_1",
    recommendedProgression: "vb-carry-capacity-l1",
    recommendedRegression: "4×15–20s hangs · lighter carries",
    editableVariables: ["hangSeconds", "carryDistance"],
    programmingStandards: standards({
      purpose: "Targeted grip endurance for farmers, sled pull and hanging durability.",
      primaryAdaptation: "grip_endurance",
      secondaryAdaptation: "carry_support",
      trainingPhase: ["base", "build"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "moderate",
      technicalDemand: "low",
      equipmentRequired: ["Pull-up bar", "Dumbbells/KBs"],
      progressionFamily: "grip_station_builder",
      progressionLevel: "level_1",
      recommendedProgression: "Carry Capacity",
      recommendedRegression: "Shorter hangs · lighter carries",
      suggestedSessionPlacement: ["upper_grip_day", "after_easy_aerobic"],
      adjacencyWarnings: ["max_pull_day"],
      expectedRpe: "6–7",
      recommendedLoggingFields: ["Hang times", "Carry load", "Session RPE"],
    }),
    prescription: {
      objective: "Fixed hang and carry doses — stop short of complete grip failure on most sets.",
      warmup: ["Open/close fists 30s", "2×15s easy dead hangs"],
      mainSet: [
        "SECTION A — 5×30s dead hang · 75s rest between sets",
        "If you drop before 30s twice, switch to 5×20s",
        "Transition: 90s easy walk",
        "SECTION B — 4×30m farmers carry · 60s rest",
        "Load: unbroken 30m target",
        "Optional SECTION C — 2×20s towel or fat-grip hang easy · 60s rest (skip if elbows irritated)",
      ],
      cooldown: ["Forearm stretch 2 min", "Easy walk 2 min"],
      targetRPE: "6–7",
      whatToRecord: ["Hang times", "Drops", "Carry load", "Session RPE"],
      coachNote: "Leave 1–2 hang seconds in reserve on most sets.",
      progression: "Carry Capacity (more carry volume).",
      regression: "4×15–20s hangs · lighter 4×20m carries.",
    },
  }),
];
