/**
 * Mini compromised / diagnostic benchmarks for the coach session library.
 * Not part of Performance Testing Week — manually insertable in later training weeks.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";

const HYROX_SOURCE = "Hybrid365 library" as const;

const MINI_BENCHMARK_ADJACENCY =
  "Do not place beside hard threshold runs, heavy lower-body strength, long compromised running, race simulation or other station-overload sessions unless deliberately planned with recovery between.";

const SHARED_AVOID = [
  "beginner_as_written",
  "race_week_full_volume",
  "deload_week_full_volume",
  "poor_recovery_state",
  "high_doms_state",
  "heavy_leg_strength",
  "threshold_run",
  "race_simulation",
  "long_compromised_running",
] as const;

const SHARED_TAGS = [
  "hyrox",
  "benchmark",
  "diagnostic",
  "mini_compromised",
  "coach_manual_insert",
] as const;

export const HYROX_MINI_COMPROMISED_COACH_SESSIONS: CoachLibraryEntry[] = [
  buildCoachEntry({
    id: "hyrox-mini-run-sled-run",
    sessionLibraryId: "hyrox_mini_run_sled_run_benchmark",
    name: "Run–Sled–Run Benchmark",
    category: "testing",
    subcategory: "mini_compromised_benchmark · diagnostic",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Short compromised sled-running diagnostic",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 2.4,
    stationVolume: 100,
    equipmentRequired: ["Running space", "Sled push", "Sled pull"],
    bestFor: ["station_capacity_block", "compromised_running_block", "diagnostic_retest"],
    avoidIf: [...SHARED_AVOID],
    tags: [...SHARED_TAGS, "sled", "compromised_running"],
    source: HYROX_SOURCE,
    preferredDay: "Sat",
    avoidDayBefore: ["Thu", "Fri"],
    avoidDayAfter: ["Sun"],
    editableVariables: ["runDistanceM", "sledDistanceM", "sledLoad", "rounds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["compromised_running", "sled_capacity", "diagnostic"],
      energySystem: "mixed_threshold",
      fatigueCost: "high",
      muscleDamageRisk: "moderate_high",
      runningVolume: 2.4,
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["sled_push", "sled_pull"],
      weaknessTargets: ["sled", "compromised_running"],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID],
      bestWeekPlacement: ["mid_block_diagnostic", "secondary_hard_day"],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "threshold_run",
        "race_simulation",
        "station_overload",
      ],
      bestTrainingPhase: ["general_hyrox_build", "station_capacity_block"],
      progressionMethods: ["improve_run_consistency", "reduce_sled_pauses", "match_race_load"],
    },
    prescription: {
      objective:
        "Short Run–Sled–Run diagnostic to track sled cost on running without a full race simulation.",
      warmup: ["10–12 min easy run or bike", "Sled technique feel at light load"],
      mainSet: [
        "2–3 rounds for quality:",
        "600–800 m controlled run",
        "25–50 m sled push @ race or near-race load",
        "25–50 m sled pull @ race or near-race load",
        "600–800 m controlled run",
        "2–3 min easy recovery between rounds",
      ],
      cooldown: ["8–10 min easy", "Hip flexor + calf mobility"],
      targetRPE: "7–8",
      whatToRecord: [
        "Run splits before/after sled",
        "Sled push time",
        "Sled pull time",
        "Load and surface",
        "Pauses",
        "RPE",
      ],
      coachNote:
        "Mini diagnostic only — not a Performance Testing Week session. Keep volume controlled and avoid stacking with heavy legs or threshold running.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Match race loads before shortening recovery.",
      regression: "Reduce run distance and sled load; keep movement quality.",
    },
  }),

  buildCoachEntry({
    id: "hyrox-mini-run-burpee-run",
    sessionLibraryId: "hyrox_mini_run_burpee_run_benchmark",
    name: "Run–Burpee–Run Benchmark",
    category: "testing",
    subcategory: "mini_compromised_benchmark · diagnostic",
    level: "intermediate",
    durationMinutes: 35,
    hardDay: true,
    hardDayReason: "Burpee-compromised running diagnostic",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 2.4,
    stationVolume: 80,
    equipmentRequired: ["Running space", "Open floor for BBJ"],
    bestFor: ["compromised_running_block", "burpee_capacity", "diagnostic_retest"],
    avoidIf: [...SHARED_AVOID, "recent_high_volume_burpees"],
    tags: [...SHARED_TAGS, "burpee", "bbj", "compromised_running"],
    source: HYROX_SOURCE,
    editableVariables: ["runDistanceM", "bbjDistanceM", "rounds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["compromised_running", "burpee_durability", "diagnostic"],
      energySystem: "mixed_threshold",
      fatigueCost: "high",
      muscleDamageRisk: "moderate",
      runningVolume: 2.4,
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["burpee_broad_jump"],
      weaknessTargets: ["burpees", "compromised_running"],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID],
      bestWeekPlacement: ["mid_block_diagnostic"],
      avoidAdjacentTo: ["threshold_run", "heavy_leg_strength", "station_overload"],
      bestTrainingPhase: ["general_hyrox_build"],
      progressionMethods: ["improve_run_consistency", "reduce_bbj_pauses"],
    },
    prescription: {
      objective: "Measure how burpee broad jumps compromise subsequent running.",
      warmup: ["10 min easy aerobic", "BBJ movement prep"],
      mainSet: [
        "2–3 rounds:",
        "600–800 m controlled run",
        "20–40 m burpee broad jumps",
        "600–800 m controlled run",
        "2–3 min easy recovery between rounds",
      ],
      cooldown: ["Easy jog or bike", "Hip mobility"],
      targetRPE: "7–8",
      whatToRecord: ["Pre/post BBJ run splits", "BBJ time or rhythm", "Pauses", "RPE"],
      coachNote: "Keep as a short diagnostic. Do not auto-prescribe after Sunday simulation.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Improve consistency before increasing BBJ distance.",
      regression: "Shorter runs and 15–20 m BBJ.",
    },
  }),

  buildCoachEntry({
    id: "hyrox-mini-run-lunge-run",
    sessionLibraryId: "hyrox_mini_run_lunge_run_benchmark",
    name: "Run–Lunge–Run Benchmark",
    category: "testing",
    subcategory: "mini_compromised_benchmark · diagnostic",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Sandbag lunge-compromised running diagnostic",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 2.0,
    stationVolume: 100,
    equipmentRequired: ["Running space", "Sandbag"],
    bestFor: ["leg_endurance_block", "compromised_running_block", "diagnostic_retest"],
    avoidIf: [...SHARED_AVOID, "knee_pain", "high_quad_doms"],
    tags: [...SHARED_TAGS, "lunges", "sandbag", "compromised_running"],
    source: HYROX_SOURCE,
    editableVariables: ["runDistanceM", "lungeDistanceM", "sandbagLoad", "rounds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["compromised_running", "lunge_durability", "diagnostic"],
      energySystem: "mixed_threshold",
      fatigueCost: "high",
      muscleDamageRisk: "high",
      runningVolume: 2.0,
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["lunges"],
      weaknessTargets: ["lunges", "leg_endurance", "compromised_running"],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID, "knee_pain"],
      bestWeekPlacement: ["mid_block_diagnostic"],
      avoidAdjacentTo: ["heavy_leg_strength", "threshold_run", "wall_ball_overload"],
      bestTrainingPhase: ["leg_endurance_block", "general_hyrox_build"],
      progressionMethods: ["race_load_lunges", "reduce_breaks", "improve_run_return"],
      highLowerBodyMuscularLoad: true,
    },
    prescription: {
      objective: "Assess running return after sandbag lunges with controlled volume.",
      warmup: ["10–12 min easy", "Lunge technique without load"],
      mainSet: [
        "2 rounds:",
        "600–800 m controlled run",
        "40–50 m sandbag lunges @ race or near-race load",
        "600–800 m controlled run",
        "3 min easy recovery between rounds",
      ],
      cooldown: ["Easy aerobic", "Quad / hip flexor mobility"],
      targetRPE: "7–8",
      whatToRecord: ["Run splits", "Lunge time", "Breaks", "Load", "RPE", "Knee/hip notes"],
      coachNote: "High muscular cost — space away from heavy lower-body and hard runs.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Race load before adding a third round.",
      regression: "Shorter lunges and lighter bag.",
    },
  }),

  buildCoachEntry({
    id: "hyrox-mini-run-wallball-run",
    sessionLibraryId: "hyrox_mini_run_wallball_run_benchmark",
    name: "Run–Wall-Ball–Run Benchmark",
    category: "testing",
    subcategory: "mini_compromised_benchmark · diagnostic",
    level: "intermediate",
    durationMinutes: 35,
    hardDay: true,
    hardDayReason: "Wall-ball-compromised running diagnostic",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 2.0,
    stationVolume: 100,
    equipmentRequired: ["Running space", "Wall ball", "Target"],
    bestFor: ["station_capacity_block", "wall_ball_focus", "diagnostic_retest"],
    avoidIf: [...SHARED_AVOID, "recent_high_volume_wall_balls"],
    tags: [...SHARED_TAGS, "wall_ball", "compromised_running"],
    source: HYROX_SOURCE,
    editableVariables: ["runDistanceM", "wallBallReps", "wallBallLoad", "rounds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["compromised_running", "wall_ball_durability", "diagnostic"],
      energySystem: "mixed_threshold",
      fatigueCost: "high",
      muscleDamageRisk: "moderate_high",
      runningVolume: 2.0,
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["wall_balls"],
      weaknessTargets: ["wall_balls", "compromised_running"],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID],
      bestWeekPlacement: ["mid_block_diagnostic"],
      avoidAdjacentTo: ["heavy_leg_strength", "threshold_run", "station_overload"],
      bestTrainingPhase: ["station_capacity_block"],
      progressionMethods: ["reduce_breaks", "match_race_target", "improve_run_return"],
      highWallBallVolume: true,
    },
    prescription: {
      objective: "Track wall-ball set strategy and the cost on subsequent running.",
      warmup: ["Easy aerobic", "Wall-ball feel sets"],
      mainSet: [
        "2–3 rounds:",
        "600–800 m controlled run",
        "25–50 wall balls @ race weight/target where practical",
        "600–800 m controlled run",
        "2–3 min easy recovery",
      ],
      cooldown: ["Easy bike", "Shoulder / hip mobility"],
      targetRPE: "7–8",
      whatToRecord: [
        "Run splits",
        "Wall-ball time",
        "Set breakdown",
        "No-reps",
        "Target height",
        "RPE",
      ],
      coachNote: "Diagnostic benchmark — insert manually when useful; do not auto-chain after testing week.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Improve unbroken quality before adding reps.",
      regression: "25 reps and shorter runs.",
    },
  }),

  buildCoachEntry({
    id: "hyrox-mini-grip-carry-compromised",
    sessionLibraryId: "hyrox_mini_grip_carry_compromised_session",
    name: "Grip and Carry Compromised Session",
    category: "testing",
    subcategory: "mini_compromised_benchmark · grip_diagnostic",
    level: "intermediate",
    durationMinutes: 40,
    hardDay: true,
    hardDayReason: "Grip/carry fatigue with compromised running",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "moderate",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 1.6,
    stationVolume: 200,
    equipmentRequired: ["Farmer’s handles or DB/KB", "Running space", "Optional dead hang bar"],
    bestFor: ["grip_endurance", "carry_capacity", "diagnostic_retest"],
    avoidIf: [...SHARED_AVOID, "hand_skin_issues"],
    tags: [...SHARED_TAGS, "farmers_carry", "grip"],
    source: HYROX_SOURCE,
    editableVariables: ["runDistanceM", "carryDistanceM", "carryLoad", "deadHangSeconds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["grip_endurance", "carry_posture", "compromised_running"],
      energySystem: "mixed_aerobic",
      fatigueCost: "moderate",
      muscleDamageRisk: "moderate",
      runningVolume: 1.6,
      runIncluded: true,
      hyroxSpecificity: "high",
      raceSimulation: false,
      stationFocus: ["farmers_carry", "grip"],
      weaknessTargets: ["grip", "farmers_carry", "compromised_running"],
      suitableLevels: ["intermediate_scaled", "advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID],
      bestWeekPlacement: ["secondary_hard_day", "mid_block_diagnostic"],
      avoidAdjacentTo: ["heavy_upper_pull", "threshold_run", "station_overload"],
      bestTrainingPhase: ["general_hyrox_build", "station_capacity_block"],
      progressionMethods: ["reduce_drops", "match_race_load", "improve_posture"],
    },
    prescription: {
      objective: "Build and diagnose grip/carry durability under light running compromise.",
      warmup: ["Easy aerobic", "Carry posture drills"],
      mainSet: [
        "3 rounds:",
        "400–600 m easy-controlled run",
        "50–100 m farmer’s carry @ race or near-race load",
        "Optional: 20–40 sec dead hang between rounds",
        "2 min easy recovery",
      ],
      cooldown: ["Forearm / shoulder mobility"],
      targetRPE: "6–8",
      whatToRecord: ["Carry times", "Drops", "Load", "Grip limitation", "Run feel", "RPE"],
      coachNote: "Useful mid-block grip check. Keep away from heavy upper pulling days.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Fewer drops before increasing load.",
      regression: "Shorter carries and lighter implements.",
    },
  }),

  buildCoachEntry({
    id: "hyrox-mini-short-mixed-station",
    sessionLibraryId: "hyrox_mini_short_mixed_station_benchmark",
    name: "Short Mixed-Station Benchmark",
    category: "testing",
    subcategory: "mini_compromised_benchmark · mixed_diagnostic",
    level: "advanced",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Compressed multi-station diagnostic with short runs",
    intensityType: "compromised_benchmark",
    impactType: "mixed",
    muscularStress: "high",
    stationStress: "high",
    sessionStress: "high",
    runDistanceKm: 2.4,
    stationVolume: 220,
    equipmentRequired: [
      "Running space",
      "SkiErg or RowErg",
      "Sled",
      "Wall ball",
      "Farmer’s or sandbag",
    ],
    bestFor: ["hyrox_specificity", "mid_block_diagnostic", "race_prep_check"],
    avoidIf: [...SHARED_AVOID],
    tags: [...SHARED_TAGS, "mixed_stations", "race_specificity"],
    source: HYROX_SOURCE,
    editableVariables: ["runDistanceM", "stationSelection", "loads", "rounds"],
    hyroxMetadata: {
      primaryCategory: "testing",
      secondaryCategory: "mini_compromised_benchmark",
      sessionType: "diagnostic_benchmark",
      trainingGoals: ["race_specificity", "station_transitions", "compromised_running"],
      energySystem: "mixed_threshold",
      fatigueCost: "very_high",
      muscleDamageRisk: "high",
      runningVolume: 2.4,
      runIncluded: true,
      hyroxSpecificity: "very_high",
      raceSimulation: false,
      stationFocus: ["mixed"],
      weaknessTargets: ["station_transitions", "compromised_running"],
      suitableLevels: ["advanced", "pro"],
      notSuitableFor: [...SHARED_AVOID, "beginner_as_written"],
      bestWeekPlacement: ["mid_block_diagnostic", "late_build_check"],
      avoidAdjacentTo: [
        "heavy_leg_strength",
        "threshold_run",
        "race_simulation",
        "station_overload",
        "long_compromised_running",
      ],
      bestTrainingPhase: ["general_hyrox_build", "specific_prep"],
      progressionMethods: ["improve_transitions", "reduce_station_breaks", "hold_run_pace"],
      requiresAdvancedOrPro: true,
    },
    prescription: {
      objective:
        "Short mixed-station diagnostic that echoes race order without a full Sunday simulation.",
      warmup: ["12–15 min easy", "Station feel for chosen stations"],
      mainSet: [
        "One continuous circuit (edit stations as needed):",
        "400–600 m run",
        "500 m Ski or Row",
        "400–600 m run",
        "25–50 m sled push or pull",
        "400–600 m run",
        "25–40 wall balls or 40–50 m lunges/carry",
        "Optional second abbreviated pass if recovery allows",
      ],
      cooldown: ["Easy aerobic", "Full mobility"],
      targetRPE: "7–9",
      whatToRecord: [
        "Total time",
        "Run splits",
        "Station times",
        "Loads/setup",
        "Primary limiter",
        "RPE",
      ],
      coachNote:
        "Manual coach insert only. Do not treat as Performance Testing Week or auto-prescribe from Sunday results yet.",
      safetyNote: MINI_BENCHMARK_ADJACENCY,
      progression: "Hold run consistency before adding a second pass.",
      regression: "Fewer stations and shorter runs.",
    },
  }),
];
