/**
 * Hybrid Engine — audited, executable bike / row / ski / mixed erg sessions.
 * Additive library only.
 */

import { buildCoachEntry, type CoachLibraryEntry } from "./hyroxCoachSessionLibraryTypes";
import type { ProgrammingSessionStandards } from "@/app/lib/hyrox-team/modules/programmingSystem/types";

const SRC = "Hybrid365 library" as const;

function engine(
  input: Omit<Parameters<typeof buildCoachEntry>[0], "category">
): CoachLibraryEntry {
  return buildCoachEntry({
    ...input,
    category: "hybrid_engine",
    source: SRC,
    tags: Array.from(new Set([...(input.tags ?? []), "hybrid_engine", "erg"])),
  });
}

function std(partial: ProgrammingSessionStandards): ProgrammingSessionStandards {
  return partial;
}

export const HYBRID_ENGINE_COACH_SESSIONS: CoachLibraryEntry[] = [
  engine({
    id: "he-bike-continuous-l1",
    sessionLibraryId: "hyrox_he_bike_continuous_l1",
    name: "Bike Continuous Engine",
    subcategory: "bike · continuous",
    level: "intermediate",
    durationMinutes: 50,
    hardDay: false,
    intensityType: "aerobic",
    impactType: "bike",
    muscularStress: "low",
    stationStress: "none",
    bikeMinutes: 45,
    equipmentRequired: ["Bike / Echo / Wattbike"],
    bestFor: ["low_impact_aerobic", "pairs_with_threshold"],
    avoidIf: [],
    tags: ["bike", "continuous", "recovery_support"],
    progressionFamily: "bike_engine",
    progressionLevel: "level_1",
    recommendedProgression: "he-row-threshold-l1",
    recommendedRegression: "30 min easy continuous · same RPE",
    editableVariables: ["durationMinutes"],
    programmingStandards: std({
      purpose: "Build bike aerobic engine with zero run impact.",
      primaryAdaptation: "bike_aerobic",
      secondaryAdaptation: "recovery_active",
      trainingPhase: ["base", "build", "deload"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 50,
      estimatedFatigueCost: "low",
      technicalDemand: "low",
      equipmentRequired: ["Bike / Echo / Wattbike"],
      progressionFamily: "bike_engine",
      progressionLevel: "level_1",
      recommendedProgression: "Row Threshold Engine (quality day) or extend this session to 50 min work",
      recommendedRegression: "30 min easy continuous",
      suggestedSessionPlacement: ["easy_day", "pairs_well_with_threshold"],
      adjacencyWarnings: [],
      expectedRpe: "3–4",
      recommendedLoggingFields: ["Duration", "Avg HR or power", "Session RPE"],
    }),
    prescription: {
      objective: "45 min continuous easy–steady bike — conversational throughout.",
      warmup: ["5 min very easy spin (included in total time feel; cadence free)"],
      mainSet: [
        "40 min continuous bike @ Z1–low Z2",
        "RPE 3–4 — must be able to speak full sentences",
        "Cadence: self-selected comfortable (typically 70–90 rpm)",
        "Stop rule: if RPE creeps to 5+, reduce resistance for 3 min then resume",
      ],
      cooldown: ["5 min very easy spin"],
      targetHR: "Z1–low Z2",
      targetRPE: "3–4",
      whatToRecord: ["Total duration", "Avg HR or power", "Session RPE"],
      coachNote: "True easy. Supports threshold and volume builder days.",
      progression: "Extend main set to 45–50 min before raising intensity.",
      regression: "30 min continuous @ same RPE.",
    },
  }),

  engine({
    id: "he-row-threshold-l1",
    sessionLibraryId: "hyrox_he_row_threshold_l1",
    name: "Row Threshold Engine",
    subcategory: "row · threshold",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Row threshold intervals",
    intensityType: "threshold",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    ergMinutes: 40,
    thresholdMinutes: 25,
    equipmentRequired: ["RowErg"],
    bestFor: ["row_engine", "threshold_support"],
    avoidIf: ["race_week", "poor_recovery_state"],
    tags: ["row", "threshold"],
    progressionFamily: "row_engine",
    progressionLevel: "level_2",
    recommendedProgression: "he-ski-threshold-l1",
    recommendedRegression: "4×4 min · 90s easy",
    editableVariables: ["reps", "repDurationMinutes", "recoverySeconds"],
    programmingStandards: std({
      purpose: "Row threshold intervals for hybrid engine without run damage.",
      primaryAdaptation: "row_threshold",
      secondaryAdaptation: "pacing",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["RowErg"],
      progressionFamily: "row_engine",
      progressionLevel: "level_2",
      recommendedProgression: "Ski Threshold Engine or 6×5 min row",
      recommendedRegression: "4×4 min",
      suggestedSessionPlacement: ["quality_erg_day"],
      adjacencyWarnings: ["hard_run_threshold", "race_simulation"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["500m splits", "Stroke rate", "Session RPE"],
    }),
    prescription: {
      objective: "5×5 min row @ threshold with 90s easy — even splits, finish with reserve.",
      warmup: ["8 min easy row", "2×1 min build to threshold feel · 45s easy"],
      mainSet: [
        "5×5 min @ row threshold effort (RPE 7–8)",
        "90s easy paddle between reps",
        "Pacing: even 500m splits across each rep; do not race rep 1",
        "Stroke rate: typically 24–28 spm unless coach specifies otherwise",
        "Stop rule: if split fades >3–4s/500m vs rep start, end the interval and use remaining as easy",
      ],
      cooldown: ["6 min easy row"],
      targetRPE: "7–8",
      whatToRecord: ["Avg 500m split each rep", "Stroke rate", "Session RPE"],
      coachNote: "Do not race the first rep.",
      progression: "Add a 6th ×5 min OR move to Ski Threshold Engine.",
      regression: "4×4 min · 90s easy.",
    },
  }),

  engine({
    id: "he-ski-threshold-l1",
    sessionLibraryId: "hyrox_he_ski_threshold_l1",
    name: "Ski Threshold Engine",
    subcategory: "ski · threshold",
    level: "intermediate",
    durationMinutes: 45,
    hardDay: true,
    hardDayReason: "Ski threshold intervals",
    intensityType: "threshold",
    impactType: "erg",
    muscularStress: "moderate",
    stationStress: "none",
    ergMinutes: 40,
    thresholdMinutes: 24,
    equipmentRequired: ["SkiErg"],
    bestFor: ["ski_engine", "threshold_support"],
    avoidIf: ["shoulder_irritation", "race_week"],
    tags: ["ski", "threshold"],
    progressionFamily: "ski_engine",
    progressionLevel: "level_2",
    recommendedProgression: "Maintain; extend reps to 5 min before adding volume",
    recommendedRegression: "he-bike-continuous-l1",
    editableVariables: ["reps", "repDurationMinutes", "recoverySeconds"],
    programmingStandards: std({
      purpose: "SkiErg threshold development for station and race engine.",
      primaryAdaptation: "ski_threshold",
      secondaryAdaptation: "upper_aerobic",
      trainingPhase: ["build", "specific"],
      suitableAthleteLevel: ["intermediate", "advanced", "pro"],
      estimatedDurationMinutes: 45,
      estimatedFatigueCost: "high",
      technicalDemand: "moderate",
      equipmentRequired: ["SkiErg"],
      progressionFamily: "ski_engine",
      progressionLevel: "level_2",
      recommendedProgression: "Longer threshold blocks",
      recommendedRegression: "Bike Continuous Engine or fewer ski reps",
      suggestedSessionPlacement: ["quality_erg_day"],
      adjacencyWarnings: ["hard_upper_day", "race_simulation"],
      expectedRpe: "7–8",
      recommendedLoggingFields: ["Splits", "Session RPE"],
    }),
    prescription: {
      objective: "6×4 min ski @ threshold with 75s easy — protect shoulders and pacing.",
      warmup: ["6 min easy ski", "Shoulder circles + band pull-aparts 1 min", "2×45s build"],
      mainSet: [
        "6×4 min @ ski threshold (RPE 7–8)",
        "75s easy ski between reps",
        "Even splits within each rep; long arm finish, braced trunk",
        "Stop rule: shoulder pain or form collapse = end hard intervals and finish easy continuous",
      ],
      cooldown: ["5 min easy ski"],
      targetRPE: "7–8",
      whatToRecord: ["Avg split each rep", "Session RPE"],
      coachNote: "Protect shoulders — stop if form collapses.",
      progression: "Extend reps to 5 min before adding a 7th interval.",
      regression: "5×3 min · 90s easy; or Bike Continuous Engine.",
    },
  }),

  engine({
    id: "he-mixed-recovery-l1",
    sessionLibraryId: "hyrox_he_mixed_recovery_l1",
    name: "Mixed Erg Recovery",
    subcategory: "mixed · recovery",
    level: "all",
    durationMinutes: 35,
    hardDay: false,
    intensityType: "recovery",
    impactType: "erg",
    muscularStress: "low",
    stationStress: "none",
    ergMinutes: 30,
    equipmentRequired: ["SkiErg and/or RowErg and/or Bike"],
    bestFor: ["recovery", "deload"],
    avoidIf: [],
    tags: ["mixed", "recovery", "deload"],
    progressionFamily: "mixed_erg_engine",
    progressionLevel: "deload",
    recommendedProgression: "he-bike-continuous-l1",
    recommendedRegression: "20 min single-modality easy flush",
    editableVariables: ["durationMinutes"],
    programmingStandards: std({
      purpose: "Very easy mixed erg flush for recovery days.",
      primaryAdaptation: "recovery",
      secondaryAdaptation: "blood_flow",
      trainingPhase: ["deload", "base", "return_to_train"],
      suitableAthleteLevel: ["beginner", "intermediate", "advanced", "pro", "all"],
      estimatedDurationMinutes: 35,
      estimatedFatigueCost: "low",
      technicalDemand: "low",
      equipmentRequired: ["SkiErg and/or RowErg and/or Bike"],
      progressionFamily: "mixed_erg_engine",
      progressionLevel: "deload",
      recommendedProgression: "Bike Continuous Engine",
      recommendedRegression: "20 min flush",
      suggestedSessionPlacement: ["recovery_day", "post_hard_day"],
      adjacencyWarnings: [],
      expectedRpe: "2–3",
      recommendedLoggingFields: ["Duration", "Session RPE"],
    }),
    prescription: {
      objective: "30 min very easy mixed erg — if it feels like work, slow down.",
      warmup: ["2 min easy on first modality"],
      mainSet: [
        "30 min total easy flush, switching every 6 min:",
        "Example order: Bike 6 → Row 6 → Ski 6 → Bike 6 → Row 6",
        "RPE 2–3 only; nasal breathing preferred",
        "Skip modalities you do not have; stay on available erg for full 30 min",
      ],
      cooldown: ["Done — session ends at 30–32 min including warm-up feel"],
      targetRPE: "2–3",
      whatToRecord: ["Duration", "Session RPE"],
      coachNote: "Recovery session — no progression via intensity.",
      progression: "Bike Continuous Engine when returning to aerobic volume.",
      regression: "20 min single-modality easy.",
    },
  }),
];
