import type { HyroxSessionCategory, HyroxSessionDefinition, HyroxSessionVariant } from "./types";
import { enrichHyroxSessionLibrary } from "./sessionLibraryEnrichments";

function v(
  summary: string,
  extra?: Partial<Omit<HyroxSessionVariant, "summary">>
): HyroxSessionVariant {
  return { summary, ...extra };
}

function defineSession(
  partial: Omit<HyroxSessionDefinition, "difficultyLevels"> & {
    difficultyLevels?: HyroxSessionDefinition["difficultyLevels"];
  }
): HyroxSessionDefinition {
  return {
    difficultyLevels: ["beginner", "intermediate", "advanced", "pro"],
    ...partial,
  };
}

// ——— Run Development ———

const RUN_SESSIONS: HyroxSessionDefinition[] = [
  defineSession({
    id: "hyrox_run_easy",
    name: "Easy Run",
    category: "run_development",
    subcategory: "aerobic_base",
    objective: "Build aerobic base and running tolerance without adding fatigue debt.",
    duration: "30–50 min",
    equipment: ["Running surface"],
    bestFor: ["recovery_days", "between_hard_sessions", "running_limited_build"],
    avoidIf: ["acute_calf_achilles_pain", "missed_previous_easy_day_when_fatigued"],
    warmup: ["5–8 min easy jog", "Leg swings", "2–3 strides (optional)"],
    mainSet: ["Continuous easy run at Z2 — conversational pace", "Optional 4×20s strides in final 10 min if fresh"],
    cooldown: ["5 min walk", "Light calf stretch"],
    intensity: "RPE 4–5 · Z2",
    beginnerVersion: v("20–30 min easy jog", { volume: "20–30 min", rest: "Walk breaks OK" }),
    intermediateVersion: v("35–45 min Z2", { volume: "35–45 min", intensity: "Prescribed easy pace from 5k" }),
    advancedVersion: v("40–50 min Z2 + strides", { volume: "40–50 min", intensity: "Lower end of easy zone" }),
    proVersion: v("45–55 min Z2 aerobic flush", { volume: "45–55 min", notes: "Strides only if HR stable" }),
    whatToRecord: ["Duration", "Avg pace", "RPE", "Pain/niggles"],
    coachNotes: ["Should feel easier than you want — bank aerobic currency."],
    tags: ["easy", "z2", "run", "aerobic"],
  }),
  defineSession({
    id: "hyrox_run_long_easy",
    name: "Long Easy Run",
    category: "run_development",
    subcategory: "aerobic_base",
    objective: "Extend aerobic duration and mental patience for race-day running volume.",
    duration: "50–85 min",
    equipment: ["Running surface"],
    bestFor: ["engine_build", "far_from_race", "balanced_intermediate"],
    avoidIf: ["poor_recovery_week", "spike_in_run_volume_last_week"],
    warmup: ["8 min easy", "Ankling + hip openers"],
    mainSet: ["Continuous easy run — stay strictly Z2", "No progression unless prescribed"],
    cooldown: ["Walk 5 min", "Fuel within 30 min"],
    intensity: "RPE 5–6 · Z2",
    beginnerVersion: v("40–50 min easy", { volume: "40–50 min max" }),
    intermediateVersion: v("55–70 min easy", { volume: "55–70 min" }),
    advancedVersion: v("65–80 min easy", { volume: "65–80 min" }),
    proVersion: v("75–90 min easy", { volume: "75–90 min", intensity: "Strict Z2 — no drift" }),
    whatToRecord: ["Duration", "Pace", "RPE", "Fuel/hydration"],
    coachNotes: ["Not a race — discipline on pace matters more than distance."],
    tags: ["long_run", "z2", "aerobic"],
  }),
  defineSession({
    id: "hyrox_run_threshold_6x6",
    name: "Threshold Run — 6 x 6 Minutes",
    category: "run_development",
    subcategory: "threshold",
    objective: "Accumulate threshold time to raise sustainable engine output.",
    duration: "55–70 min",
    equipment: ["Running surface", "Track or measurable loop"],
    bestFor: ["running_limited", "engine_build", "mid_block"],
    avoidIf: ["consecutive_hard_days", "calf_pain", "poor_sleep_3_nights"],
    warmup: ["10 min easy", "4×20s strides", "2 min easy"],
    mainSet: [
      "6×6 min @ threshold pace (from 5k/10k zones)",
      "90s–2 min easy jog between",
      "Cool 5 min easy after final rep",
    ],
    cooldown: ["8 min easy jog"],
    intensity: "RPE 7–8 · Threshold",
    beginnerVersion: v("4×4 min threshold", { volume: "4×4 min", rest: "2 min easy" }),
    intermediateVersion: v("5×5 min threshold", { volume: "5×5 min", rest: "90s easy" }),
    advancedVersion: v("6×6 min threshold", { volume: "6×6 min", rest: "90s easy" }),
    proVersion: v("6×6 min — last 2 at upper threshold", { volume: "6×6 min", intensity: "Upper zone if RPE stable" }),
    whatToRecord: ["Rep paces", "RPE per rep", "Rest quality"],
    coachNotes: ["Even splits — rep 6 should look like rep 1."],
    tags: ["threshold", "intervals", "engine"],
  }),
  defineSession({
    id: "hyrox_run_threshold_3x10",
    name: "Threshold Run — 3 x 10 Minutes",
    category: "run_development",
    subcategory: "threshold",
    objective: "Longer threshold blocks for race-pace durability.",
    duration: "60–75 min",
    equipment: ["Running surface"],
    bestFor: ["advanced_competitive", "mid_to_near_race"],
    avoidIf: ["beginner_foundation", "high_output_poor_recovery"],
    warmup: ["12 min easy", "3×20s strides"],
    mainSet: ["3×10 min @ threshold", "2–3 min easy between reps"],
    cooldown: ["10 min easy"],
    intensity: "RPE 7–8",
    beginnerVersion: v("3×5 min @ tempo-high", { volume: "3×5 min", rest: "2 min" }),
    intermediateVersion: v("3×8 min threshold", { volume: "3×8 min", rest: "2 min" }),
    advancedVersion: v("3×10 min threshold", { volume: "3×10 min" }),
    proVersion: v("3×10 min — progressive last rep", { intensity: "Last rep upper threshold" }),
    whatToRecord: ["Split times", "HR if used", "RPE"],
    coachNotes: ["Mental session — stay controlled early."],
    tags: ["threshold", "durability"],
  }),
  defineSession({
    id: "hyrox_run_5k_pace_8x3",
    name: "5km Pace Intervals — 8 x 3 Minutes",
    category: "run_development",
    subcategory: "vo2_intervals",
    objective: "Develop speed and economy above threshold without full VO2 collapse.",
    duration: "50–65 min",
    equipment: ["Running surface"],
    bestFor: ["advanced", "pre_race_sharpening"],
    avoidIf: ["running_limited_beginner", "poor_recovery"],
    warmup: ["12 min easy", "4×20s strides", "2 min easy"],
    mainSet: ["8×3 min @ 5k pace", "90s easy jog between"],
    cooldown: ["10 min easy"],
    intensity: "RPE 8–9",
    beginnerVersion: v("6×2 min @ 5k pace", { volume: "6×2 min", rest: "2 min" }),
    intermediateVersion: v("6×3 min @ 5k pace", { volume: "6×3 min" }),
    advancedVersion: v("8×3 min @ 5k pace", { volume: "8×3 min" }),
    proVersion: v("8×3 min — reps 6–8 at 5k–3k feel", { intensity: "Hold form — no sprint finish" }),
    whatToRecord: ["Rep paces", "RPE", "Form breakdown Y/N"],
    coachNotes: ["Stop if pace drops >5% on two consecutive reps."],
    tags: ["5k_pace", "intervals", "speed"],
  }),
  defineSession({
    id: "hyrox_run_parkrun_benchmark",
    name: "Parkrun / 5km Benchmark",
    category: "run_development",
    subcategory: "benchmark",
    objective: "Anchor running paces for prescription and track engine progress.",
    duration: "40–55 min",
    equipment: ["Measured 5km route"],
    bestFor: ["testing_weeks", "every_4_6_weeks"],
    avoidIf: ["taper_week", "illness", "within_48h_of_hard_compromised"],
    warmup: ["15 min easy", "4×20s strides", "3 min easy"],
    mainSet: ["5km time trial — even effort", "Optional 10 min easy after"],
    cooldown: ["10 min walk/easy"],
    intensity: "RPE 9–10 (5km effort)",
    beginnerVersion: v("5km effort — run/walk OK on course", { complexity: "Effort-based, not pace" }),
    intermediateVersion: v("5km TT — even splits target", { intensity: "From recent training" }),
    advancedVersion: v("5km TT — race effort", { intensity: "Even or slight negative split" }),
    proVersion: v("5km TT — benchmark for block", { intensity: "Full effort, controlled start" }),
    whatToRecord: ["Total time", "Splits", "RPE", "Conditions"],
    coachNotes: ["Update pace zones after — not every week."],
    tags: ["benchmark", "5k", "testing"],
  }),
  defineSession({
    id: "hyrox_run_race_pace_repeats",
    name: "Hyrox Race Pace Repeats",
    category: "run_development",
    subcategory: "race_specific",
    objective: "Practice sustained running at estimated Hyrox race pace under control.",
    duration: "45–60 min",
    equipment: ["Running surface"],
    bestFor: ["near_race", "4_6_weeks_out"],
    avoidIf: ["far_from_race", "beginner_foundation"],
    warmup: ["10 min easy", "3×20s strides"],
    mainSet: [
      "5–8×800m–1km @ estimated Hyrox race run pace",
      "Equal time easy jog recovery",
    ],
    cooldown: ["8 min easy"],
    intensity: "RPE 7–8 · Race rhythm",
    beginnerVersion: v("4×600m @ steady-hard", { volume: "4×600m" }),
    intermediateVersion: v("5×800m @ Hyrox pace estimate", { volume: "5×800m" }),
    advancedVersion: v("6×1km @ Hyrox pace", { volume: "6×1km" }),
    proVersion: v("8×1km @ Hyrox pace — even splits", { volume: "8×1km" }),
    whatToRecord: ["Rep times", "RPE", "Pace vs estimate"],
    coachNotes: ["Should feel like race km 3–6, not km 1."],
    tags: ["race_pace", "hyrox_specific", "run"],
  }),
];

// ——— Erg Development ———

const ERG_SESSIONS: HyroxSessionDefinition[] = [
  defineSession({
    id: "hyrox_erg_ski_threshold_8x4",
    name: "SkiErg Threshold — 8 x 4 Minutes",
    category: "erg_development",
    subcategory: "ski_threshold",
    objective: "Build threshold capacity on SkiErg with low running impact.",
    duration: "45–55 min",
    equipment: ["SkiErg"],
    bestFor: ["running_limited", "ski_weakness", "extra_threshold"],
    avoidIf: ["shoulder_niggle", "day_after_heavy_pulling"],
    warmup: ["5 min easy ski", "Shoulder prep", "2×1 min build"],
    mainSet: ["8×4 min @ threshold watts/pace", "60–90s easy between"],
    cooldown: ["5 min easy ski"],
    intensity: "RPE 7–8",
    beginnerVersion: v("5×3 min threshold", { volume: "5×3 min", rest: "90s" }),
    intermediateVersion: v("6×4 min threshold", { volume: "6×4 min" }),
    advancedVersion: v("8×4 min threshold", { volume: "8×4 min" }),
    proVersion: v("8×4 min — hold consistent split", { intensity: "Last 2 reps same as first" }),
    whatToRecord: ["Avg split/watts", "RPE", "Stroke rate"],
    coachNotes: ["Substitute for a run threshold when legs need relief."],
    tags: ["ski", "threshold", "erg"],
  }),
  defineSession({
    id: "hyrox_erg_row_threshold_8x4",
    name: "RowErg Threshold — 8 x 4 Minutes",
    category: "erg_development",
    subcategory: "row_threshold",
    objective: "Row-specific threshold for Hyrox station durability.",
    duration: "45–55 min",
    equipment: ["RowErg"],
    bestFor: ["row_weakness", "engine_build"],
    avoidIf: ["low_back_flare", "grip_fatigue_day"],
    warmup: ["5 min easy row", "Hinge prep", "2×1 min build"],
    mainSet: ["8×4 min @ threshold pace/500m", "60–90s easy between"],
    cooldown: ["5 min easy row"],
    intensity: "RPE 7–8",
    beginnerVersion: v("5×3 min threshold", { volume: "5×3 min" }),
    intermediateVersion: v("6×4 min threshold", { volume: "6×4 min" }),
    advancedVersion: v("8×4 min threshold", { volume: "8×4 min" }),
    proVersion: v("8×4 min — consistent 500m pace", { intensity: "No fly-and-die" }),
    whatToRecord: ["500m splits", "Watts", "RPE"],
    coachNotes: ["Posture over pull rate."],
    tags: ["row", "threshold", "erg"],
  }),
  defineSession({
    id: "hyrox_erg_mixed_aerobic",
    name: "Mixed Ski/Row Aerobic",
    category: "erg_development",
    subcategory: "mixed_z2",
    objective: "Accumulate Z2 volume on ergs without running impact.",
    duration: "40–60 min",
    equipment: ["SkiErg", "RowErg"],
    bestFor: ["easy_day_substitute", "high_output_poor_recovery"],
    avoidIf: ["needs_run_specific_stimulus_that_day"],
    warmup: ["3 min each erg easy"],
    mainSet: ["Alternating 8–12 min Ski / 8–12 min Row @ Z2", "Up to 40–50 min total work"],
    cooldown: ["5 min easy either erg"],
    intensity: "RPE 5–6",
    beginnerVersion: v("20–30 min total Z2 mixed", { volume: "20–30 min" }),
    intermediateVersion: v("35–45 min mixed Z2", { volume: "35–45 min" }),
    advancedVersion: v("45–55 min mixed Z2", { volume: "45–55 min" }),
    proVersion: v("50–60 min — stay strict Z2", { volume: "50–60 min" }),
    whatToRecord: ["Duration", "Avg splits", "RPE"],
    coachNotes: ["True easy — not sneaky threshold."],
    tags: ["z2", "ski", "row", "aerobic"],
  }),
  defineSession({
    id: "hyrox_erg_bike_z2",
    name: "Bike Z2 Aerobic",
    category: "erg_development",
    subcategory: "bike_z2",
    objective: "Add aerobic minutes with minimal impact — support engine on easy days.",
    duration: "30–60 min",
    equipment: ["Bike or spin bike"],
    bestFor: ["running_limited", "recovery_support", "doubles_z2"],
    avoidIf: ["needs_outdoor_run_skill"],
    warmup: ["5 min easy spin"],
    mainSet: ["Continuous Z2 cycling", "Cadence 80–95"],
    cooldown: ["5 min easy"],
    intensity: "RPE 4–5",
    beginnerVersion: v("25–35 min Z2", { volume: "25–35 min" }),
    intermediateVersion: v("40–50 min Z2", { volume: "40–50 min" }),
    advancedVersion: v("50–60 min Z2", { volume: "50–60 min" }),
    proVersion: v("60–75 min Z2 — fueling practice", { volume: "60–75 min" }),
    whatToRecord: ["Duration", "RPE", "HR zone"],
    coachNotes: ["Ideal PM session on double days."],
    tags: ["bike", "z2", "low_impact"],
  }),
  defineSession({
    id: "hyrox_erg_mixed_recovery",
    name: "Mixed Erg Recovery",
    category: "erg_development",
    subcategory: "recovery",
    objective: "Promote blood flow and movement quality without training stress.",
    duration: "25–35 min",
    equipment: ["SkiErg", "RowErg", "Bike"],
    bestFor: ["recovery_days", "after_hard_compromised"],
    avoidIf: ["complete_rest_prescribed"],
    warmup: ["Mobility 5 min"],
    mainSet: ["3×5 min very easy rotating erg", "Nasal breathing if possible"],
    cooldown: ["Stretch 5 min"],
    intensity: "RPE 3–4",
    beginnerVersion: v("15–20 min very easy", { volume: "15–20 min" }),
    intermediateVersion: v("25–30 min easy rotation", { volume: "25–30 min" }),
    advancedVersion: v("30–35 min easy", { volume: "30–35 min" }),
    proVersion: v("30 min flush — HR capped", { intensity: "Strict recovery" }),
    whatToRecord: ["RPE", "How legs feel after"],
    coachNotes: ["Should feel better after, not worse."],
    tags: ["recovery", "erg", "easy"],
  }),
];

// ——— Compromised Running ———

const COMPROMISED_SESSIONS: HyroxSessionDefinition[] = [
  defineSession({
    id: "hyrox_compromised_mini_test",
    name: "Mini Hyrox Compromised Run Test",
    category: "compromised_running",
    subcategory: "benchmark",
    objective: "Standardised compromised running benchmark for pacing and progress.",
    duration: "35–50 min",
    equipment: ["SkiErg or Row", "Wall ball", "Running space"],
    bestFor: ["testing", "baseline", "every_4_6_weeks"],
    avoidIf: ["taper", "injury", "far_overreached"],
    warmup: ["10 min easy run", "Station movement prep"],
    mainSet: [
      "1000m SkiErg or Row @ strong steady",
      "40 wall balls",
      "1000m run @ best sustainable",
      "Record total time + run split",
    ],
    cooldown: ["10 min easy"],
    intensity: "RPE 8–9",
    beginnerVersion: v("500m erg + 25 WB + 800m run", { volume: "Reduced distances" }),
    intermediateVersion: v("Standard mini test", { volume: "As prescribed" }),
    advancedVersion: v("Standard — race effort on run", { intensity: "Race rhythm" }),
    proVersion: v("Standard + target split card", { intensity: "Even station pacing" }),
    whatToRecord: ["Total time", "Run 1km split", "Station times", "RPE"],
    coachNotes: ["Use to set compromised run pace targets."],
    tags: ["benchmark", "compromised", "test"],
  }),
  defineSession({
    id: "hyrox_compromised_sled_burpee",
    name: "Sled Push/Pull + Burpee Compromised Builder",
    category: "compromised_running",
    subcategory: "station_to_run",
    objective: "Build ability to run after heavy lower-body station work.",
    duration: "45–55 min",
    equipment: ["Sled", "Running space"],
    bestFor: ["station_limited", "mid_block"],
    avoidIf: ["acute_low_back", "calf_tear_risk"],
    warmup: ["Easy jog 8 min", "Sled empty pushes x3"],
    mainSet: [
      "2–4 rounds: Sled push + pull (prescribed load)",
      "15–25 burpee broad jumps or burpees",
      "600–1000m run @ steady-hard",
      "Rest 2–3 min between rounds",
    ],
    cooldown: ["8 min easy"],
    intensity: "RPE 7–8",
    beginnerVersion: v("2 rounds — light sled, 600m run", { load: "Light", volume: "2 rounds" }),
    intermediateVersion: v("3 rounds — moderate load", { volume: "3 rounds" }),
    advancedVersion: v("4 rounds — race load", { load: "Race weight" }),
    proVersion: v("4 rounds — minimal rest, race load", { rest: "90s", load: "Race" }),
    whatToRecord: ["Run splits per round", "Sled feel", "RPE"],
    coachNotes: ["Run rep 1 pace = run rep 4 pace goal."],
    tags: ["sled", "burpee", "compromised"],
  }),
  defineSession({
    id: "hyrox_compromised_run_lunges",
    name: "Run + Lunges Compromised Builder",
    category: "compromised_running",
    subcategory: "station_to_run",
    objective: "Improve sandbag lunge durability and running after leg fatigue.",
    duration: "45–60 min",
    equipment: ["Sandbag", "Running space"],
    bestFor: ["lunge_weakness", "station_limited"],
    avoidIf: ["knee_pain", "DOMS_from_heavy_legs"],
    warmup: ["8 min easy", "Lunge pattern prep"],
    mainSet: [
      "3–5 rounds: 50–100m sandbag lunges",
      "800m run @ controlled hard",
      "Rest 2 min",
    ],
    cooldown: ["8 min easy"],
    intensity: "RPE 7–8",
    beginnerVersion: v("2 rounds — 50m lunges, 600m run", { load: "Light bag" }),
    intermediateVersion: v("3 rounds — 75m, 800m run", { load: "Moderate" }),
    advancedVersion: v("4 rounds — 100m, 800m run", { load: "Race weight" }),
    proVersion: v("5 rounds — race weight, 800m even splits", { volume: "5 rounds" }),
    whatToRecord: ["Lunge breaks", "Run pace each round", "RPE"],
    coachNotes: ["Walk lunges if form breaks — don't race the lunge."],
    tags: ["lunges", "sandbag", "compromised"],
  }),
  defineSession({
    id: "hyrox_compromised_run_wallballs",
    name: "Run + Wall Balls Builder",
    category: "compromised_running",
    subcategory: "station_to_run",
    objective: "Train wall ball efficiency and running after upper-fatigue breathing stress.",
    duration: "40–55 min",
    equipment: ["Wall ball", "Running space"],
    bestFor: ["wall_ball_weakness", "near_race"],
    avoidIf: ["shoulder_pain"],
    warmup: ["8 min easy", "WB technique sets"],
    mainSet: [
      "3–5 rounds: 30–50 wall balls",
      "600–1000m run @ steady-hard",
      "Rest 90s–2 min",
    ],
    cooldown: ["8 min easy"],
    intensity: "RPE 7–8",
    beginnerVersion: v("2 rounds — 25 WB, 600m run", { volume: "2 rounds" }),
    intermediateVersion: v("3 rounds — 40 WB, 800m run", { volume: "3 rounds" }),
    advancedVersion: v("4 rounds — 50 WB, 1000m run", { volume: "4 rounds" }),
    proVersion: v("5 rounds — unbroken WB goal, even runs", { intensity: "Race sets on WB" }),
    whatToRecord: ["WB breaks", "Run splits", "RPE"],
    coachNotes: ["Breathe on WB — don't treat as max strength."],
    tags: ["wall_ball", "compromised", "run"],
  }),
  defineSession({
    id: "hyrox_compromised_threshold_station",
    name: "Threshold Into Station Overload",
    category: "compromised_running",
    subcategory: "race_specific",
    objective: "Blend threshold running with immediate station work — late-race simulation.",
    duration: "50–65 min",
    equipment: ["SkiErg", "Row", "Wall ball", "Running space"],
    bestFor: ["advanced", "near_race"],
    avoidIf: ["beginner", "poor_recovery"],
    warmup: ["10 min easy", "Strides"],
    mainSet: [
      "2–3 blocks: 8–12 min threshold run",
      "Immediately into station triplet (e.g. 500m ski + 30 WB)",
      "4 min easy between blocks",
    ],
    cooldown: ["10 min easy"],
    intensity: "RPE 8–9",
    beginnerVersion: v("2 blocks — 6 min tempo + short stations", { volume: "2 blocks" }),
    intermediateVersion: v("2 blocks — 10 min threshold + stations", { volume: "2 blocks" }),
    advancedVersion: v("3 blocks — full prescription", { volume: "3 blocks" }),
    proVersion: v("3 blocks — race loads, minimal rest", { intensity: "Race simulation" }),
    whatToRecord: ["Run pace decay", "Station splits", "RPE"],
    coachNotes: ["Hardest session of the week — protect with easy days around it."],
    tags: ["threshold", "compromised", "race_specific"],
  }),
];

// ——— Strength ———

const STRENGTH_SESSIONS: HyroxSessionDefinition[] = [
  defineSession({
    id: "hyrox_strength_upper_emom",
    name: "Upper Strength Density EMOM",
    category: "strength",
    subcategory: "upper_density",
    objective: "Upper body strength endurance for sled pull, carries and station control.",
    duration: "40–50 min",
    equipment: ["Dumbbells", "Pull-up bar", "Cable/bands"],
    bestFor: ["station_support", "time_crunched"],
    avoidIf: ["shoulder_injury", "day_before_heavy_ski_volume"],
    warmup: ["Band shoulders", "2 warm-up rounds light"],
    mainSet: ["EMOM 30–40 min rotating: push, pull, carry, core", "Load moderate — no failure"],
    cooldown: ["Stretch lats/pecs"],
    intensity: "RPE 6–7",
    beginnerVersion: v("20 min EMOM — basic patterns", { volume: "20 min" }),
    intermediateVersion: v("30 min EMOM", { volume: "30 min" }),
    advancedVersion: v("40 min EMOM — heavier", { volume: "40 min" }),
    proVersion: v("40 min — race-grip emphasis", { load: "Heavy carries each 4th min" }),
    whatToRecord: ["Loads", "RPE", "Failed reps Y/N"],
    coachNotes: ["Stop set before grind — density is the goal."],
    tags: ["upper", "emom", "strength"],
  }),
  defineSession({
    id: "hyrox_strength_upper_full",
    name: "Upper Strength Full Session",
    category: "strength",
    subcategory: "upper_strength",
    objective: "Build maximal strength and muscle for pulling and pressing stations.",
    duration: "50–65 min",
    equipment: ["Gym weights", "Pull-up bar"],
    bestFor: ["strength_dominant", "off_season_base"],
    avoidIf: ["compromised_day_next", "grip_shot"],
    warmup: ["Upper activation", "Ramp sets"],
    mainSet: ["Compound push + pull + accessory", "3–5 sets strength range"],
    cooldown: ["Mobility"],
    intensity: "RPE 7–8",
    beginnerVersion: v("2–3 exercises, machine/band assist", { volume: "Lower sets" }),
    intermediateVersion: v("Full session — moderate loads", { volume: "Standard" }),
    advancedVersion: v("Full session — progressive load", { load: "Heavy compounds" }),
    proVersion: v("Heavy + power — low rep", { intensity: "Strength focus" }),
    whatToRecord: ["Top sets", "RPE", "Volume"],
    coachNotes: ["Not a Hyrox simulation — build capacity."],
    tags: ["upper", "strength"],
  }),
  defineSession({
    id: "hyrox_strength_heavy_legs",
    name: "Heavy Legs — Hyrox Durability",
    category: "strength",
    subcategory: "lower_strength",
    objective: "Leg strength for sled, lunges and running resilience.",
    duration: "50–60 min",
    equipment: ["Barbell", "Squat rack", "Sled optional"],
    bestFor: ["station_limited", "base_phase"],
    avoidIf: ["48h_before_key_run", "knee_pain"],
    warmup: ["Hinge/squat prep", "Ramp sets"],
    mainSet: ["Squat or trap bar + RDL + accessory", "Strength rep ranges"],
    cooldown: ["Hip mobility"],
    intensity: "RPE 7–8",
    beginnerVersion: v("Goblet squat + RDL — technique", { load: "Light-moderate" }),
    intermediateVersion: v("Standard strength loads", { load: "Moderate-heavy" }),
    advancedVersion: v("Heavy compounds", { load: "Heavy" }),
    proVersion: v("Heavy + sled finish sets", { load: "Race prep" }),
    whatToRecord: ["Loads", "RPE", "Soreness next day"],
    coachNotes: ["Separate from compromised by 48h minimum."],
    tags: ["legs", "strength", "durability"],
  }),
  defineSession({
    id: "hyrox_strength_lower_sled",
    name: "Lower Strength — Sled Support",
    category: "strength",
    subcategory: "sled_strength",
    objective: "Sled-specific leg drive and position strength.",
    duration: "45–55 min",
    equipment: ["Sled", "Squat rack"],
    bestFor: ["sled_weakness"],
    avoidIf: ["low_back_flare"],
    warmup: ["Empty sled pushes", "Leg activation"],
    mainSet: ["Strength lift + sled push/pull sets", "Focus on body angle"],
    cooldown: ["Hip flexor stretch"],
    intensity: "RPE 7",
    beginnerVersion: v("Light sled + goblet squat", { load: "Light" }),
    intermediateVersion: v("Moderate sled volumes", { load: "Moderate" }),
    advancedVersion: v("Race-weight sled work", { load: "Race" }),
    proVersion: v("Race load — density sets", { volume: "Higher sets" }),
    whatToRecord: ["Sled loads", "RPE", "Technique notes"],
    coachNotes: ["Low hips on push — long arms on pull."],
    tags: ["sled", "lower", "strength"],
  }),
  defineSession({
    id: "hyrox_strength_single_leg",
    name: "Single-Leg Durability",
    category: "strength",
    subcategory: "unilateral",
    objective: "Unilateral strength for lunges, running stability and injury prevention.",
    duration: "40–50 min",
    equipment: ["Dumbbells", "Bench"],
    bestFor: ["everyone", "lunge_support"],
    avoidIf: ["acute_knee_pain"],
    warmup: ["Split squat warm-up"],
    mainSet: ["Bulgarian split squat, step-ups, single-leg RDL", "3–4 sets each"],
    cooldown: ["Hip mobility"],
    intensity: "RPE 6–7",
    beginnerVersion: v("Bodyweight + supported split squat", { load: "BW" }),
    intermediateVersion: v("DB loads — moderate", { load: "Moderate" }),
    advancedVersion: v("Heavy unilateral", { load: "Heavy" }),
    proVersion: v("Heavy + tempo lunges", { complexity: "Tempo reps" }),
    whatToRecord: ["Loads", "L/R balance", "RPE"],
    coachNotes: ["Quality over load — knee tracks toe."],
    tags: ["single_leg", "durability"],
  }),
  defineSession({
    id: "hyrox_strength_grip_carry",
    name: "Grip + Carry Strength",
    category: "strength",
    subcategory: "carry",
    objective: "Farmer carry and grip endurance for Hyrox stations.",
    duration: "35–45 min",
    equipment: ["Kettlebells", "Farmer handles"],
    bestFor: ["carry_weakness", "grip_limiter"],
    avoidIf: ["forearm_tendon_pain"],
    warmup: ["Dead hangs", "Light carries"],
    mainSet: ["Farmer carries, suitcase, dead hangs", "Progressive distance/load"],
    cooldown: ["Forearm stretch"],
    intensity: "RPE 6–8",
    beginnerVersion: v("Light carries — short distance", { load: "Light" }),
    intermediateVersion: v("Moderate load — race distance practice", { load: "Moderate" }),
    advancedVersion: v("Race load carries", { load: "Race" }),
    proVersion: v("Heavy + race distance under fatigue", { load: "Heavy/race" }),
    whatToRecord: ["Load", "Distance", "Grip failure point"],
    coachNotes: ["Fast feet — don't grip-only shuffle."],
    tags: ["carry", "grip", "farmer"],
  }),
  defineSession({
    id: "hyrox_strength_posterior",
    name: "Posterior Chain Strength",
    category: "strength",
    subcategory: "posterior",
    objective: "Hamstring/glute strength for running economy and sled pull.",
    duration: "45–55 min",
    equipment: ["Barbell", "GHD or bench"],
    bestFor: ["running_economy", "pull_weakness"],
    avoidIf: ["hamstring_strain"],
    warmup: ["Hinge patterning"],
    mainSet: ["RDL, hip thrust, hamstring curl", "Strength ranges"],
    cooldown: ["Hamstring stretch"],
    intensity: "RPE 7",
    beginnerVersion: v("DB RDL + glute bridge", { load: "Light" }),
    intermediateVersion: v("Standard hinge loads", { load: "Moderate" }),
    advancedVersion: v("Heavy RDL/hip thrust", { load: "Heavy" }),
    proVersion: v("Heavy + power hinge", { intensity: "Power subset" }),
    whatToRecord: ["Loads", "RPE"],
    coachNotes: ["Support running — don't replace running."],
    tags: ["posterior", "hinge", "strength"],
  }),
  defineSession({
    id: "hyrox_strength_calf_achilles",
    name: "Calf/Achilles Resilience",
    category: "strength",
    subcategory: "prehab",
    objective: "Tissue capacity for running volume and elastic rebound.",
    duration: "25–35 min",
    equipment: ["Step", "Bands"],
    bestFor: ["running_limited", "volume_ramp"],
    avoidIf: ["acute_tendon_pain — rehab only"],
    warmup: ["Ankle circles", "Walk drills"],
    mainSet: ["Calf raises — straight/bent knee", "Slow eccentrics", "Pogo hops if tolerated"],
    cooldown: ["Soleus stretch"],
    intensity: "RPE 5–6",
    beginnerVersion: v("2×15 raises — bodyweight", { volume: "Low" }),
    intermediateVersion: v("3×12–15 loaded", { load: "Moderate" }),
    advancedVersion: v("Heavy slow eccentrics + hops", { load: "Heavy" }),
    proVersion: v("Full prehab + plyo prep", { complexity: "Plyometric progression" }),
    whatToRecord: ["Pain 0–10", "Reps completed"],
    coachNotes: ["Daily micro-dose OK on easy days."],
    tags: ["calf", "achilles", "prehab", "running"],
  }),
];

// ——— Testing ———

const TESTING_SESSIONS: HyroxSessionDefinition[] = [
  defineSession({
    id: "hyrox_test_5k_tt",
    name: "5km Time Trial",
    category: "testing",
    subcategory: "run_benchmark",
    objective: "Primary run benchmark for pace prescription.",
    duration: "40–55 min",
    equipment: ["5km route"],
    bestFor: ["baseline", "retest"],
    avoidIf: ["taper", "injury"],
    warmup: ["15 min easy", "Strides"],
    mainSet: ["5km all-out effort"],
    cooldown: ["10 min easy"],
    intensity: "Max effort",
    beginnerVersion: v("5km effort — walk breaks allowed", { complexity: "Effort-based" }),
    intermediateVersion: v("5km TT", { intensity: "Even effort" }),
    advancedVersion: v("5km TT — splits", { intensity: "Even/negative" }),
    proVersion: v("5km TT — benchmark", { intensity: "Race" }),
    whatToRecord: ["Time", "Conditions", "RPE"],
    coachNotes: ["Update pace calculator inputs."],
    tags: ["test", "5k", "benchmark"],
  }),
  defineSession({
    id: "hyrox_test_1k_ski",
    name: "1km SkiErg Test",
    category: "testing",
    subcategory: "erg_benchmark",
    objective: "Ski benchmark for erg pacing.",
    duration: "25–35 min",
    equipment: ["SkiErg"],
    bestFor: ["baseline"],
    avoidIf: ["shoulder_injury"],
    warmup: ["5 min easy ski", "Builds"],
    mainSet: ["1000m SkiErg max effort"],
    cooldown: ["5 min easy"],
    intensity: "Max effort",
    beginnerVersion: v("500m max effort", { volume: "500m" }),
    intermediateVersion: v("1000m test", { volume: "1000m" }),
    advancedVersion: v("1000m test", { volume: "1000m" }),
    proVersion: v("1000m — even splits", { intensity: "Paced" }),
    whatToRecord: ["Time", "Avg split", "SR"],
    coachNotes: ["Same damper/settings each retest."],
    tags: ["test", "ski", "benchmark"],
  }),
  defineSession({
    id: "hyrox_test_1k_row",
    name: "1km RowErg Test",
    category: "testing",
    subcategory: "erg_benchmark",
    objective: "Row benchmark for erg pacing.",
    duration: "25–35 min",
    equipment: ["RowErg"],
    bestFor: ["baseline"],
    avoidIf: ["low_back_acute"],
    warmup: ["5 min easy row"],
    mainSet: ["1000m Row max effort"],
    cooldown: ["5 min easy"],
    intensity: "Max effort",
    beginnerVersion: v("500m test", { volume: "500m" }),
    intermediateVersion: v("1000m test", { volume: "1000m" }),
    advancedVersion: v("1000m test", { volume: "1000m" }),
    proVersion: v("1000m — negative split", { intensity: "Paced" }),
    whatToRecord: ["Time", "500m splits"],
    coachNotes: ["Record drag factor."],
    tags: ["test", "row", "benchmark"],
  }),
  defineSession({
    id: "hyrox_test_wallball",
    name: "Wall Ball Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    objective: "Max unbroken or 2-min wall ball benchmark.",
    duration: "20–30 min",
    equipment: ["Wall ball 6/9kg"],
    bestFor: ["wall_ball_limiter"],
    avoidIf: ["shoulder_pain"],
    warmup: ["WB technique", "10 reps"],
    mainSet: ["Max unbroken wall balls OR 2 min max reps"],
    cooldown: ["Shoulder mobility"],
    intensity: "RPE 9",
    beginnerVersion: v("Max reps in 2 min — lighter ball", { load: "Lighter ball" }),
    intermediateVersion: v("Max unbroken or 2 min", { load: "Category weight" }),
    advancedVersion: v("Max unbroken — category ball", { load: "Race weight" }),
    proVersion: v("Max unbroken + 50 rep time trial", { complexity: "Dual metric" }),
    whatToRecord: ["Reps", "Breaks", "Ball weight"],
    coachNotes: ["Same target height each test."],
    tags: ["test", "wall_ball", "benchmark"],
  }),
  defineSession({
    id: "hyrox_test_sled",
    name: "Sled Push/Pull Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    objective: "Timed sled push + pull at category load.",
    duration: "30–40 min",
    equipment: ["Sled", "50m track"],
    bestFor: ["sled_limiter"],
    avoidIf: ["low_back_acute"],
    warmup: ["Empty sled", "Activation"],
    mainSet: ["50m push + 50m pull @ race load — timed", "2–3 attempts with full rest"],
    cooldown: ["Walk", "Hip stretch"],
    intensity: "RPE 9",
    beginnerVersion: v("Light load — technique focus", { load: "50% race" }),
    intermediateVersion: v("Moderate load timed", { load: "75% race" }),
    advancedVersion: v("Race load timed", { load: "100%" }),
    proVersion: v("Race load — best of 2", { load: "100%" }),
    whatToRecord: ["Push time", "Pull time", "Load"],
    coachNotes: ["Same surface each test."],
    tags: ["test", "sled", "benchmark"],
  }),
  defineSession({
    id: "hyrox_test_lunge",
    name: "Sandbag Lunge Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    objective: "Max distance or 4 min lunge test at category load.",
    duration: "25–35 min",
    equipment: ["Sandbag"],
    bestFor: ["lunge_limiter"],
    avoidIf: ["knee_pain"],
    warmup: ["Lunge pattern", "Light bag"],
    mainSet: ["100m timed lunges OR max distance in 4 min"],
    cooldown: ["Hip stretch"],
    intensity: "RPE 8–9",
    beginnerVersion: v("50m light bag", { load: "Light", volume: "50m" }),
    intermediateVersion: v("100m moderate", { load: "Moderate" }),
    advancedVersion: v("100m race weight", { load: "Race" }),
    proVersion: v("100m race — no breaks", { load: "Race" }),
    whatToRecord: ["Time", "Breaks", "Load"],
    coachNotes: ["Walk steps count — no hopping."],
    tags: ["test", "lunge", "sandbag"],
  }),
  defineSession({
    id: "hyrox_test_farmer",
    name: "Farmer's Carry Benchmark",
    category: "testing",
    subcategory: "station_benchmark",
    objective: "Timed carry at category load over race distance.",
    duration: "20–30 min",
    equipment: ["Farmer handles"],
    bestFor: ["carry_limiter"],
    avoidIf: ["grip_injury"],
    warmup: ["Light carries"],
    mainSet: ["200m farmer carry @ race load — timed"],
    cooldown: ["Grip stretch"],
    intensity: "RPE 8–9",
    beginnerVersion: v("100m light load", { load: "Light", volume: "100m" }),
    intermediateVersion: v("200m moderate", { load: "Moderate" }),
    advancedVersion: v("200m race load", { load: "Race" }),
    proVersion: v("200m race — best of 2", { load: "Race" }),
    whatToRecord: ["Time", "Load", "Grip breaks"],
    coachNotes: ["Upright posture — quick feet."],
    tags: ["test", "farmer", "carry"],
  }),
];

const HYROX_SESSION_LIBRARY_BASE: HyroxSessionDefinition[] = [
  ...RUN_SESSIONS,
  ...ERG_SESSIONS,
  ...COMPROMISED_SESSIONS,
  ...STRENGTH_SESSIONS,
  ...TESTING_SESSIONS,
];

/** Base templates + enrichments (progression examples, film prompts, prescription rationale). */
export const HYROX_SESSION_LIBRARY: HyroxSessionDefinition[] =
  enrichHyroxSessionLibrary(HYROX_SESSION_LIBRARY_BASE);

export const HYROX_SESSION_LIBRARY_BASE_EXPORT = HYROX_SESSION_LIBRARY_BASE;

export const HYROX_SESSION_BY_ID: Record<string, HyroxSessionDefinition> = Object.fromEntries(
  HYROX_SESSION_LIBRARY.map((s) => [s.id, s])
);

export function getHyroxSession(id: string): HyroxSessionDefinition | undefined {
  return HYROX_SESSION_BY_ID[id];
}

export function getHyroxSessionsByCategory(
  category: HyroxSessionCategory
): HyroxSessionDefinition[] {
  return HYROX_SESSION_LIBRARY.filter((s) => s.category === category);
}

export function searchHyroxSessionsByTag(tag: string): HyroxSessionDefinition[] {
  const t = tag.toLowerCase();
  return HYROX_SESSION_LIBRARY.filter((s) => s.tags.some((x) => x.toLowerCase().includes(t)));
}
